// The network catalogue: every network card and the subcategories they sort into.
// Adding a card means one entry here, one file beside it, one poster, one note.

// The SUBCATEGORIES list below is an ORDER, not a set: the sequence is an editorial argument
// about what a reader has to know first, never alphabetical and never a merge artefact.

export const SUBCATEGORIES = [
    { key: 'network-foundations',        label: 'Network Foundations'    },
    { key: 'pod-networking',     label: 'Pod Networking'         },
    { key: 'services-endpoints', label: 'Services & Endpoints'   },
    { key: 'external-traffic',   label: 'External Traffic'       },
    { key: 'dns-service-discovery',                label: 'DNS & Service Discovery' },
];

export const CARDS = [
  {
    id: 'network-model',
    title: 'Flat Pod Network Model',
    category: 'network',
    subcategory: 'network-foundations',
    desc: 'What does Kubernetes actually promise about the network? The model is one flat address space: every Pod gets a cluster-unique IP, any Pod reaches any other Pod on any Node with no NAT so the real source IP is preserved, and the Node agent reaches every Pod on its own Node. None of this lives in the core, a CNI plugin like Calico, Cilium or Flannel is what wires Pods into the flat space. Three rules, and a conformant plugin upholds all three.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Cluster Networking', href: 'https://kubernetes.io/docs/concepts/cluster-administration/networking/' },
      { label: 'The Kubernetes Network Model', href: 'https://kubernetes.io/docs/concepts/services-networking/#the-kubernetes-network-model' },
    ],
  },
  {
    id: 'network-namespaces',
    title: 'Network Namespaces',
    category: 'network',
    subcategory: 'network-foundations',
    desc: 'What makes a Pod IP feel like a separate machine? A network namespace is a private copy of the Linux network stack, with its own interfaces, routing table, iptables rules and port space. The pause container holds one that every container in the Pod shares, so they reach each other over loopback, while a single veth pair is the only link to the host. Deleting the Pod releases the veth and the IP together, so nothing of that stack outlives it on the Node.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Cluster Networking', href: 'https://kubernetes.io/docs/concepts/cluster-administration/networking/' },
      { label: 'CNI Specification', href: 'https://github.com/containernetworking/cni/blob/main/SPEC.md' },
    ],
  },
  {
    id: 'network-service-cidr',
    title: 'Service CIDR and ClusterIP Allocation',
    category: 'network',
    subcategory: 'network-foundations',
    desc: 'Where does a Service ClusterIP come from when nobody assigns it? The cluster carves it out of one Service CIDR split into two bands: the allocator draws from the large dynamic band and falls back to the small static one only when that runs out, so a hand-picked address like kube-dns on 10.96.0.10 is never reserved, only unlikely to be taken. Each allocation is tracked by an IPAddress object, and a second ServiceCIDR grows the range with no downtime.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Service ClusterIP Allocation', href: 'https://kubernetes.io/docs/concepts/services-networking/cluster-ip-allocation/' },
      { label: 'Extend Service IP Ranges', href: 'https://kubernetes.io/docs/tasks/network/extend-service-ip-ranges/' },
      { label: 'Service', href: 'https://kubernetes.io/docs/concepts/services-networking/service/' },
    ],
  },
  {
    id: 'network-dualstack',
    title: 'Dual-Stack IPv4 and IPv6',
    category: 'network',
    subcategory: 'network-foundations',
    desc: 'What changes when a cluster runs IPv4 and IPv6 side by side? The CNI gives every Pod one address per family on the same eth0, and a Service set to ipFamilyPolicy PreferDualStack gets one ClusterIP per family, ordered by ipFamilies. Where only one family exists, PreferDualStack falls back to a single ClusterIP while RequireDualStack fails the Service outright. A client resolves both A and AAAA records and connects over whichever family it prefers.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'IPv4/IPv6 Dual-Stack', href: 'https://kubernetes.io/docs/concepts/services-networking/dual-stack/' },
    ],
  },
  {
    id: 'network-kube-proxy-modes',
    title: 'kube-proxy: iptables vs IPVS',
    category: 'network',
    subcategory: 'network-foundations',
    desc: 'How does kube-proxy pick a backend, and why does the mode matter at scale? In iptables mode a packet to a ClusterIP walks KUBE-SERVICES into a per-Service chain that picks an endpoint by probability, then a per-endpoint chain DNATs it to the Pod. IPVS mode makes the same choice with an in-kernel hash table, trading the rule walk for constant-time lookup, though v1.35 deprecates it in favour of nftables. Either way conntrack pins the flow to the chosen backend.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Virtual IPs and Service Proxies', href: 'https://kubernetes.io/docs/reference/networking/virtual-ips/' },
    ],
  },
  {
    id: 'network-netfilter-path',
    title: 'The Netfilter Path a Packet Takes',
    category: 'network',
    subcategory: 'network-foundations',
    desc: 'Why must the DNAT that kube-proxy programs run before routing? A packet enters at PREROUTING, where conntrack records the flow and the nat table rewrites the Service address to a backend Pod, and only then does routing run, on the already rewritten address. MASQUERADE sits at POSTROUTING for the mirror reason: only after routing is the source known. The reply is untangled by conntrack, walking no Service rule.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Virtual IPs and Service Proxies', href: 'https://kubernetes.io/docs/reference/networking/virtual-ips/' },
      { label: 'Cluster Networking', href: 'https://kubernetes.io/docs/concepts/cluster-administration/networking/' },
      { label: 'netfilter packet flow', href: 'https://wiki.nftables.org/wiki-nftables/index.php/Netfilter_hooks' },
    ],
  },
  {
    id: 'network-ebpf-dataplane',
    title: 'eBPF Dataplane',
    category: 'network',
    subcategory: 'network-foundations',
    desc: 'How does the modern dataplane route Services without iptables? The CNI agent attaches eBPF programs to kernel hooks and keeps Service and endpoint state in BPF maps. A connection to a ClusterIP is then looked up and rewritten to a backend right at the socket: connect-time load balancing instead of per-packet DNAT, with constant-time lookups that let kube-proxy and its iptables chains be removed entirely. The rewrite lands before the first packet is built.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Virtual IPs and Service Proxies', href: 'https://kubernetes.io/docs/reference/networking/virtual-ips/' },
      { label: 'eBPF', href: 'https://ebpf.io/what-is-ebpf/' },
    ],
  },
  {
    id: 'network-conntrack-nat',
    title: 'Connection Tracking and NAT',
    category: 'network',
    subcategory: 'network-foundations',
    desc: 'A connection is more than one packet, so how does NAT remember the backend it picked? The first packet of a new flow creates a conntrack entry recording the original and translated tuples, and is DNAT-ed to a backend chosen once. Every later packet matches that stored entry instead of walking rules again, and the returning reply is what flips it to ESTABLISHED. That is why a flow sticks to one backend, and why a busy Node can exhaust the conntrack table.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Virtual IPs and Service Proxies', href: 'https://kubernetes.io/docs/reference/networking/virtual-ips/' },
      { label: 'Cluster Networking', href: 'https://kubernetes.io/docs/concepts/cluster-administration/networking/' },
    ],
  },
  {
    id: 'network-pod-localhost',
    title: 'Containers Share Localhost',
    category: 'network',
    subcategory: 'pod-networking',
    desc: 'Why can an app and its sidecar reach each other over 127.0.0.1 with no network in between? Every container in a Pod joins the same network namespace, so they share one loopback, one eth0 and one Pod IP. Calls between them cross the loopback with no veth hop, and because the port space is shared too, two of them cannot bind the same port. From outside the Pod is one host, however many containers run inside, and every one of them answers on that single IP.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Pod networking', href: 'https://kubernetes.io/docs/concepts/workloads/pods/#pod-networking' },
      { label: 'Cluster Networking', href: 'https://kubernetes.io/docs/concepts/cluster-administration/networking/' },
    ],
  },
  {
    id: 'network-hostnetwork-hostport',
    title: 'hostNetwork and hostPort',
    category: 'network',
    subcategory: 'pod-networking',
    desc: 'What are the two sanctioned ways to reach a Pod on the Node address itself? With hostNetwork true the Pod gets no network namespace of its own, no veth and no Pod IP, and binds the Node interfaces directly, which is how kube-proxy and a CNI agent run. A hostPort gives up nothing: the Pod keeps its namespace, its IP and its veth, and the portmap plugin only adds a DNAT rule. Both spend a Node port, so the scheduler fits only one such replica per Node.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Pod networking', href: 'https://kubernetes.io/docs/concepts/workloads/pods/#pod-networking' },
      { label: 'Do not use hostPort or hostNetwork lightly', href: 'https://kubernetes.io/blog/2025/11/25/configuration-good-practices/#avoid-hostport-and-hostnetwork-unless-absolutely-necessary' },
      { label: 'CNI portmap plugin', href: 'https://www.cni.dev/plugins/current/meta/portmap/' },
    ],
  },
  {
    id: 'network-ipam-pod-cidr',
    title: 'IPAM and Pod CIDR Allocation',
    category: 'network',
    subcategory: 'pod-networking',
    desc: 'How does every Pod in the cluster end up with a unique IP and no clashes? The cluster starts from one large pod CIDR, and the controller-manager, whenever it is started with --allocate-node-cidrs, carves a smaller non-overlapping slice out of it for each Node into node.spec.podCIDR. The CNI IPAM on that Node then hands out addresses only from its own slice, which keeps every Pod IP unique cluster-wide and keeps routing down to a single route per Node.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'kube-controller-manager', href: 'https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/' },
      { label: 'Cluster Networking', href: 'https://kubernetes.io/docs/concepts/cluster-administration/networking/' },
    ],
  },
  {
    id: 'network-cni-invocation',
    title: 'Wiring a Pod via CNI',
    category: 'network',
    subcategory: 'pod-networking',
    desc: 'Who actually plumbs a Pod onto the network? The Kubelet asks the CRI runtime to create the Pod sandbox, a pause container holding a fresh network namespace with loopback only. The runtime then invokes the CNI ADD operation, and the plugin chain creates a veth pair, attaches it to the host and draws an IP from IPAM. That address and its routes land in the namespace as eth0, and the DNS rides back in the result.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'CNI Specification', href: 'https://github.com/containernetworking/cni/blob/main/SPEC.md' },
      { label: 'Network Plugins', href: 'https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/' },
    ],
  },
  {
    id: 'network-pod-ip-and-veth',
    title: 'Pod IP and the veth Pair',
    category: 'network',
    subcategory: 'pod-networking',
    desc: 'Where does a Pod get its IP, and how is it wired to the Node? The pause container opens one network namespace that every container in the Pod is joined into, so they share a single address and reach each other over localhost. When the sandbox starts the CNI plugin draws one Pod IP from its IPAM and builds a veth pair, moving one end into the namespace as eth0 and attaching the peer to the cni0 host bridge. That pair is the only way out.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Cluster Networking', href: 'https://kubernetes.io/docs/concepts/cluster-administration/networking/' },
      { label: 'CNI Specification', href: 'https://github.com/containernetworking/cni/blob/main/SPEC.md' },
    ],
  },
  {
    id: 'network-pod-to-pod-same-node',
    title: 'Pod-to-Pod on the Same Node',
    category: 'network',
    subcategory: 'pod-networking',
    desc: 'How does a packet get from one Pod to another when both run on the same Node? The two share the Node podCIDR subnet, so the source simply sends to the destination Pod IP and the frame crosses a veth pair onto the cni0 bridge. The bridge switches it straight out the peer veth at layer 2, with no NAT and no encapsulation anywhere, so the real source IP arrives intact and the packet never touches the physical NIC. ARP resolves the peer first.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Cluster Networking', href: 'https://kubernetes.io/docs/concepts/cluster-administration/networking/' },
    ],
  },
  {
    id: 'network-pod-to-pod-cross-node',
    title: 'Pod-to-Pod Across Nodes',
    category: 'network',
    subcategory: 'pod-networking',
    desc: 'What happens when the destination Pod lives on a different Node? The local bridge has no port for that Pod, so the CNI takes over the inter-Node hop. An overlay plugin wraps the frame in VXLAN over UDP to the remote Node IP, whose kernel decapsulates it and delivers it through its own bridge, while a routed plugin instead advertises each Node podCIDR so the frame travels unwrapped, trading the MTU overhead for a network that carries Pod routes.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Cluster Networking', href: 'https://kubernetes.io/docs/concepts/cluster-administration/networking/' },
    ],
  },
  {
    id: 'network-pod-egress-snat',
    title: 'Pod Egress to the Internet',
    category: 'network',
    subcategory: 'pod-networking',
    desc: 'A Pod IP is private to the cluster, so how does a Pod reach the internet and get a reply back? As the packet leaves the Node an iptables MASQUERADE rule rewrites its source from the Pod IP to the Node IP, and conntrack records the mapping it made. The server replies to the Node, conntrack reverses the translation, and the reply lands on the Pod, which never learns that its address was rewritten at all. Traffic that stays inside the cluster is left alone.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Cluster Networking', href: 'https://kubernetes.io/docs/concepts/cluster-administration/networking/' },
      { label: 'Virtual IPs and Service Proxies', href: 'https://kubernetes.io/docs/reference/networking/virtual-ips/' },
    ],
  },
  {
    id: 'network-service-types',
    title: 'Service Types and How They Stack',
    category: 'network',
    subcategory: 'services-endpoints',
    desc: 'Kubernetes has four Service types plus a headless variant, so how do they relate? Three of them stack: ClusterIP is the internal base with a virtual IP, NodePort builds on it by opening the same port on every Node, and LoadBalancer builds on NodePort with a cloud address. ExternalName and headless skip the proxy and work through DNS alone. Only the first three ever program anything into kube-proxy, and on bare metal LoadBalancer needs an add-on.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Service', href: 'https://kubernetes.io/docs/concepts/services-networking/service/' },
      { label: 'Publishing Services', href: 'https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types' },
    ],
  },
  {
    id: 'network-service-clusterip',
    title: 'ClusterIP via kube-proxy',
    category: 'network',
    subcategory: 'services-endpoints',
    desc: 'A ClusterIP belongs to no network interface, so what makes traffic to it reach a Pod? The kube-proxy watches the Service and its EndpointSlices and programs the Node dataplane so any packet sent to that address is DNAT-ed to one of the backing Pod IPs. Connection tracking remembers each choice, so a connection sticks to its backend and the reply is rewritten back to the ClusterIP. The client only sees one address.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Service', href: 'https://kubernetes.io/docs/concepts/services-networking/service/' },
      { label: 'Virtual IPs and Service Proxies', href: 'https://kubernetes.io/docs/reference/networking/virtual-ips/' },
    ],
  },
  {
    id: 'network-endpointslice-reconcile',
    title: 'Service and EndpointSlice',
    category: 'network',
    subcategory: 'services-endpoints',
    desc: 'A Service is a stable name for a moving set of Pods, so how does it learn which ones back it now? The EndpointSlice controller watches Pods matching the selector and records each as an IP and port. Readiness gates the serving set, not liveness, so a Pod failing its readiness probe is flagged notReady and excluded with no restart, and kube-proxy reprograms from the slice. Slices exist because Endpoints did not scale: each caps at 100 endpoints by default.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Service', href: 'https://kubernetes.io/docs/concepts/services-networking/service/' },
      { label: 'EndpointSlices', href: 'https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/' },
    ],
  },
  {
    id: 'network-traffic-distribution',
    title: 'Session Affinity and Topology',
    category: 'network',
    subcategory: 'services-endpoints',
    desc: 'How does kube-proxy choose which backend gets a connection, and can you steer it? By default it spreads connections evenly across every ready endpoint and ignores zones. Two fields tune that: sessionAffinity ClientIP pins a client source IP to one Pod for a sticky window that defaults to three hours, and trafficDistribution PreferSameZone favours endpoints in the client zone, falling back cluster-wide when that zone has none ready.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Topology Aware Routing', href: 'https://kubernetes.io/docs/concepts/services-networking/topology-aware-routing/' },
      { label: 'Service Session Affinity', href: 'https://kubernetes.io/docs/reference/networking/virtual-ips/#session-affinity' },
    ],
  },
  {
    id: 'network-internal-traffic-policy',
    title: 'Internal Traffic Cluster vs Local',
    category: 'network',
    subcategory: 'services-endpoints',
    desc: 'What keeps a call from inside the cluster on the Node it started on? The internalTrafficPolicy field is the east-west twin of externalTrafficPolicy, with the same two values. Cluster programs every ready endpoint, so a call can be DNAT-ed across Nodes and pay a hop. Local keeps only endpoints on that Node, which is how a Pod reaches a node-local DaemonSet agent, and it has no fallback, so a Node with no local backend drops the call.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Service Internal Traffic Policy', href: 'https://kubernetes.io/docs/concepts/services-networking/service-traffic-policy/' },
      { label: 'Virtual IPs and Service Proxies', href: 'https://kubernetes.io/docs/reference/networking/virtual-ips/' },
    ],
  },
  {
    id: 'network-service-ports',
    title: 'Service Port Remapping',
    category: 'network',
    subcategory: 'services-endpoints',
    desc: 'A Service has two port numbers that are easy to mix up, so which does what? The port is the stable front door clients dial, while the targetPort is what the container actually listens on, and they need not match because kube-proxy rewrites the destination port as it DNATs, though leaving targetPort out defaults it to the same number as port. The targetPort can even be a name each Pod resolves to its own containerPort.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Service', href: 'https://kubernetes.io/docs/concepts/services-networking/service/' },
      { label: 'Defining a Service', href: 'https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service' },
    ],
  },
  {
    id: 'network-service-terminating-endpoints',
    title: 'Terminating Endpoints and Draining',
    category: 'network',
    subcategory: 'services-endpoints',
    desc: 'When a rolling update deletes a backing Pod, why do requests keep flowing instead of failing? The Pod enters Terminating and its endpoint flips to notReady while serving and terminating stay true, so kube-proxy stops sending new connections but keeps draining the in-flight ones. Only after the grace period does the endpoint leave the slice, so a clean rollout drops nothing. The window is the grace period, no more.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'EndpointSlices', href: 'https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/' },
      { label: 'Termination of Pods', href: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination' },
      { label: 'Virtual IPs and Service Proxies', href: 'https://kubernetes.io/docs/reference/networking/virtual-ips/' },
    ],
  },
  {
    id: 'network-externalname',
    title: 'ExternalName and Services without Selectors',
    category: 'network',
    subcategory: 'services-endpoints',
    desc: 'Most Services proxy to Pods chosen by a selector, so how do the two kinds without one work? A type ExternalName Service has no ClusterIP, CoreDNS returns a CNAME and the client connects there with kube-proxy never involved, which can break HTTP and TLS because the client still dialed the in-cluster name and no certificate matches it. A selectorless ClusterIP Service keeps a virtual IP but gets no automatic endpoints, so you attach an EndpointSlice by hand.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'ExternalName Services', href: 'https://kubernetes.io/docs/concepts/services-networking/service/#externalname' },
      { label: 'Services without selectors', href: 'https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors' },
    ],
  },
  {
    id: 'network-dns-coredns',
    title: 'DNS Resolution via CoreDNS',
    category: 'network',
    subcategory: 'dns-service-discovery',
    desc: 'When a Pod connects to a Service by name, who turns that name into an IP? The Kubelet writes a resolv.conf pointing at the kube-dns ClusterIP, so the query reaches a CoreDNS Pod where the plugin chain checks its cache first and falls through to the kubernetes plugin on a miss. That plugin answers the cluster zone from its own watch of Services and EndpointSlices, never querying the API per lookup, and returns an A record holding the ClusterIP.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'DNS for Services and Pods', href: 'https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/' },
    ],
  },
  {
    id: 'network-dns-records',
    title: 'DNS Records and FQDN',
    category: 'network',
    subcategory: 'dns-service-discovery',
    desc: 'What decides the shape of the DNS answer a cluster gives back? A Service name is really web.default.svc.cluster.local, built from the Service, its namespace, the literal svc and the cluster domain, and that svc segment is what marks it a Service record. The name returns an A record holding the ClusterIP, or one A record per ready Pod when headless, while a named port publishes SRV under a _http._tcp prefix. A Pod answers at 10-244-2-7.default.pod.cluster.local.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'DNS for Services and Pods', href: 'https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/' },
    ],
  },
  {
    id: 'network-dns-ndots',
    title: 'Search Domains and ndots',
    category: 'network',
    subcategory: 'dns-service-discovery',
    desc: 'Why can one name that does not exist cost eight DNS queries? A name with fewer dots than ndots counts as relative, so the resolver appends each search domain in turn and tries the name as written only once the list runs out. A name that exists is answered on the first candidate, one that does not walks all four of them, and since the resolver asks for IPv4 and IPv6 in parallel the miss doubles again. A trailing dot skips the walk.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'DNS for Services and Pods', href: 'https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/' },
      { label: 'Pod DNS Config', href: 'https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config' },
    ],
  },
  {
    id: 'network-nodelocal-dnscache',
    title: 'NodeLocal DNSCache',
    category: 'network',
    subcategory: 'dns-service-discovery',
    desc: 'Why does cluster DNS stall for five seconds under load? Without a local cache every lookup is a UDP packet that kube-proxy DNATs across the cluster to a CoreDNS Pod, adding a conntrack entry per query, and the races on those short flows are what surface as the stalls. NodeLocal DNSCache puts a DaemonSet agent on every Node, so a cached name is answered on the host with no DNAT and only a miss travels upstream.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'NodeLocal DNSCache', href: 'https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/' },
      { label: 'DNS for Services and Pods', href: 'https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/' },
    ],
  },
  {
    id: 'network-headless-service',
    title: 'Headless Service',
    category: 'network',
    subcategory: 'dns-service-discovery',
    desc: 'What does a Service with clusterIP None give you instead of a virtual IP? Nothing is programmed into kube-proxy, so CoreDNS returns one A record per ready Pod and the client opens its connection to a Pod IP directly, with no DNAT anywhere in the path. Nothing balances that traffic either, and each StatefulSet Pod gains a stable name, so web-0.web.default.svc.cluster.local always resolves to that exact replica.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Headless Services', href: 'https://kubernetes.io/docs/concepts/services-networking/service/#headless-services' },
      { label: 'DNS for Services and Pods', href: 'https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/' },
    ],
  },
  {
    id: 'network-north-south-path',
    title: 'North-South Request Path',
    category: 'network',
    subcategory: 'external-traffic',
    desc: 'A request from the public internet does not reach a Pod in one jump, so what is the chain? The client dials the public IP of a cloud load balancer, which forwards to a Node on the Service NodePort, and the kube-proxy there DNATs the packet to a backing Pod IP while conntrack pins the flow. The reply retraces every hop in reverse, so the client sees an answer from the address it dialed. Three hops out, three back.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Publishing Services', href: 'https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types' },
      { label: 'Virtual IPs and Service Proxies', href: 'https://kubernetes.io/docs/reference/networking/virtual-ips/' },
    ],
  },
  {
    id: 'network-nodeport-loadbalancer',
    title: 'NodePort and LoadBalancer',
    category: 'network',
    subcategory: 'external-traffic',
    desc: 'How does traffic from outside the cluster reach a Pod? A NodePort opens the same high port on every Node, so a packet to any Node on that port is DNAT-ed to a backing Pod, and under the default externalTrafficPolicy Cluster that Pod may well be running on another Node. A LoadBalancer builds on top: the cloud-controller-manager provisions an external balancer whose targets are those Node ports, giving clients one stable address in front.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Service', href: 'https://kubernetes.io/docs/concepts/services-networking/service/' },
      { label: 'Virtual IPs and Service Proxies', href: 'https://kubernetes.io/docs/reference/networking/virtual-ips/' },
    ],
  },
  {
    id: 'network-loadbalancer-bare-metal',
    title: 'LoadBalancer without a Cloud',
    category: 'network',
    subcategory: 'external-traffic',
    desc: 'Who provisions the load balancer when there is no cloud? Nobody, so the Service stays pending forever until something in-cluster fills the gap. MetalLB allocates an address from a pool the operator declares and then announces it, either in layer 2 mode where one elected Node answers ARP and takes all inbound traffic, or in BGP mode where every Node advertises it and the router hashes flows. Only BGP spreads the ingress across Nodes.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Service type LoadBalancer', href: 'https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer' },
      { label: 'MetalLB Concepts', href: 'https://metallb.io/concepts/' },
    ],
  },
  {
    id: 'network-externaltrafficpolicy',
    title: 'External Traffic Cluster vs Local',
    category: 'network',
    subcategory: 'external-traffic',
    desc: 'When external traffic lands on a Node, should it spread evenly or keep the client IP? With externalTrafficPolicy Cluster the packet can go to a backend on any Node, which balances load but can add a hop and SNATs the client source IP away. With Local the Node serves only its own Pods, preserving the client IP, at the cost of dropping traffic where no local backend exists. A health check steers the balancer away from Nodes that have no local backend.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'ExternalTrafficPolicy', href: 'https://kubernetes.io/docs/reference/networking/virtual-ips/#external-traffic-policy' },
    ],
  },
  {
    id: 'network-client-ip-preservation',
    title: 'Preserving the Client IP',
    category: 'network',
    subcategory: 'external-traffic',
    desc: 'Why does the backend see the proxy address instead of the real client? An edge proxy opens a connection of its own, so for HTTP it writes the original address into X-Forwarded-For and the standard Forwarded header, which a client can forge, so only the value your own trusted edge wrote may be believed. For raw TCP there is no header, so the PROXY protocol prepends a preamble the backend must expect or it reads it as request bytes.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Preserving the client source IP', href: 'https://kubernetes.io/docs/tutorials/services/source-ip/' },
      { label: 'Forwarded header (RFC 7239)', href: 'https://www.rfc-editor.org/info/rfc7239/' },
    ],
  },
  {
    id: 'network-ingress-routing',
    title: 'Ingress Controller Routing',
    category: 'network',
    subcategory: 'external-traffic',
    desc: 'An Ingress object is only a set of host and path rules, so what actually serves the traffic? An Ingress controller Pod watches the objects that name its ingressClassName and turns them into live proxy configuration, reached through a Service of its own. It matches the request Host and path against the rules, longest match wins, and most controllers proxy straight to a Ready Pod IP from the EndpointSlice. TLS terminates at the controller.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Ingress', href: 'https://kubernetes.io/docs/concepts/services-networking/ingress/' },
      { label: 'Ingress Controllers', href: 'https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/' },
    ],
  },
  {
    id: 'network-tls-termination',
    title: 'TLS Termination at the Edge',
    category: 'network',
    subcategory: 'external-traffic',
    desc: 'Where does HTTPS stop on the way to a Pod? Clients reach the cluster over TLS while backend Pods usually speak plain HTTP, so the Ingress or Gateway presents a certificate from a Kubernetes Secret, completes the handshake, and proxies plain HTTP to a Pod that never sees one. The Ingress API defines only port 443, so re-encrypt to the backend and passthrough are controller extensions or Gateway API modes.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Ingress TLS', href: 'https://kubernetes.io/docs/concepts/services-networking/ingress/#tls' },
      { label: 'Gateway API Project', href: 'https://gateway-api.sigs.k8s.io/' },
    ],
  },
  {
    id: 'network-gateway-api',
    title: 'Gateway API',
    category: 'network',
    subcategory: 'external-traffic',
    desc: 'How does the Gateway API split ingress across the teams that own its parts? A GatewayClass names the controller implementation, a Gateway declares the listeners and belongs to cluster operators, and an HTTPRoute attaches to that Gateway with the host and path rules an application team controls. A listener takes routes from its own namespace until allowedRoutes opens it, so the operator decides who may attach. The role split is why it succeeds Ingress.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Gateway API', href: 'https://kubernetes.io/docs/concepts/services-networking/gateway/' },
      { label: 'Gateway API Project', href: 'https://gateway-api.sigs.k8s.io/' },
    ],
  },
];
