// The network catalogue: every network card and the subcategories they sort into.
// Adding a card means one entry here, one file beside it, one poster, one note.

// SUBCATEGORIES is an editorial order (D-10): what a reader has to know first, never alphabetical.

export const SUBCATEGORIES = [
    { key: 'network-foundations',        label: 'Network Foundations'    },
    { key: 'pod-networking',     label: 'Pod Networking'         },
    { key: 'services-endpoints', label: 'Services & Endpoints'   },
    { key: 'external-traffic',   label: 'External Traffic'       },
    { key: 'dns-service-discovery',                label: 'DNS & Service Discovery' },
];

export const CARDS = [
  {
    id: 'network-flat-pod-network',
    title: 'Flat Pod Network Model',
    category: 'network',
    subcategory: 'network-foundations',
    desc: 'What does Kubernetes promise about the network? The model is one flat address space: every Pod gets a cluster-unique IP, any Pod reaches any other Pod on any Node with no NAT so the real source IP is preserved barring intentional segmentation, and the model promises the Node agent the Pods on its own Node. Only a few parts of this live in the core, the container runtime implements the model, almost always through a CNI plugin like Calico, Cilium or Flannel.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Cluster Networking', href: 'https://kubernetes.io/docs/concepts/cluster-administration/networking/' },
      { label: 'The Kubernetes Network Model', href: 'https://kubernetes.io/docs/concepts/services-networking/#the-kubernetes-network-model' },
    ],
  },
  {
    id: 'network-ipam-pod-cidr',
    title: 'IPAM and Pod CIDR Allocation',
    category: 'network',
    subcategory: 'network-foundations',
    desc: 'How does every Pod in the cluster end up with a unique IP and no clashes? The cluster starts from one large pod CIDR, and the controller-manager, whenever it is started with --allocate-node-cidrs, carves a smaller non-overlapping slice out of it for each Node into node.spec.podCIDR. The CNI IPAM on that Node then hands out addresses only from its own slice, which keeps every Pod IP unique cluster-wide and keeps routing down to a single route per Node.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'kube-controller-manager', href: 'https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/' },
      { label: 'Nodes', href: 'https://kubernetes.io/docs/concepts/architecture/nodes/' },
      { label: 'Cluster Networking', href: 'https://kubernetes.io/docs/concepts/cluster-administration/networking/' },
    ],
  },
  {
    id: 'network-service-cidr',
    title: 'Service CIDR and ClusterIP Allocation',
    category: 'network',
    subcategory: 'network-foundations',
    desc: 'Where does a Service ClusterIP come from when nobody assigns it? One ServiceCIDR object declares the range, and the allocator in the API server reads it as two bands: it draws from the dynamic band and falls back to the static one only when that runs out, so kube-dns on 10.96.0.10 is not reserved, only unlikely to be taken. The allocation is a write, an IPAddress object named after the address, and a second ServiceCIDR grows the range with nothing restarted.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Service ClusterIP Allocation', href: 'https://kubernetes.io/docs/concepts/services-networking/cluster-ip-allocation/' },
      { label: 'Extend Service IP Ranges', href: 'https://kubernetes.io/docs/tasks/network/extend-service-ip-ranges/' },
      { label: 'Service', href: 'https://kubernetes.io/docs/concepts/services-networking/service/' },
      { label: 'Multiple ServiceCIDRs KEP', href: 'https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/1880-multiple-service-cidrs' },
    ],
  },
  {
    id: 'network-dualstack',
    title: 'Dual-Stack IPv4 and IPv6',
    category: 'network',
    subcategory: 'network-foundations',
    desc: 'What changes when a cluster runs IPv4 and IPv6 side by side? The CNI gives every Pod one address per family on the same eth0, and a Service set to ipFamilyPolicy PreferDualStack gets one ClusterIP per family, ordered by ipFamilies. Where only one family exists, PreferDualStack falls back to a single ClusterIP while RequireDualStack fails the Service outright. A client resolves both A and AAAA records and connects over whichever family it prefers.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'IPv4/IPv6 Dual-Stack', href: 'https://kubernetes.io/docs/concepts/services-networking/dual-stack/' },
      { label: 'DNS for Services and Pods', href: 'https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/' },
      { label: 'EndpointSlices', href: 'https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/' },
    ],
  },
  {
    id: 'network-namespaces',
    title: 'Network Namespaces',
    category: 'network',
    subcategory: 'network-foundations',
    desc: 'What makes a Pod IP feel like a separate machine? A network namespace is a private copy of the Linux network stack, with its own interfaces, routing table, iptables rules and port space, invisible to every other Pod. The pause container opens one and holds it for the life of the Pod, unless hostNetwork is set, and one veth pair is normally the only door out of it. A deleted Pod takes the namespace with it, so nothing of that stack outlives it on the Node.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Pod networking', href: 'https://kubernetes.io/docs/concepts/workloads/pods/#pod-networking' },
      { label: 'Linux network namespaces', href: 'https://man7.org/linux/man-pages/man7/network_namespaces.7.html' },
      { label: 'CRI Spec', href: 'https://github.com/kubernetes/cri-api/blob/master/pkg/apis/runtime/v1/api.proto' },
      { label: 'CNI Specification', href: 'https://github.com/containernetworking/cni/blob/main/SPEC.md' },
    ],
  },
  {
    id: 'network-kube-proxy-modes',
    title: 'kube-proxy: iptables vs IPVS',
    category: 'network',
    subcategory: 'network-foundations',
    desc: 'How does kube-proxy pick a backend, and why does the mode matter at scale? In iptables mode a packet to a ClusterIP walks KUBE-SERVICES into a per-Service chain that picks an endpoint by probability, then a per-endpoint chain DNATs it to the Pod. IPVS mode makes the same choice with an in-kernel hash table, trading the rule walk for constant-time lookup, though v1.35 deprecates it in favour of nftables. Either mode turns the ClusterIP into one chosen backend.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Virtual IPs and Service Proxies', href: 'https://kubernetes.io/docs/reference/networking/virtual-ips/' },
      { label: 'kube-proxy iptables proxier', href: 'https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/iptables/proxier.go' },
    ],
  },
  {
    id: 'network-proxy-rule-resync',
    title: 'Rule Resync and minSyncPeriod',
    category: 'network',
    subcategory: 'network-foundations',
    desc: 'How long after a Pod dies do the rules sending traffic to it disappear? Every Node runs a kube-proxy unless you replaced it, and it watches Services and EndpointSlices, not Pods, batching changes behind minSyncPeriod instead of rewriting the kernel per event, so deleting a 100-Pod Deployment costs about five updates, not a hundred. Staleness is the price, because one change can wait a full minSyncPeriod, while syncPeriod drives the cleanup no single change triggers.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Optimizing iptables mode performance', href: 'https://kubernetes.io/docs/reference/networking/virtual-ips/#optimizing-iptables-mode-performance' },
      { label: 'kube-proxy Configuration (v1alpha1)', href: 'https://kubernetes.io/docs/reference/config-api/kube-proxy-config.v1alpha1/' },
    ],
  },
  {
    id: 'network-conntrack-nat',
    title: 'Connection Tracking and NAT',
    category: 'network',
    subcategory: 'network-foundations',
    desc: 'A connection is more than one packet, so how does NAT remember the backend it picked? The first packet matches no entry and walks the NAT rules, and conntrack stores it as one entry with an original and a reply tuple. Every later packet is translated straight off that entry, no rule read, and the reply is what flips it to ESTABLISHED. That is why a flow sticks to one backend while the entry lives, and why a busy Node can exhaust its conntrack table.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Virtual IPs and Service Proxies', href: 'https://kubernetes.io/docs/reference/networking/virtual-ips/' },
      { label: 'kube-proxy', href: 'https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/' },
    ],
  },
  {
    id: 'network-netfilter-path',
    title: 'The Netfilter Path a Packet Takes',
    category: 'network',
    subcategory: 'network-foundations',
    desc: 'Why must the DNAT that kube-proxy programs run before routing? A packet enters at PREROUTING, where conntrack records the flow and the nat table rewrites the Service address to a backend Pod, and only then does routing run, on the rewritten address. That decision is a fork: an address the Node owns goes to INPUT, everything else to FORWARD and POSTROUTING, where MASQUERADE waits. The reply is untangled by conntrack, walking no Service rule.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Virtual IPs and Service Proxies', href: 'https://kubernetes.io/docs/reference/networking/virtual-ips/' },
      { label: 'Cluster Networking', href: 'https://kubernetes.io/docs/concepts/cluster-administration/networking/' },
      { label: 'netfilter packet flow', href: 'https://wiki.nftables.org/wiki-nftables/index.php/Netfilter_hooks' },
      { label: 'netfilter NAT HOWTO', href: 'https://www.netfilter.org/documentation/HOWTO/NAT-HOWTO.txt' },
    ],
  },
  {
    id: 'network-ebpf-dataplane',
    title: 'eBPF Dataplane',
    category: 'network',
    subcategory: 'network-foundations',
    desc: 'How does the modern dataplane route Services without iptables? The CNI agent attaches eBPF programs to kernel hooks and keeps Service and endpoint state in BPF maps. A connection to a ClusterIP is then looked up and rewritten to a backend right at the socket: connect-time load balancing instead of per-packet DNAT, with constant-time lookups that let kube-proxy and its iptables chains be removed entirely. The rewrite lands before the first packet is built.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Virtual IPs and Service Proxies', href: 'https://kubernetes.io/docs/reference/networking/virtual-ips/' },
      { label: 'Kubernetes Without kube-proxy', href: 'https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/' },
      { label: 'eBPF', href: 'https://ebpf.io/what-is-ebpf/' },
    ],
  },
  {
    id: 'network-packet-classification',
    title: 'Packet Classification by Destination',
    category: 'network',
    subcategory: 'network-foundations',
    desc: 'A Pod sends to one address, so which machinery picks the packet up? The destination decides, because two stations stand between the Pod and the wire in a fixed order. The nat table owns the Service range and rewrites a Service address to a backend Pod address, then the route lookup sorts what it is handed into the Pod range, routed to the Node owning that slice, or into no cluster range at all, taken by the default route and masqueraded to the Node IP.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Cluster Networking', href: 'https://kubernetes.io/docs/concepts/cluster-administration/networking/' },
      { label: 'Virtual IPs and Service Proxies', href: 'https://kubernetes.io/docs/reference/networking/virtual-ips/' },
      { label: 'IP Masquerade Agent User Guide', href: 'https://kubernetes.io/docs/tasks/administer-cluster/ip-masq-agent/' },
    ],
  },
  {
    id: 'network-policy',
    title: 'How a NetworkPolicy Blocks a Pod',
    category: 'network',
    subcategory: 'network-foundations',
    desc: 'Every Pod can reach every Pod, so how do you stop one? A NetworkPolicy that selects a Pod for a direction raises a boundary on that Pod in that direction, and from then on everything it does not explicitly allow is dropped there. A connection has to clear a boundary at each end, the egress of the sender and the ingress of the receiver, and the network plugin is what raises them, so a policy nothing implements raises nothing.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Network Policies', href: 'https://kubernetes.io/docs/concepts/services-networking/network-policies/' },
      { label: 'NetworkPolicy API reference', href: 'https://kubernetes.io/docs/reference/kubernetes-api/networking/network-policy-v1/' },
    ],
  },
  {
    id: 'network-containers-share-localhost',
    title: 'Containers Share Localhost',
    category: 'network',
    subcategory: 'pod-networking',
    desc: 'Why can an app and its sidecar reach each other over 127.0.0.1 with no network in between? Every container in a Pod joins the same network namespace, so they stand on the same loopback and the same eth0 and bind their ports in a single shared space. A loopback call never leaves the Pod, a bind of a pair another container holds comes back as address already in use, and from outside the Pod is one host whose container on that port answers.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Pod networking', href: 'https://kubernetes.io/docs/concepts/workloads/pods/#pod-networking' },
      { label: 'Share Process Namespace', href: 'https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/' },
    ],
  },
  {
    id: 'network-hostnetwork-hostport',
    title: 'hostNetwork and hostPort',
    category: 'network',
    subcategory: 'pod-networking',
    desc: 'What are the two fields that put a Pod on the Node address itself? With hostNetwork true the Pod gets no network namespace of its own, no veth and no Pod IP, and binds the Node interfaces directly, which is how kube-proxy and a CNI agent run. A hostPort gives up far less: the Pod keeps its namespace, its IP and its veth, and the portmap plugin only adds a port mapping. Both spend a Node port, so the Scheduler fits only one such replica per Node.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Pod networking', href: 'https://kubernetes.io/docs/concepts/workloads/pods/#pod-networking' },
      { label: 'Do not use hostPort or hostNetwork lightly', href: 'https://kubernetes.io/blog/2025/11/25/configuration-good-practices/#avoid-hostport-and-hostnetwork-unless-absolutely-necessary' },
      { label: 'CNI portmap plugin', href: 'https://www.cni.dev/plugins/current/meta/portmap/' },
    ],
  },
  {
    id: 'network-wiring-pod-via-cni',
    title: 'Wiring a Pod via CNI',
    category: 'network',
    subcategory: 'pod-networking',
    desc: 'Who actually runs the CNI plugins, and in what order? The Kubelet asks the CRI runtime for a Pod sandbox, then the runtime, not the Kubelet, reads the plugin list from /etc/cni/net.d and runs each as an executable, handing every one after the first the previous result as prevResult. The bridge plugin delegates addressing to its own host-local IPAM plugin, the last plugin prints one result of interfaces, addresses, routes and DNS, and DEL runs the list in reverse.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'CNI Specification', href: 'https://github.com/containernetworking/cni/blob/main/SPEC.md' },
      { label: 'Network Plugins', href: 'https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/' },
      { label: 'CNI Plugins Reference', href: 'https://www.cni.dev/plugins/current/' },
    ],
  },
  {
    id: 'network-pod-ip-and-veth',
    title: 'Pod IP and the veth Pair',
    category: 'network',
    subcategory: 'pod-networking',
    desc: 'What is a veth pair, and where does a Pod IP actually live? A veth pair is one virtual link with two ends, and in a Pod they stand in two different network namespaces: eth0 inside the Pod, and its peer in the Node root namespace, enslaved to the cni0 bridge and carrying no address of its own. The address sits on the Pod end because a namespace is what holds an address, which is why one pair and one IP are allocated per Pod and never per container.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Pod networking', href: 'https://kubernetes.io/docs/concepts/workloads/pods/#pod-networking' },
      { label: 'CNI Specification', href: 'https://github.com/containernetworking/cni/blob/main/SPEC.md' },
      { label: 'CNI bridge plugin', href: 'https://www.cni.dev/plugins/current/main/bridge/' },
    ],
  },
  {
    id: 'network-pod-to-pod-same-node',
    title: 'Pod-to-Pod on the Same Node',
    category: 'network',
    subcategory: 'pod-networking',
    desc: 'How does a packet get from one Pod to another when both run on the same Node? Both draw from the Node podCIDR, so the destination is on-link and the source needs no gateway: ARP resolves the peer MAC through the cni0 bridge, which records the port that answer came in on. The data frame then crosses a veth pair and is switched out that one port at layer 2, with no NAT and no encapsulation anywhere, so the real source IP arrives intact.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Kubernetes network model', href: 'https://kubernetes.io/docs/concepts/services-networking/' },
      { label: 'CNI bridge plugin', href: 'https://www.cni.dev/plugins/current/main/bridge/' },
      { label: 'Pod networking', href: 'https://kubernetes.io/docs/concepts/workloads/pods/#pod-networking' },
    ],
  },
  {
    id: 'network-pod-to-pod-cross-node',
    title: 'Pod-to-Pod Across Nodes',
    category: 'network',
    subcategory: 'pod-networking',
    desc: 'What happens when the destination Pod lives on a different Node? That address is off-subnet, so the route hands the frame to the CNI dataplane. An overlay plugin such as flannel wraps the frame in VXLAN over UDP to the remote Node IP, where the kernel decapsulates it and delivers it through its own bridge, while a routed plugin advertises the Pod subnet of each Node so the frame travels unwrapped, trading the MTU overhead for a network that carries Pod routes.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Kubernetes network model', href: 'https://kubernetes.io/docs/concepts/services-networking/' },
      { label: 'CNI bridge plugin', href: 'https://www.cni.dev/plugins/current/main/bridge/' },
      { label: 'flannel backends', href: 'https://github.com/flannel-io/flannel/blob/master/Documentation/backends.md' },
      { label: 'Calico overlay networking', href: 'https://docs.tigera.io/calico/latest/networking/configuring/vxlan-ipip' },
    ],
  },
  {
    id: 'network-mtu-overhead',
    title: 'MTU Overhead and PMTU Blackholes',
    category: 'network',
    subcategory: 'pod-networking',
    desc: 'Why does ping keep answering while a large transfer hangs on the same path? A VXLAN outer header spends 50 of the 1500 bytes a link carries, so the CNI sets the Pod eth0 to 1450 and the wrapped frame fits the Node NIC exactly. When one tunnel hop further along the path carries less and the ICMP that would report it is filtered, nothing on the Node ever learns, so small packets keep crossing while large ones disappear.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Calico MTU configuration', href: 'https://docs.tigera.io/calico/latest/networking/configuring/mtu' },
      { label: 'RFC 1191 Path MTU Discovery', href: 'https://datatracker.ietf.org/doc/html/rfc1191' },
      { label: 'RFC 2923 TCP problems with Path MTU Discovery', href: 'https://datatracker.ietf.org/doc/html/rfc2923' },
      { label: 'RFC 4459 MTU and fragmentation issues', href: 'https://datatracker.ietf.org/doc/html/rfc4459' },
    ],
  },
  {
    id: 'network-pod-egress-snat',
    title: 'Pod Egress and SNAT',
    category: 'network',
    subcategory: 'pod-networking',
    desc: 'No route on the internet leads back to a Pod IP, so how does a Pod reach the internet and get a reply? On the way out the Node walks its POSTROUTING rules, which exempt anything addressed inside the cluster and masquerade the rest, rewriting the source to the Node IP and storing the flow in conntrack. The reply comes back to that Node IP and walks no masquerade rule: the stored entry reverses the translation, so the Pod never learns its address changed.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Preserving the client source IP', href: 'https://kubernetes.io/docs/tutorials/services/source-ip/' },
      { label: 'IP Masquerade Agent User Guide', href: 'https://kubernetes.io/docs/tasks/administer-cluster/ip-masq-agent/' },
      { label: 'Kubernetes network model', href: 'https://kubernetes.io/docs/concepts/services-networking/' },
    ],
  },
  {
    id: 'network-service-types',
    title: 'ClusterIP, NodePort, LoadBalancer and the Rest',
    category: 'network',
    subcategory: 'services-endpoints',
    desc: 'Kubernetes has four Service types plus a headless variant, so how do they relate? Three of them stack: ClusterIP is the internal base with a virtual IP, NodePort builds on it by opening the same port on every Node, and LoadBalancer usually builds on NodePort with a balancer from a cloud or an add-on. ExternalName and headless Services get no virtual IP and no Service rules: DNS answers with a CNAME or the Pod IPs, and the client connects by itself.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Service', href: 'https://kubernetes.io/docs/concepts/services-networking/service/' },
      { label: 'Virtual IPs and Service Proxies', href: 'https://kubernetes.io/docs/reference/networking/virtual-ips/' },
      { label: 'DNS for Services and Pods', href: 'https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#namespaces-of-services' },
      { label: 'ServiceSpec', href: 'https://kubernetes.io/docs/reference/kubernetes-api/core/service-v1/#ServiceSpec' },
    ],
  },
  {
    id: 'network-service-clusterip',
    title: 'ClusterIP via kube-proxy',
    category: 'network',
    subcategory: 'services-endpoints',
    desc: 'No Pod owns a ClusterIP and no single host answers for it, so how does traffic to it reach a Pod? The kube-proxy on each Node watches the Service and its EndpointSlices and writes Service rules into the Node dataplane, and those rules, not kube-proxy, DNAT a packet sent to that address to one backing Pod. Connection tracking pins each connection to its backend and rewrites the reply back to the ClusterIP, so the client sees one address.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Service', href: 'https://kubernetes.io/docs/concepts/services-networking/service/' },
      { label: 'Virtual IPs and Service Proxies', href: 'https://kubernetes.io/docs/reference/networking/virtual-ips/' },
    ],
  },
  {
    id: 'network-service-debugging',
    title: 'Debugging Service Traffic',
    category: 'network',
    subcategory: 'services-endpoints',
    desc: 'A Service exists and its name resolves, so why does the app behind it never get the call? Three links must hold: the selector matches the Pod labels, a matching Pod is Ready (unless publishNotReadyAddresses is set) so the EndpointSlice serves it, and targetPort is the port the container listens on. Break either of the first two and no endpoint is serving, while a wrong targetPort lands where nothing listens. A named targetPort follows the port the Pod declares.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Debug Services', href: 'https://kubernetes.io/docs/tasks/debug/debug-application/debug-service/' },
      { label: 'Service', href: 'https://kubernetes.io/docs/concepts/services-networking/service/' },
      { label: 'EndpointSlices', href: 'https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/' },
    ],
  },
  {
    id: 'network-service-and-endpointslice',
    title: 'Service and EndpointSlice',
    category: 'network',
    subcategory: 'services-endpoints',
    desc: 'A Service is a stable name for a moving set of Pods, so what decides which of them take traffic now? The EndpointSlice controller watches the Pods matching the selector and records each Pod IP as one endpoint with its conditions, in slices of up to 100 endpoints by default. When a failing readiness probe turns a Pod Ready=False, its endpoint becomes ready=false with no container restart, and kube-proxy writes Service rules for the ready endpoints.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Service', href: 'https://kubernetes.io/docs/concepts/services-networking/service/' },
      { label: 'EndpointSlices', href: 'https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/' },
    ],
  },
  {
    id: 'network-service-terminating-endpoints',
    title: 'Terminating Endpoints and Draining',
    category: 'network',
    subcategory: 'services-endpoints',
    desc: 'When a rolling update deletes a backing Pod, why do requests keep flowing instead of failing? Here the replacement is Ready first, and on deletion the old endpoint turns ready=false and terminating=true, so kube-proxy rewrites the Service rules to send new connections to the ready Pods. A preStop sleep gives that rewrite time to land before SIGTERM, established TCP flows finish on their conntrack entries, and the Pod exits inside its grace period.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'EndpointSlices', href: 'https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/' },
      { label: 'Termination of Pods', href: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination' },
      { label: 'Virtual IPs and Service Proxies', href: 'https://kubernetes.io/docs/reference/networking/virtual-ips/' },
      { label: 'Max Unavailable', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#max-unavailable' },
    ],
  },
  {
    id: 'network-traffic-distribution',
    title: 'Session Affinity and Traffic Distribution',
    category: 'network',
    subcategory: 'services-endpoints',
    desc: 'Which backend does a Service connection reach, and can you steer it? By default kube-proxy writes every ready endpoint into the rules and the dataplane picks one per connection, ignoring zones. Two fields change that: sessionAffinity ClientIP pins a client IP to one Pod while that Pod stays in the rules and the client reconnects within 10800s by default, and trafficDistribution PreferSameZone keeps only same-zone endpoints, or all ready ones if that zone has none.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Traffic Distribution Control', href: 'https://kubernetes.io/docs/reference/networking/virtual-ips/#traffic-distribution' },
      { label: 'Service Session Affinity', href: 'https://kubernetes.io/docs/reference/networking/virtual-ips/#session-affinity' },
    ],
  },
  {
    id: 'network-internal-traffic-policy',
    title: 'Internal Traffic Cluster vs Local',
    category: 'network',
    subcategory: 'services-endpoints',
    desc: 'What keeps a call from inside the cluster on the Node it started on? With internalTrafficPolicy Cluster, kube-proxy on each Node writes every ready endpoint into its rules, so a call can be DNAT-ed to another Node. With Local it writes only the endpoints on its own Node, which lets a Pod reach its node-local DaemonSet agent, and it never falls back to another Node, so in iptables mode a Node with no local endpoint left drops the call.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Service Internal Traffic Policy', href: 'https://kubernetes.io/docs/concepts/services-networking/service-traffic-policy/' },
      { label: 'Virtual IPs and Service Proxies', href: 'https://kubernetes.io/docs/reference/networking/virtual-ips/#internal-traffic-policy' },
    ],
  },
  {
    id: 'network-externalname',
    title: 'ExternalName and Services without Selectors',
    category: 'network',
    subcategory: 'services-endpoints',
    desc: 'Most Services front Pods picked by a selector, so how do the two kinds without one reach outside? An ExternalName Service has no ClusterIP: CoreDNS answers with a CNAME and the client connects by itself, while TLS SNI and HTTP Host still carry the in-cluster name the server may not recognize. A selectorless Service keeps its virtual IP, and a hand-written EndpointSlice labelled kubernetes.io/service-name lists the address kube-proxy writes rules for.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'ExternalName Services', href: 'https://kubernetes.io/docs/concepts/services-networking/service/#externalname' },
      { label: 'Services without selectors', href: 'https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors' },
    ],
  },
  {
    id: 'network-nodeport-loadbalancer',
    title: 'NodePort and LoadBalancer',
    category: 'network',
    subcategory: 'external-traffic',
    desc: 'How does traffic from outside the cluster reach a Pod? A NodePort opens the same port on every Node, so a client can dial any Node directly, even one with no backend, which by default DNATs the connection and forwards it across the cluster network to a Pod on another Node. A LoadBalancer puts one address in front: the cloud-controller-manager provisions an external balancer that typically forwards to that Node port, and the chosen Node DNATs to a Pod.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Service', href: 'https://kubernetes.io/docs/concepts/services-networking/service/' },
      { label: 'Virtual IPs and Service Proxies', href: 'https://kubernetes.io/docs/reference/networking/virtual-ips/' },
    ],
  },
  {
    id: 'network-external-traffic-policy',
    title: 'External Traffic Cluster vs Local',
    category: 'network',
    subcategory: 'external-traffic',
    desc: 'When external traffic lands on a Node, may that Node hand it to a Pod on another Node? With externalTrafficPolicy Cluster it may, so load spreads over every ready Pod, but SNAT replaces the client source IP even when the Node serves it itself. With Local a Node serves only its own Pods and keeps the client IP, drops traffic where it has none until a health check steers the balancer away, and an unweighted balancer splits load per Node, not per Pod.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'ExternalTrafficPolicy', href: 'https://kubernetes.io/docs/reference/networking/virtual-ips/#external-traffic-policy' },
      { label: 'Preserving the client source IP', href: 'https://kubernetes.io/docs/tutorials/services/source-ip/' },
      { label: 'Caveats of preserving source IPs', href: 'https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#caveats-and-limitations-when-preserving-source-ips' },
    ],
  },
  {
    id: 'network-loadbalancer-without-cloud',
    title: 'LoadBalancer without a Cloud',
    category: 'network',
    subcategory: 'external-traffic',
    desc: 'Who gives a LoadBalancer Service its address when there is no cloud? MetalLB does it in-cluster: its controller allocates an address from a pool the operator declares, and its speakers then have to announce it to the router before any client traffic can arrive. In layer 2 mode one Node answers ARP and a gratuitous ARP moves the address when it fails, while in BGP mode every Node advertises it and the router spreads connections by ECMP.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Service type LoadBalancer', href: 'https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer' },
      { label: 'MetalLB Concepts', href: 'https://metallb.io/concepts/' },
      { label: 'MetalLB in layer 2 mode', href: 'https://metallb.io/concepts/layer2/' },
      { label: 'MetalLB in BGP mode', href: 'https://metallb.io/concepts/bgp/' },
    ],
  },
  {
    id: 'network-loadbalancer-straight-to-pods',
    title: 'LoadBalancer Straight to Pods',
    category: 'network',
    subcategory: 'external-traffic',
    desc: 'How does a load balancer send traffic straight to Pods instead of through Node ports? A balancer implementation that targets Pods reads the Service endpoints, here an EndpointSlice, and registers each Pod IP and port, so a connection needs no second Node hop or Node SNAT, and a replaced Pod is registered at its new address. Setting allocateLoadBalancerNodePorts false then allocates no new Node port unless one is requested, and frees none already allocated.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Disabling load balancer NodePort allocation', href: 'https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-nodeport-allocation' },
      { label: 'EndpointSlices', href: 'https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/' },
      { label: 'ServiceSpec allocateLoadBalancerNodePorts', href: 'https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/#ServiceSpec' },
    ],
  },
  {
    id: 'network-ingress-routing',
    title: 'Ingress Controller Routing',
    category: 'network',
    subcategory: 'external-traffic',
    desc: 'An Ingress on its own does nothing, so what actually serves the traffic? A controller Pod watches the Ingresses of its IngressClass, compiles their rules into proxy config and is usually reached through a Service of its own. It terminates TLS, matches Host and path, longest path wins, and commonly proxies straight to a Ready Pod IP from the EndpointSlice. The Ingress API stays GA but is frozen, and the Kubernetes project recommends Gateway instead.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Ingress', href: 'https://kubernetes.io/docs/concepts/services-networking/ingress/' },
      { label: 'Ingress Controllers', href: 'https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/' },
      { label: 'Ingress-NGINX Service Upstream', href: 'https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#service-upstream' },
    ],
  },
  {
    id: 'network-gateway-api',
    title: 'Gateway API',
    category: 'network',
    subcategory: 'external-traffic',
    desc: 'How does Gateway API decide whether a route may use a shared entry point? A GatewayClass names the implementation, a Gateway in the operator namespace admits routes only from its own namespace by default, and an HTTPRoute from another namespace is not Accepted until a listener allowedRoutes admits its namespace. A backendRef into a third namespace also needs a ReferenceGrant there, and until then a rule with no filters and only that backend returns HTTP 500.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Gateway API', href: 'https://kubernetes.io/docs/concepts/services-networking/gateway/' },
      { label: 'HTTPRoute', href: 'https://gateway-api.sigs.k8s.io/reference/api-types/httproute/' },
      { label: 'ReferenceGrant', href: 'https://gateway-api.sigs.k8s.io/reference/api-types/referencegrant/' },
      { label: 'HTTPBackendRef', href: 'https://gateway-api.sigs.k8s.io/reference/api-spec/1.6/spec/#httpbackendref' },
    ],
  },
  {
    id: 'network-gateway-traffic-splitting',
    title: 'Traffic Splitting with HTTPRoute',
    category: 'network',
    subcategory: 'external-traffic',
    desc: 'How does a Gateway send a tenth of traffic to a new version? An HTTPRoute rule lists several backendRefs with weights, and each Service gets its weight divided by the sum of the weights whatever its Pod count, while a rule matching a test header can send only tagged requests there first. A backendRef that does not resolve keeps its share, which must get HTTP 500, and a weight of 0 on the old version completes the cutover.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'HTTP traffic splitting', href: 'https://gateway-api.sigs.k8s.io/guides/user-guides/traffic-splitting/' },
      { label: 'HTTPRoute', href: 'https://gateway-api.sigs.k8s.io/reference/api-types/httproute/' },
      { label: 'HTTPBackendRef', href: 'https://gateway-api.sigs.k8s.io/reference/api-spec/1.6/spec/#httpbackendref' },
      { label: 'Gateway API', href: 'https://kubernetes.io/docs/concepts/services-networking/gateway/' },
    ],
  },
  {
    id: 'network-client-ip-preservation',
    title: 'Preserving the Client IP',
    category: 'network',
    subcategory: 'external-traffic',
    desc: 'Why does the backend see the proxy address instead of the real client? An edge proxy ends the connection the client opened and starts one of its own, so the socket names the proxy and the original address survives only if something writes it down. For HTTP that is X-Forwarded-For, which the client can also send, so the header becomes a list to be trusted from its last entry inwards, and for raw TCP the PROXY protocol prepends a preamble the backend must expect.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Preserving the client source IP', href: 'https://kubernetes.io/docs/tutorials/services/source-ip/' },
      { label: 'X-Forwarded-For', href: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/X-Forwarded-For' },
      { label: 'Forwarded header (RFC 7239)', href: 'https://www.rfc-editor.org/info/rfc7239/' },
      { label: 'The PROXY protocol', href: 'https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt' },
    ],
  },
  {
    id: 'network-dns-coredns',
    title: 'DNS Resolution via CoreDNS',
    category: 'network',
    subcategory: 'dns-service-discovery',
    desc: 'When a Pod connects to a Service by name, who turns that name into an IP? The Kubelet configures a resolv.conf pointing at the kube-dns ClusterIP, so the query reaches a CoreDNS Pod where the plugin chain checks its cache first and falls through to the kubernetes plugin on a miss. That plugin answers the cluster zone from its own watch of Services and EndpointSlices, never querying the API per lookup, and returns an A record holding the ClusterIP.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'DNS for Services and Pods', href: 'https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/' },
      { label: 'CoreDNS plugins and the chain order', href: 'https://coredns.io/manual/plugins/' },
      { label: 'CoreDNS kubernetes plugin', href: 'https://coredns.io/plugins/kubernetes/' },
      { label: 'CoreDNS cache plugin', href: 'https://coredns.io/plugins/cache/' },
    ],
  },
  {
    id: 'network-dns-records',
    title: 'DNS Records and FQDN',
    category: 'network',
    subcategory: 'dns-service-discovery',
    desc: 'What decides the shape of the DNS answer a cluster gives back? A Service name is really web.default.svc.cluster.local, built from the Service, its namespace, the literal svc that marks a Service record, and the cluster domain. It returns an A record holding the ClusterIP, or one A record per ready Pod when headless, while a named port publishes SRV under a _http._tcp prefix. With pods enabled in CoreDNS, a Pod is reachable at 10-244-2-7.default.pod.cluster.local.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'DNS for Services and Pods', href: 'https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/' },
      { label: 'CoreDNS kubernetes plugin', href: 'https://coredns.io/plugins/kubernetes/' },
      { label: 'Customizing DNS Service', href: 'https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/' },
    ],
  },
  {
    id: 'network-dns-pod-policy',
    title: 'Pod DNS Policy and dnsConfig',
    category: 'network',
    subcategory: 'dns-service-discovery',
    desc: 'Where does the resolv.conf inside a Pod come from? The Kubelet configures it from its own clusterDNS settings, the resolver file its resolvConf setting names and the Pod spec, and dnsPolicy picks the source: ClusterFirst when unset, Default for the Node file, None for dnsConfig alone. A hostNetwork Pod left on ClusterFirst silently gets the Node file, and dnsConfig merges on top, appending nameservers up to three and overriding options by name.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Pod DNS policy and Pod DNS Config', href: 'https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy' },
      { label: 'Kubelet Configuration', href: 'https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/' },
      { label: 'Debugging DNS Resolution, known issues', href: 'https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/#known-issues' },
    ],
  },
  {
    id: 'network-dns-ndots',
    title: 'Search Domains and ndots',
    category: 'network',
    subcategory: 'dns-service-discovery',
    desc: 'Why can one lookup of an external name like api.example.com cost eight DNS queries from a Pod? With ndots:5 any name with fewer than five dots and no trailing dot is relative, so the resolver tries it with every search domain before trying it as written, and asks for A and AAAA each time. A Service in the same namespace answers on the first candidate, one in another namespace on the second, and a trailing dot skips the search list.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'DNS for Services and Pods', href: 'https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/' },
      { label: 'Pod DNS Config', href: 'https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config' },
    ],
  },
  {
    id: 'network-dns-egress-policy',
    title: 'DNS and a Default Deny Egress Policy',
    category: 'network',
    subcategory: 'dns-service-discovery',
    desc: 'Why does a Pod stop resolving names the moment it gets an egress policy? Once a NetworkPolicy selects a Pod for Egress, the Pod may open only the connections an egress rule allows, and a lookup to the cluster DNS Service is not one of them until a rule says so, so name resolution fails while the addresses the policy allows still connect. The rule that repairs it selects the DNS Pods by namespace and Pod labels, and it lists port 53 for both UDP and TCP.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Network Policies', href: 'https://kubernetes.io/docs/concepts/services-networking/network-policies/' },
      { label: 'NetworkPolicy API reference', href: 'https://kubernetes.io/docs/reference/kubernetes-api/networking/network-policy-v1/' },
      { label: 'DNS for Services and Pods', href: 'https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/' },
      { label: 'Debugging DNS Resolution', href: 'https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/' },
    ],
  },
  {
    id: 'network-nodelocal-dnscache',
    title: 'NodeLocal DNSCache',
    category: 'network',
    subcategory: 'dns-service-discovery',
    desc: 'Why does cluster DNS stall under load, and what does a cache on every Node change? Without one, each lookup from a ClusterFirst Pod is a UDP query that kube-proxy DNATs to a CoreDNS Pod, often on another Node, with a conntrack entry per lookup. In iptables mode NodeLocal DNSCache answers that ClusterIP on the Node with no DNAT or conntrack, sends cluster misses to CoreDNS over TCP and other names to the Node resolvers, and caches answers for up to 30 seconds.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'NodeLocal DNSCache', href: 'https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/' },
      { label: 'DNS for Services and Pods', href: 'https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/' },
      { label: 'nodelocaldns.yaml', href: 'https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/nodelocaldns/nodelocaldns.yaml' },
    ],
  },
  {
    id: 'network-dns-autoscaling',
    title: 'DNS Horizontal Autoscaling',
    category: 'network',
    subcategory: 'dns-service-discovery',
    desc: 'How does a cluster end up running the right number of CoreDNS replicas? When enabled, a separate kube-dns-autoscaler Deployment polls the API server for Node and core counts and takes its parameters from a ConfigMap, so nothing here watches CPU the way a HorizontalPodAutoscaler does. Linear mode divides each count by its per-replica figure, rounds up, keeps the larger, clamps it and writes it to the CoreDNS scale subresource. Ladder mode uses step tables instead.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Autoscale the DNS Service in a Cluster', href: 'https://kubernetes.io/docs/tasks/administer-cluster/dns-horizontal-autoscaling/' },
      { label: 'cluster-proportional-autoscaler', href: 'https://github.com/kubernetes-sigs/cluster-proportional-autoscaler' },
      { label: 'DNS for Services and Pods', href: 'https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/' },
    ],
  },
  {
    id: 'network-headless-service',
    title: 'Headless Service',
    category: 'network',
    subcategory: 'dns-service-discovery',
    desc: 'What does a Service with clusterIP None give you instead of a virtual IP? It gets no kube-proxy rules and no load balancing from the platform. A lookup of the Service name returns one A record per ready Pod, and the client connects to a Pod IP it picks itself. Under a StatefulSet each Pod also gets its own name, such as web-0.nginx.default.svc.cluster.local, which follows that replica even when it comes back with a new IP.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Headless Services', href: 'https://kubernetes.io/docs/concepts/services-networking/service/#headless-services' },
      { label: 'DNS for Services and Pods', href: 'https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/' },
      { label: 'StatefulSet stable network ID', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-network-id' },
    ],
  },
];
