// The cluster catalogue: every cluster card and the subcategories they sort into.
// Adding a card means one entry here, one file beside it, one poster, one note.

// Design notes: scheme/INTERNALS.md#schemejsdatajs

export const SUBCATEGORIES = [
    { key: 'control-plane',  label: 'Control Plane'  },
    { key: 'node-runtime',   label: 'Node Runtime'   },
    { key: 'node-lifecycle', label: 'Node Lifecycle' },
];

export const CARDS = [
  {
    id: 'cluster-architecture',
    title: 'Cluster Architecture',
    category: 'cluster',
    subcategory: 'control-plane',
    desc: 'What are the moving parts of a Kubernetes cluster, and how do they talk to each other? One contract runs under all of it: desired state lives in ETCD behind the API, the single front door, and the controllers and scheduler compare it against observed state and loop until the gap closes. A Kubelet on every worker Node reconciles the same way and brings Pods to life, so nothing outside the control plane reaches ETCD, and kube-proxy programs Service rules beside it.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Components', href: 'https://kubernetes.io/docs/concepts/overview/components/' },
      { label: 'Architecture', href: 'https://kubernetes.io/docs/concepts/architecture/' },
    ],
  },
  {
    id: 'cluster-apply-flow',
    title: 'Object Create Path',
    category: 'cluster',
    subcategory: 'control-plane',
    desc: 'What actually happens between kubectl apply and a running Pod? The manifest travels to the API and lands in ETCD, and then a chain of watchers takes over: the Deployment controller creates a ReplicaSet, the ReplicaSet controller creates a Pod, the Scheduler assigns that Pod a Node, and the Kubelet there starts the container. Every handoff after the write is one component reacting to a change on its own watch rather than a call from the component before it.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Architecture', href: 'https://kubernetes.io/docs/concepts/architecture/' },
      { label: 'Controllers', href: 'https://kubernetes.io/docs/concepts/architecture/controller/' },
    ],
  },
  {
    id: 'cluster-admission-webhooks',
    title: 'Admission Chain',
    category: 'cluster',
    subcategory: 'control-plane',
    desc: 'Before any object reaches storage, what gets a say in whether it is allowed and how it looks? Each request runs a gauntlet inside the API: authenticated, authorized, optionally rewritten, checked against the schema, and validated one last time before the write commits. The mutating and validating steps are where Kyverno, OPA Gatekeeper or a sidecar injector plugs in. A slow webhook stalls every write it matches, and failurePolicy decides whether it then fails.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Admission Controllers', href: 'https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/' },
      { label: 'Dynamic Admission Control', href: 'https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/' },
    ],
  },
  {
    id: 'cluster-resource-quota',
    title: 'ResourceQuota and LimitRange',
    category: 'cluster',
    subcategory: 'control-plane',
    desc: 'The Deployment is one replica short and kubectl get pods has nothing to show for it, so where did that Pod go? A ResourceQuota caps what a single namespace may request in total and is checked at admission, so the Pod is refused before it exists and the 403 lands on the ReplicaSet that asked for it, as a FailedCreate event and a ReplicaFailure condition. A LimitRange is the other half, because it supplies the request a quota demands from every Pod that names none.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Resource Quotas', href: 'https://kubernetes.io/docs/concepts/policy/resource-quotas/' },
      { label: 'Limit Ranges', href: 'https://kubernetes.io/docs/concepts/policy/limit-range/' },
      { label: 'Admission Controllers', href: 'https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/' },
    ],
  },
  {
    id: 'cluster-server-side-apply',
    title: 'Server-side Apply and Field Ownership',
    category: 'cluster',
    subcategory: 'control-plane',
    desc: 'Two controllers write the same Deployment, so who wins and how does the API even know? Server-side apply records a field manager for every field an actor sets, keeping that ledger in managedFields on the object, and an apply that stops sending a field it used to own is what removes that field. A second manager setting the same field to a different value raises a conflict the API refuses until it is forced, which is what replaces the client-side three-way merge.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Server-Side Apply', href: 'https://kubernetes.io/docs/reference/using-api/server-side-apply/' },
      { label: 'API Concepts', href: 'https://kubernetes.io/docs/reference/using-api/api-concepts/' },
      { label: 'Declarative Object Management', href: 'https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/' },
    ],
  },
  {
    id: 'cluster-api-structure',
    title: 'List-Watch and Informers',
    category: 'cluster',
    subcategory: 'control-plane',
    desc: 'How does a controller keep an up-to-date picture of the cluster without hammering the API? It lists the objects it cares about once, then opens a watch that streams every later change to them. An informer turns that stream into a local cache, so the controller reconciles against memory and only re-lists when its watch has fallen too far behind to catch up, which the API signals with a 410 Gone. Every controller is built on that one list-watch pattern.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'API Concepts', href: 'https://kubernetes.io/docs/reference/using-api/api-concepts/' },
      { label: 'Kubernetes API', href: 'https://kubernetes.io/docs/concepts/overview/kubernetes-api/' },
    ],
  },
  {
    id: 'cluster-scheduler-decision',
    title: 'Scheduler Decision Cycle',
    category: 'cluster',
    subcategory: 'control-plane',
    desc: 'A new Pod has no Node yet, so how does Kubernetes decide where it runs? The scheduler pulls the Pod off its queue, filters out the Nodes that cannot fit it, scores the survivors to find the best home, and writes that choice back as a binding object. From there the Kubelet on the chosen Node picks the Pod up on its own watch and starts the containers. That one write is the whole of its placement decision, and the scheduler itself never starts anything.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Kube-scheduler', href: 'https://kubernetes.io/docs/concepts/scheduling-eviction/kube-scheduler/' },
      { label: 'Scheduling Framework', href: 'https://kubernetes.io/docs/concepts/scheduling-eviction/scheduling-framework/' },
    ],
  },
  {
    id: 'cluster-pod-priority-preemption',
    title: 'Pod Priority and Preemption',
    category: 'cluster',
    subcategory: 'control-plane',
    desc: 'What happens when an important Pod has nowhere to fit on a full cluster? Its PriorityClass resolves to a numeric priority, and when every Node fails on capacity the scheduler preempts, unless that class sets preemptionPolicy Never. It picks the smallest set of lower-priority Pods whose removal makes room and deletes them with a plain DELETE, bypassing the PodDisruptionBudgets normal eviction respects. The Pod is then bound in their place.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Priority and Preemption', href: 'https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/' },
      { label: 'PriorityClass', href: 'https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.35/#priorityclass-v1-scheduling-k8s-io' },
    ],
  },
  {
    id: 'cluster-delete-flow',
    title: 'Cascading Deletion and Finalizers',
    category: 'cluster',
    subcategory: 'control-plane',
    desc: 'You run kubectl delete and the prompt returns at once, so why is the object still there? By default the API drops the owner at once and the Garbage collector walks ownerReferences to clean up the dependents afterwards. Ask for foreground cascade instead and the object is only stamped for deletion until the dependents that carry blockOwnerDeletion are gone and the finalizers clear. A finalizer that never clears is how an object sticks.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Garbage Collection', href: 'https://kubernetes.io/docs/concepts/architecture/garbage-collection/' },
      { label: 'Owners and Dependents', href: 'https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/' },
      { label: 'Finalizers', href: 'https://kubernetes.io/docs/concepts/overview/working-with-objects/finalizers/' },
    ],
  },
  {
    id: 'cluster-etcd-raft',
    title: 'ETCD Raft Consensus',
    category: 'cluster',
    subcategory: 'control-plane',
    desc: 'How does Kubernetes keep its single source of truth safe when a machine can fail? ETCD runs a small group of replicas that agree on every write through the Raft protocol: one Leader takes the change, copies it to the Followers, and commits only once a majority has stored it. That quorum rule is what lets a cluster of three lose a Node and still never serve a half-written state. Lose the majority and it stops writing until quorum returns.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Raft Algorithm', href: 'https://raft.github.io/' },
      { label: 'Raft Paper', href: 'https://raft.github.io/raft.pdf' },
      { label: 'Operating etcd clusters for Kubernetes', href: 'https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/' },
    ],
  },
  {
    id: 'cluster-leader-election',
    title: 'Leader Election via Lease',
    category: 'cluster',
    subcategory: 'control-plane',
    desc: 'When you run several copies of a controller for high availability, how do they avoid all acting at once? They race to claim a single Lease object, and only the winner runs the control loops while the rest stand by and poll it. The holder keeps renewing the Lease to prove it is alive, and once renewals stop for a full lease duration a standby takes it over, so leadership moves after a crash on its own. The Lease records the holder and counts every handover.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Leases', href: 'https://kubernetes.io/docs/concepts/architecture/leases/' },
      { label: 'Lease v1', href: 'https://kubernetes.io/docs/reference/kubernetes-api/coordination/lease-v1/' },
    ],
  },
  {
    id: 'cluster-kubelet-sync-loop',
    title: 'Kubelet Reconcile Loop',
    category: 'cluster',
    subcategory: 'node-runtime',
    desc: 'How does the Kubelet turn a Pod spec into running containers, and keep them that way? It runs a sync loop that compares the Pod specs it takes from its sources, mainly the API, against what the container runtime reports is actually running on this Node. Whenever the two differ it issues the runtime calls needed to converge, then reports the fresh status back to the API. PLEG is what wakes that loop when a container dies on its own.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Kubelet', href: 'https://kubernetes.io/docs/concepts/overview/components/#node-components' },
      { label: 'Kubelet PLEG', href: 'https://developers.redhat.com/blog/2019/11/13/pod-lifecycle-event-generator-understanding-the-pleg-is-not-healthy-issue-in-kubernetes' },
    ],
  },
  {
    id: 'cluster-pod-sandbox-cri',
    title: 'Pod Sandbox via CRI',
    category: 'cluster',
    subcategory: 'node-runtime',
    desc: 'What does the container runtime actually do when the Kubelet asks it to start a Pod? It first builds a sandbox, a tiny pause container that holds open the network and the other shared namespaces, and then has the CNI plugin wire up the Pod IP. Only once the images are pulled does it create and start each workload container inside that sandbox, so every container in the Pod shares one network identity that outlives any container restarting inside it.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'CRI Spec', href: 'https://github.com/kubernetes/cri-api/blob/master/pkg/apis/runtime/v1/api.proto' },
      { label: 'Container Runtimes', href: 'https://kubernetes.io/docs/setup/production-environment/container-runtimes/' },
    ],
  },
  {
    id: 'cluster-static-pods',
    title: 'Static Pods and Mirror Pods',
    category: 'cluster',
    subcategory: 'node-runtime',
    desc: 'If the API server runs as a Pod, who starts it before the API server exists? The Kubelet watches a manifest directory on the Node and runs whatever it finds there directly, with no Scheduler and no controller involved, which is how kubeadm brings the control plane up on a fresh machine. For each one it also creates a read-only mirror Pod in the API so kubectl can see it, and deleting that mirror changes nothing because the file on disk stays the source of truth.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Static Pods', href: 'https://kubernetes.io/docs/concepts/workloads/pods/static-pods/' },
      { label: 'Create static Pods', href: 'https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/' },
    ],
  },
  {
    id: 'cluster-node-allocatable',
    title: 'Node Allocatable',
    category: 'cluster',
    subcategory: 'node-runtime',
    desc: 'Your Node reports 16Gi of memory, so why does the Scheduler refuse a 15Gi Pod? Capacity is what the machine has, and Allocatable is what survives after kube-reserved, system-reserved and the hard eviction threshold are carved out of it, which is the only number the Scheduler ever sums Pod requests against. Everything above Allocatable belongs to the Kubelet, the runtime and the OS, so a Node that looks half empty can still be full.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Reserve Compute Resources', href: 'https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/' },
      { label: 'Node Status', href: 'https://kubernetes.io/docs/concepts/architecture/nodes/#node-status' },
      { label: 'Resource Management', href: 'https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/' },
    ],
  },
  {
    id: 'cluster-cpu-throttling',
    title: 'CPU Throttling and CFS Quota',
    category: 'cluster',
    subcategory: 'node-runtime',
    desc: 'A container over its memory limit is killed, so why is one over its CPU limit still alive? A CPU limit becomes a CFS quota, a budget of run time the cgroup may spend inside every 100ms period, and once it is spent the kernel stops scheduling those threads until the next period opens. Nothing dies and nothing is recorded as an error, the latency just grows, which is why throttling shows up in container_cpu_cfs_throttled_seconds_total and not in kubectl describe.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Resource Management', href: 'https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/' },
      { label: 'cgroup v2', href: 'https://kubernetes.io/docs/concepts/architecture/cgroups/' },
    ],
  },
  {
    id: 'cluster-oom-kill',
    title: 'Container OOMKill',
    category: 'cluster',
    subcategory: 'node-runtime',
    desc: 'A container blows past its memory limit, so what kills it and what gets recorded? The limit is enforced by the kernel cgroup, and once usage reaches the cap and reclaim cannot free enough, the cgroup out-of-memory killer SIGKILLs every process in that container at once, and it exits 137. The Kubelet only witnesses this. It records the OOMKilled reason in the container status, then restarts the container according to the Pod restart policy.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Resource Management', href: 'https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/' },
      { label: 'Pod QoS Classes', href: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-qos/' },
    ],
  },
  {
    id: 'cluster-node-pressure-eviction',
    title: 'Node-pressure Eviction',
    category: 'cluster',
    subcategory: 'node-lifecycle',
    desc: 'When a Node starts running low on memory or disk, who decides which Pods to sacrifice? The Kubelet watches local usage and, once a signal crosses its configured threshold, ranks the Pods by whether they exceed their requests, then by Priority, then by how far each has overrun, and evicts the cheapest first. It keeps going until the signal drops back under the threshold. QoS class only approximates that order, and no PodDisruptionBudget applies here.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Node-pressure Eviction', href: 'https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/' },
      { label: 'Pod QoS Classes', href: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-qos/' },
    ],
  },
  {
    id: 'cluster-node-drain',
    title: 'Node Drain',
    category: 'cluster',
    subcategory: 'node-lifecycle',
    desc: 'How do you take a Node out of service without dropping your apps? The drain command first cordons the Node so nothing new lands on it, then evicts the running Pods through the Eviction API rather than deleting them outright. A PodDisruptionBudget can hold an eviction back with a 429 until a replacement is Ready elsewhere. A drain never evicts DaemonSet Pods at all, and kubectl refuses to start one while any are present unless you pass --ignore-daemonsets.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Safely Drain a Node', href: 'https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/' },
      { label: 'Eviction API', href: 'https://kubernetes.io/docs/concepts/scheduling-eviction/api-eviction/' },
      { label: 'PodDisruptionBudget', href: 'https://kubernetes.io/docs/concepts/workloads/pods/disruptions/' },
    ],
  },
  {
    id: 'cluster-graceful-node-shutdown',
    title: 'Graceful Node Shutdown',
    category: 'cluster',
    subcategory: 'node-lifecycle',
    desc: 'When a Node is told to power off, can its Pods still shut down cleanly first? With graceful Node shutdown enabled, the Kubelet catches the shutdown signal from systemd and holds an inhibitor lock that delays the power-off while it terminates Pods in priority order, giving ordinary workloads one grace window and the critical ones a second window of their own. Only then does it release the lock and let the operating system finish powering down.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Graceful Node Shutdown', href: 'https://kubernetes.io/docs/concepts/cluster-administration/node-shutdown/' },
      { label: 'KEP-2000: Graceful Node Shutdown', href: 'https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2000-graceful-node-shutdown' },
    ],
  },
  {
    id: 'cluster-node-failure',
    title: 'Node Failure and Eviction',
    category: 'cluster',
    subcategory: 'node-lifecycle',
    desc: 'A Node goes silent, so how long until its Pods come back elsewhere? The cluster notices when the heartbeat Lease stops renewing, flips the Node to an unknown state, and taints it so that the Pods are eventually evicted and rescheduled somewhere healthy. The grace period plus the default toleration mean recovery takes a few minutes by design, trading raw speed for not overreacting to a network blip.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Node Status', href: 'https://kubernetes.io/docs/concepts/architecture/nodes/#node-status' },
      { label: 'Node Taints', href: 'https://kubernetes.io/docs/reference/labels-annotations-taints/#node-kubernetes-io-unreachable' },
      { label: 'Taint-Based Evictions', href: 'https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-based-evictions' },
    ],
  },
];
