// The workloads catalogue: every workloads card and the subcategories they sort into.
// Adding a card means one entry here, one file beside it, one poster, one note.

// The SUBCATEGORIES list below is an ORDER, not a set: the sequence is an editorial argument
// about what a reader has to know first, never alphabetical and never a merge artefact.

export const SUBCATEGORIES = [
    { key: 'pods-bootstrap', label: 'Pods Bootstrap' },
    { key: 'pods-lifecycle', label: 'Pods Lifecycle' },
    { key: 'controllers',   label: 'Controllers'    },
];

export const CARDS = [
  {
    id: 'workloads-controller-kinds',
    title: 'Workload Controller Kinds',
    category: 'workloads',
    subcategory: 'controllers',
    desc: 'Six built-in kinds manage Pods for you, so which one does a workload want? Three questions separate them: whether a replica needs a stable identity, which is the StatefulSet, whether the count follows the matching Node set rather than a number you set, which is the DaemonSet, and whether the work ends, which is the Job. A Deployment reaches its Pods through a ReplicaSet and a CronJob through a Job, and Deployment replaces the legacy ReplicationController.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Workload Management', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/' },
      { label: 'ReplicationController', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/replicationcontroller/' },
    ],
  },
  {
    id: 'workloads-replicaset',
    title: 'ReplicaSet Reconcile and Ownership',
    category: 'workloads',
    subcategory: 'controllers',
    desc: 'How does Kubernetes keep exactly the right number of identical Pods alive? A ReplicaSet runs a control loop comparing how many Pods it should have against how many it can see, then creates or deletes until the two match. It owns them through ownerReferences, adopts any matching Pod that no other controller already owns, and releases one whose labels stop matching. Deployments never manage Pods directly, they manage ReplicaSets.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'ReplicaSet', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/' },
      { label: 'Owners and Dependents', href: 'https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/' },
    ],
  },
  {
    id: 'workloads-rolling-update',
    title: 'Deployment Rolling Update',
    category: 'workloads',
    subcategory: 'controllers',
    desc: 'How do you move every Pod to a new version without taking the app offline? A Deployment rolls the change out gradually, bringing up new-version Pods within its surge budget and retiring old ones as replacements report Ready, so the Service stays backed. The maxSurge and maxUnavailable dials both default to 25%, which at 3 replicas rounds up to a surge of 1 and down to 0 unavailable, and only at maxUnavailable 0 does an old Pod stay until its replacement serves.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Rolling Update Deployment', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#rolling-update-deployment' },
    ],
  },
  {
    id: 'workloads-deployment-strategy',
    title: 'RollingUpdate or Recreate',
    category: 'workloads',
    subcategory: 'controllers',
    desc: 'Should a Deployment replace its Pods alongside the old ones or after them? The field .spec.strategy.type takes two values, and RollingUpdate, the default, surges to create the replacement and wait for it to report Ready before the old Pod is removed, so the two are briefly alive together. Recreate inverts that order, terminating every old Pod before the replacement is created, which buys one version running at a time and pays with a window where nothing serves.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Deployment Strategy', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy' },
      { label: 'Recreate Deployment', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#recreate-deployment' },
    ],
  },
  {
    id: 'workloads-deployment-rollback',
    title: 'Deployment Rollback and Revision History',
    category: 'workloads',
    subcategory: 'controllers',
    desc: 'A rollout went bad, so how do you get back to what worked? A revision is not a snapshot the Deployment stores, it is a ReplicaSet with a revision annotation, kept at zero once it is old, so a rollback copies that template back and the matching ReplicaSet is scaled up and renumbered forward rather than a fifth being created. A pruned ReplicaSet takes its revision with it, so revisionHistoryLimit, 2 on this Deployment and 10 by default, caps how far back you can go.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Rolling Back a Deployment', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#rolling-back-a-deployment' },
      { label: 'Clean up Policy', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#clean-up-policy' },
    ],
  },
  {
    id: 'workloads-statefulset-ordered-rollout',
    title: 'StatefulSet Ordered Rollout',
    category: 'workloads',
    subcategory: 'controllers',
    desc: 'Why does a StatefulSet start its Pods strictly one at a time? Under the default podManagementPolicy of OrderedReady, ordinal 0 has to be Running and Ready before ordinal 1 is even created, which is what lets a clustered system elect a primary before any follower appears. Each Pod also keeps a stable name and its own claim across restarts, and under that same policy a scale-down reverses the order, highest ordinal first, so ordinal 0 is the last to go.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'OrderedReady Pod Management', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#orderedready-pod-management' },
      { label: 'PVC Retention Policy', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#persistentvolumeclaim-retention' },
    ],
  },
  {
    id: 'workloads-statefulset-update-strategy',
    title: 'StatefulSet Update Strategy',
    category: 'workloads',
    subcategory: 'controllers',
    desc: 'How does a change to the Pod template reach a StatefulSet that is already running? RollingUpdate deletes and recreates the Pods one at a time from the largest ordinal down, waiting for each to be Running and Ready before it touches the predecessor. A partition freezes every ordinal below it so you can stage a canary, maxUnavailable widens the window past the default of one, and OnDelete hands the trigger back to you.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Update Strategies', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#update-strategies' },
      { label: 'Partitioned Rolling Updates', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#partitions' },
    ],
  },
  {
    id: 'workloads-pod-pending-init-states',
    title: 'Pod Pending and Init States',
    category: 'workloads',
    subcategory: 'pods-bootstrap',
    desc: 'A Pod is not Running yet, so which component is still holding it? The STATUS column answers exactly that: Pending means no Node has been chosen and the Scheduler owns it, an Init:N/M counter or Init:CrashLoopBackOff means the Kubelet is working through the init containers, and PodInitializing means those are done and the app containers are being created. READY stays 0/1 through all of them, because that column asks a different question.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Debug Init Containers', href: 'https://kubernetes.io/docs/tasks/debug/debug-application/debug-init-containers/' },
      { label: 'Init Containers', href: 'https://kubernetes.io/docs/concepts/workloads/pods/init-containers/' },
      { label: 'Pod phase', href: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase' },
    ],
  },

  {
    id: 'workloads-pod-scheduling-gates',
    title: 'Pod Scheduling Gates',
    category: 'workloads',
    subcategory: 'pods-bootstrap',
    desc: 'Why has the Scheduler not even looked at a Pod created a minute ago? Because spec.schedulingGates holds it out of the scheduling queue entirely: kubectl prints STATUS SchedulingGated, the PodScheduled condition is False with reason SchedulingGated, and scheduler_pending_pods counts it under queue gated rather than unschedulable. Entries come off in any order and none can be added after creation, so the Pod is queued only once the list is empty.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Pod Scheduling Readiness', href: 'https://kubernetes.io/docs/concepts/scheduling-eviction/pod-scheduling-readiness/' },
      { label: 'Pod Conditions', href: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-conditions' },
      { label: 'Pod v1', href: 'https://kubernetes.io/docs/reference/kubernetes-api/core/pod-v1/' },
      { label: 'Scheduling Readiness KEP', href: 'https://github.com/kubernetes/enhancements/tree/master/keps/sig-scheduling/3521-pod-scheduling-readiness' },
    ],
  },

  {
    id: 'workloads-pod-startup-conditions',
    title: 'Pod Startup Conditions',
    category: 'workloads',
    subcategory: 'pods-bootstrap',
    desc: 'When a Pod is not Ready, which of its conditions are still False? Five conditions climb in roughly this order, PodScheduled then PodReadyToStartContainers then Initialized then ContainersReady then Ready, and each one is written by a different act, while status.phase moves once on that whole climb. The Kubelet begins pulling images only after the second condition flips, and Ready can lag ContainersReady whenever a readinessGate has not agreed.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Pod Conditions', href: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-condition/' },
      { label: 'Pod Lifecycle', href: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/' },
      { label: 'Feature Gates', href: 'https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/' },
      { label: 'EndpointSlices', href: 'https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/' },
    ],
  },
  {
    id: 'workloads-image-pull-registry-auth',
    title: 'Image Pull and Registry Auth',
    category: 'workloads',
    subcategory: 'pods-bootstrap',
    desc: 'How does the Kubelet get a container image onto the Node before the container can run? It reads imagePullPolicy, which when you leave it unset defaults to Always for :latest or an untagged image and to IfNotPresent for any other tag or a digest, finds credentials through imagePullSecrets, and pulls only the layers the Node does not already hold by sha256 digest. A failed pull surfaces as ErrImagePull and retries on an exponential ImagePullBackOff.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Images', href: 'https://kubernetes.io/docs/concepts/containers/images/' },
      { label: 'ImagePullSecrets', href: 'https://kubernetes.io/docs/concepts/configuration/secret/#using-imagepullsecrets' },
      { label: 'CRI Spec', href: 'https://github.com/kubernetes/cri-api/blob/master/pkg/apis/runtime/v1/api.proto' },
      { label: 'OCI Distribution Spec', href: 'https://github.com/opencontainers/distribution-spec' },
    ],
  },
  {
    id: 'workloads-init-containers-and-sidecars',
    title: 'Init Containers and Native Sidecars',
    category: 'workloads',
    subcategory: 'pods-bootstrap',
    desc: 'How does a Pod start its containers when some of them must run before others? Regular init containers run strictly in order, each exiting 0 before the next begins, and a native sidecar (an initContainer with restartPolicy=Always, GA in 1.33) starts after them and runs for the whole Pod lifetime. The main container is held back until that sidecar reports Started, and on shutdown the termination order reverses. The sidecar still counts in the init list.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Sidecar Containers', href: 'https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/' },
      { label: 'Init Containers', href: 'https://kubernetes.io/docs/concepts/workloads/pods/init-containers/' },
      { label: 'Pod Lifecycle', href: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/' },
      { label: 'CRI Spec', href: 'https://github.com/kubernetes/cri-api/blob/master/pkg/apis/runtime/v1/api.proto' },
    ],
  },
  {
    id: 'workloads-env-before-pid-1',
    title: 'Environment Before PID 1',
    category: 'workloads',
    subcategory: 'pods-bootstrap',
    desc: 'How does a value from a ConfigMap reach the container before its process starts? At launch the Kubelet resolves env, envFrom and the downward API into one set of variables and hands it over in the CreateContainer call, adding a pair for every Service that exists at that instant unless enableServiceLinks is false. That set is a copy taken once, so a later edit moves the object and never the running process, and only a restarted container reads the new value.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'ConfigMaps', href: 'https://kubernetes.io/docs/concepts/configuration/configmap/' },
      { label: 'Container Environment', href: 'https://kubernetes.io/docs/concepts/containers/container-environment/' },
      { label: 'Service', href: 'https://kubernetes.io/docs/concepts/services-networking/service/' },
      { label: 'Downward API', href: 'https://kubernetes.io/docs/concepts/workloads/pods/downward-api/' },
    ],
  },
  {
    id: 'workloads-effective-pod-requests',
    title: 'Effective Pod Resource Requests',
    category: 'workloads',
    subcategory: 'pods-bootstrap',
    desc: 'Four containers ask for cpu, so how much does the Scheduler reserve? Not their sum: regular init containers run one at a time so the tallest counts, plus any sidecar declared before it, while the app and the sidecar run together so theirs are added, and the Pod takes the higher of those two plus any RuntimeClass overhead. The Scheduler bins on it and the Kubelet sizes the Pod cgroup from it, so a short init container holds its share for the whole Pod life.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Sidecar Containers', href: 'https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/' },
      { label: 'Init Containers', href: 'https://kubernetes.io/docs/concepts/workloads/pods/init-containers/' },
      { label: 'Pod Overhead', href: 'https://kubernetes.io/docs/concepts/scheduling-eviction/pod-overhead/' },
    ],
  },
  {
    id: 'workloads-pod-qos-classes',
    title: 'Pod QoS Classes',
    category: 'workloads',
    subcategory: 'pods-bootstrap',
    desc: 'When a Node runs low on memory, which Pods does Kubernetes sacrifice first? At admission it reads each Pod resources block and assigns a QoS class: Guaranteed when every container sets both CPU and memory with requests equal to limits, BestEffort when neither is set at all, Burstable in between. The class is fixed for the life of the Pod and drives the cgroup caps and the oom_score_adj, but not the eviction order, which goes by whether a Pod is over its request.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Pod QoS Classes', href: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-qos/' },
      { label: 'Resource Management', href: 'https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/' },
      { label: 'Node-pressure Eviction', href: 'https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/' },
    ],
  },
  {
    id: 'workloads-daemonset',
    title: 'DaemonSet Controller',
    category: 'workloads',
    subcategory: 'controllers',
    desc: 'How does a DaemonSet decide how many Pods to run, when there is no replicas field to set? With no nodeSelector or affinity it runs one Pod on every eligible Node, and with a selector it matches each Node against it, so desiredNumberScheduled is computed from the cluster, not declared by you. Labelling a Node adds a Pod, removing the Node takes its Pod and nothing is rescheduled, and updateStrategy picks RollingUpdate with maxUnavailable or OnDelete.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'DaemonSet', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/' },
      { label: 'Perform a Rolling Update on a DaemonSet', href: 'https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/' },
    ],
  },
  {
    id: 'workloads-job-parallelism',
    title: 'Job Parallelism and Completions',
    category: 'workloads',
    subcategory: 'controllers',
    desc: 'How does a Job run a batch of work to completion instead of serving forever? You give it completions, the number of successful runs you need, and parallelism, how many Pods may run at once, and it keeps launching Pods and retrying failures until that target is met. Once enough runs succeed it stops on its own and marks the batch complete. A failed Pod counts against backoffLimit, 6 by default, and exceeding that limit fails the Job instead.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Parallel execution for Jobs', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/job/#parallel-jobs' },
      { label: 'Job v1', href: 'https://kubernetes.io/docs/reference/kubernetes-api/batch/job-v1/' },
    ],
  },
  {
    id: 'workloads-finished-job-cleanup',
    title: 'Automatic Cleanup for Finished Jobs',
    category: 'workloads',
    subcategory: 'controllers',
    desc: 'Who deletes a Job once it has finished? A Complete or Failed Job and its Pods stay in the API so the run is still inspectable, and .spec.ttlSecondsAfterFinished starts a clock when the Job finishes rather than when it was created. Once that many seconds pass the ttl-after-finished controller deletes the Job cascadingly, so the Pods go with it, while an unset field means this controller never touches the Job and 0 makes it eligible the moment it finishes.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Automatic Cleanup for Finished Jobs', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/' },
      { label: 'TTL mechanism for finished Jobs', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/job/#ttl-mechanism-for-finished-jobs' },
      { label: 'kube-controller-manager', href: 'https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/' },
    ],
  },
  {
    id: 'workloads-cronjob',
    title: 'CronJob Schedule and Concurrency',
    category: 'workloads',
    subcategory: 'controllers',
    desc: 'How do you run a Job on a repeating schedule instead of on demand? A CronJob holds a cron expression and, each time the clock matches, creates a Job from its template, which runs a Pod. It also decides what happens when a run is still going at the next tick, prunes finished Jobs, and starts a run missed while it was down, bounded both by startingDeadlineSeconds and by a ceiling of 100 missed ticks. A CronJob never runs a Pod itself, it only creates Jobs.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'CronJob', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/' },
      { label: 'Running Automated Tasks with a CronJob', href: 'https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/' },
    ],
  },
  {
    id: 'workloads-pod-replacement-guarantees',
    title: 'Pod Replacement Guarantees',
    category: 'workloads',
    subcategory: 'controllers',
    desc: 'What actually comes back when a Pod that a controller owns disappears? A ReplicaSet and a Job both create a replacement with a new name, the ReplicaSet at once and the Job after a back-off delay that also counts against backoffLimit. A StatefulSet returns the identical ordinal with the claim it already had, a DaemonSet a fresh name on the Node it lost one on, and a CronJob nothing at all, because it owns Jobs rather than Pods.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'PVC Retention Policy', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#persistentvolumeclaim-retention' },
      { label: 'Handling Pod and Container Failures', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/job/#handling-pod-and-container-failures' },
      { label: 'DaemonSet', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/' },
      { label: 'CronJob', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/' },
    ],
  },
  {
    id: 'workloads-pod-lifecycle-phases',
    title: 'Pod Lifecycle Phases',
    category: 'workloads',
    subcategory: 'pods-lifecycle',
    desc: 'What single field tells you where a Pod is in its life? The status.phase field moves through Pending while the Pod is placed and its images pulled, Running once every container exists and one has started, and then Succeeded or Failed once they have all exited and none will be restarted. It is deliberately coarse, so a container crash-looping inside a Running Pod never changes it. Phase is a summary of placement, not a statement about health.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Pod phase', href: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase' },
      { label: 'PodStatus', href: 'https://kubernetes.io/docs/reference/kubernetes-api/core/pod-v1/#PodStatus' },
    ],
  },
  {
    id: 'workloads-pod-restart-policy',
    title: 'Pod Restart Policy',
    category: 'workloads',
    subcategory: 'pods-lifecycle',
    desc: 'When a container in a Pod exits, what should happen next? The restartPolicy field is the Pod-level default a container can override: Always brings the container back whatever the exit code, OnFailure retries only a non-zero exit, and Never leaves it alone. It separates a Pod that runs forever from one that retries and one that finishes. The Job controller relies on OnFailure and Never for exactly this, and the shared backoff only starts after the first restart.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Restart Policy', href: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy' },
    ],
  },
  {
    id: 'workloads-crashloopbackoff',
    title: 'CrashLoopBackOff and Restart Backoff',
    category: 'workloads',
    subcategory: 'pods-lifecycle',
    desc: 'Why does a broken container restart slower and slower? The Kubelet backs off exponentially, doubling the wait from 10s up to a 5 minute ceiling, so a crashing process cannot hot-loop and saturate the Node. During each wait the container reports Waiting with reason CrashLoopBackOff while the Pod phase stays Running, and a clean 10 minutes resets the backoff, so a new crash counts as a first one, restarted at once. CrashLoopBackOff is a symptom, never the cause.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Restart Policy', href: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy' },
    ],
  },
  {
    id: 'workloads-container-states',
    title: 'Container Restarts and lastState',
    category: 'workloads',
    subcategory: 'pods-lifecycle',
    desc: 'A container crashed and restarted, so what killed it? The live state shows only the fresh Running instance, but Kubernetes keeps the previous termination beside it: lastState holds the exit code and reason, restartCount counts how often it has happened, and kubectl logs --previous reads the log stream of the instance that died. Together they are the whole post-mortem for a container you can no longer see, and only the last termination is kept.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Container States', href: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-states' },
      { label: 'Determine the Reason for Pod Failure', href: 'https://kubernetes.io/docs/tasks/debug/debug-application/determine-reason-pod-failure/' },
      { label: 'Pod v1', href: 'https://kubernetes.io/docs/reference/kubernetes-api/core/pod-v1/' },
      { label: 'Garbage Collection', href: 'https://kubernetes.io/docs/concepts/architecture/garbage-collection/' },
    ],
  },
  {
    id: 'workloads-ephemeral-containers',
    title: 'Ephemeral Debug Containers',
    category: 'workloads',
    subcategory: 'pods-lifecycle',
    desc: 'A container is running but its image is distroless, so how do you get a look inside without replacing the Pod? An ephemeral container is added to the live Pod through the ephemeralcontainers subresource, the only writer of that list, and it arrives with no ports, no probes and no resources, and is never restarted. The kubectl debug command builds it, targetContainerName runs it in the namespaces of the container you name, and it can never be removed.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Ephemeral Containers', href: 'https://kubernetes.io/docs/concepts/workloads/pods/ephemeral-containers/' },
      { label: 'Debug Running Pods', href: 'https://kubernetes.io/docs/tasks/debug/debug-application/debug-running-pod/' },
      { label: 'Pod v1', href: 'https://kubernetes.io/docs/reference/kubernetes-api/core/pod-v1/' },
      { label: 'Share Process Namespace', href: 'https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/' },
    ],
  },
  {
    id: 'workloads-probes',
    title: 'Startup, Liveness and Readiness Probes',
    category: 'workloads',
    subcategory: 'pods-lifecycle',
    desc: 'How does the Kubelet tell a slow boot from a hung container? Three probes answer that on their own periodSeconds: startupProbe gates the other two until the app is up, livenessProbe restarts the container per restartPolicy after failureThreshold consecutive failures, and readinessProbe flips the Pod endpoint to ready=false in the EndpointSlice without removing it or restarting anything. A probe never restarts a Pod, only the container that failed it.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Configure Liveness, Readiness and Startup Probes', href: 'https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/' },
      { label: 'Pod Lifecycle: Pod readiness', href: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-readiness-gate' },
    ],
  },
  {
    id: 'workloads-pod-resize',
    title: 'In-place Pod Resize',
    category: 'workloads',
    subcategory: 'pods-lifecycle',
    desc: 'A running Pod is short on CPU, so does it have to be replaced to get more? In-place resize is stable in 1.35: you patch spec.containers[].resources through the resize subresource, and the Kubelet applies the new numbers to the container that is already running, in place or by restarting it, as resizePolicy says per resource. It answers PodResizePending when the Node cannot take the change, and the QoS class the Pod was created with never moves.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Resize Container Resources', href: 'https://kubernetes.io/docs/tasks/configure-pod-container/resize-container-resources/' },
      { label: 'Pod QoS Classes', href: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-qos/' },
      { label: 'Pod v1', href: 'https://kubernetes.io/docs/reference/kubernetes-api/core/pod-v1/' },
      { label: 'CRI Spec', href: 'https://github.com/kubernetes/cri-api/blob/master/pkg/apis/runtime/v1/api.proto' },
    ],
  },
  {
    id: 'workloads-poststart-prestop-hooks',
    title: 'postStart and preStop Hooks',
    category: 'workloads',
    subcategory: 'pods-lifecycle',
    desc: 'Where do postStart and preStop actually sit in a container life, and why do they behave so differently? Drawn on one timeline, postStart opens on the same tick as the ENTRYPOINT with no ordering guarantee between them, while preStop is run to completion before any signal and shares the termination grace window with the SIGTERM drain that follows it. Kubelet owns both slots, and it is the runtime that runs an exec handler inside the container.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Container Lifecycle Hooks', href: 'https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/' },
      { label: 'Pod Lifecycle', href: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/' },
    ],
  },
  {
    id: 'workloads-graceful-shutdown',
    title: 'Graceful Pod Shutdown',
    category: 'workloads',
    subcategory: 'pods-lifecycle',
    desc: 'Why does a deleted Pod still take traffic for a moment, and why does it not die on the spot? One DELETE stamps deletionTimestamp on the stored object and two tracks start: the control plane marks the endpoint terminating so kube-proxy stops choosing it while others stay ready, and the Kubelet runs preStop, has the runtime send the stop signal and spends the same 30s window. Neither waits for the other, preStop lines them up, and SIGKILL at 0s is the last resort.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Termination of Pods', href: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination' },
      { label: 'EndpointSlices', href: 'https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/' },
      { label: 'Traffic to terminating endpoints', href: 'https://kubernetes.io/docs/reference/networking/virtual-ips/#traffic-to-terminating-endpoints' },
    ],
  },
  {
    id: 'workloads-termination-order',
    title: 'Container Termination Order',
    category: 'workloads',
    subcategory: 'pods-lifecycle',
    desc: 'Which container in a multi-container Pod is stopped first, and why is it not the sidecar? Regular containers are signalled first, at different times and in no guaranteed order, and only once the last of them has terminated does the Kubelet signal the native sidecars, in the reverse of the order they are declared in. That keeps a proxy or a log agent alive while the app drains, and every stop is spent from one shared terminationGracePeriodSeconds.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Pod shutdown and sidecar containers', href: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#termination-with-sidecars' },
      { label: 'Sidecar Containers', href: 'https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/' },
    ],
  },
  {
    id: 'workloads-force-deletion',
    title: 'Force Deletion and Stuck Terminating Pods',
    category: 'workloads',
    subcategory: 'pods-lifecycle',
    desc: 'Why does a Pod sit in Terminating forever when its Node goes silent? The Kubelet never acknowledges the delete, so the API keeps the object and an identity-bound controller like StatefulSet refuses to create a replacement. Force deletion drops it from ETCD at once, but a merely partitioned Node may still be running the original container. That is why the flag exists but is never the first thing to reach for, and deleting the Node object is the safer route.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Force Delete StatefulSet Pods', href: 'https://kubernetes.io/docs/tasks/run-application/force-delete-stateful-set-pod/' },
      { label: 'Termination of Pods', href: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination' },
    ],
  },
  {
    id: 'workloads-pod-garbage-collection',
    title: 'Pod Garbage Collection',
    category: 'workloads',
    subcategory: 'pods-lifecycle',
    desc: 'Who deletes a Pod once it has finished? The object outlives the containers: a Succeeded or Failed Pod stays in the API until something removes it, and that something is PodGC in kube-controller-manager. It deletes terminated Pods oldest first once their number passes terminated-pod-gc-threshold, which defaults to 12500, and three further rules ignore the count and take orphans, unscheduled terminating Pods, and ones on a Node tainted out-of-service.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Garbage Collection of Pods', href: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-garbage-collection' },
      { label: 'kube-controller-manager', href: 'https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/' },
      { label: 'Pod Disruption Conditions', href: 'https://kubernetes.io/docs/concepts/workloads/pods/disruptions/#pod-disruption-conditions' },
    ],
  },
];
