// The workloads catalogue: every workloads card and the subcategories they sort into.
// Adding a card means one entry here, one file beside it, one poster, one note.

// The SUBCATEGORIES list below is an ORDER, not a set: the sequence is an editorial argument
// about what a reader has to know first, never alphabetical and never a merge artefact.

export const SUBCATEGORIES = [
    { key: 'pods-bootstrap', label: 'Pods Bootstrap' },
    { key: 'pods-lifecycle', label: 'Pods Lifecycle' },
    { key: 'controllers',   label: 'Controllers'    },
];

export const CARDS = [
  {
    id: 'workloads-rolling-update',
    title: 'Deployment Rolling Update',
    category: 'workloads',
    subcategory: 'controllers',
    desc: 'How do you move every Pod to a new version without taking the app offline? A Deployment rolls the change out gradually, bringing up Pods on the new version a few at a time and retiring old ones as the replacements report Ready, so the Service always keeps enough backends. The maxSurge and maxUnavailable dials, 25% each by default, set how wide that window is, and only at maxUnavailable 0 is an old Pod guaranteed to stay until its replacement serves.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Rolling Update Deployment', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#rolling-update-deployment' },
    ],
  },
  {
    id: 'workloads-deployment-rollback',
    title: 'Deployment Rollback and Revision History',
    category: 'workloads',
    subcategory: 'controllers',
    desc: 'A rollout went bad, so how do you get back to the version that worked? A Deployment keeps its old ReplicaSets as numbered revisions, so a rollback sends the broken one to zero while the previous one, never scaled down, keeps serving. That history undoes a bad change in one command, and revisionHistoryLimit, 10 by default, caps it: a pruned ReplicaSet takes its revision with it. A rollback creates a new revision rather than erasing the bad one.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Rolling Back a Deployment', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#rolling-back-a-deployment' },
    ],
  },
  {
    id: 'workloads-replicaset',
    title: 'ReplicaSet Reconcile and Ownership',
    category: 'workloads',
    subcategory: 'controllers',
    desc: 'How does Kubernetes keep exactly the right number of identical Pods alive? A ReplicaSet runs a control loop comparing how many Pods it should have against how many it can see, then creates or deletes until the two match. It owns them through ownerReferences, adopts any matching Pod that no other controller already owns, and releases one whose labels stop matching. Deployments never manage Pods directly, they manage ReplicaSets.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'ReplicaSet', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/' },
      { label: 'Owners and Dependents', href: 'https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/' },
    ],
  },
  {
    id: 'workloads-statefulset-ordered-startup',
    title: 'StatefulSet Ordered Rollout',
    category: 'workloads',
    subcategory: 'controllers',
    desc: 'Why does a StatefulSet start its Pods strictly one at a time? Under the default podManagementPolicy of OrderedReady, ordinal 0 has to be Ready before ordinal 1 is even created, which is what lets a clustered system elect a primary before any follower appears. Each Pod also keeps a stable name and its own claim across restarts, and under that same policy a scale-down reverses the order, newest ordinal first, so ordinal 0 is the last to go.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'OrderedReady Pod Management', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#orderedready-pod-management' },
    ],
  },
  {
    id: 'workloads-init-containers-and-sidecars',
    title: 'Init Containers and Native Sidecars',
    category: 'workloads',
    subcategory: 'pods-bootstrap',
    desc: 'How does a Pod start its containers when some of them must run before others? Init containers run strictly in order, each exiting 0 before the next begins, and a native sidecar (an initContainer with restartPolicy=Always, GA in 1.33) starts after them and runs for the whole Pod lifetime. The main container is held back until that sidecar reports Started, and on shutdown the termination order reverses. The sidecar still counts in the init list.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Sidecar Containers', href: 'https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/' },
    ],
  },
  {
    id: 'workloads-pod-image-pull',
    title: 'Image Pull and Registry Auth',
    category: 'workloads',
    subcategory: 'pods-bootstrap',
    desc: 'How does the Kubelet get a container image onto the Node before the container can run? It reads imagePullPolicy, which when you leave it unset defaults to Always for :latest or an untagged image and to IfNotPresent for any other tag or a digest, finds credentials through imagePullSecrets, and pulls only the layers the Node does not already hold by sha256 digest. A failed pull surfaces as ErrImagePull and retries on an exponential ImagePullBackOff.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Images', href: 'https://kubernetes.io/docs/concepts/containers/images/' },
      { label: 'ImagePullSecrets', href: 'https://kubernetes.io/docs/concepts/configuration/secret/#using-imagepullsecrets' },
      { label: 'OCI Distribution Spec', href: 'https://github.com/opencontainers/distribution-spec' },
    ],
  },
  {
    id: 'workloads-pod-qos-classes',
    title: 'Pod QoS Classes',
    category: 'workloads',
    subcategory: 'pods-bootstrap',
    desc: 'When a Node runs low on memory, which Pods does Kubernetes sacrifice first? At admission it reads each Pod resources block and assigns a QoS class: Guaranteed when every container sets both CPU and memory with requests equal to limits, BestEffort when nothing is set at all, Burstable in between. The class is fixed for the life of the Pod and drives the cgroup caps and the oom_score_adj, but not the eviction order, which goes by whether a Pod is over its request.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Pod QoS Classes', href: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-qos/' },
      { label: 'Resource Management', href: 'https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/' },
      { label: 'Node-pressure Eviction', href: 'https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/' },
    ],
  },
  {
    id: 'workloads-pvc-stickiness',
    title: 'StatefulSet PVC Stickiness',
    category: 'workloads',
    subcategory: 'controllers',
    desc: 'When a StatefulSet Pod moves to another Node, does its data move with it? The volume is bound to the Pod identity rather than to the Pod object, so it outlives the deletion and simply waits. When the replacement with the same ordinal starts, possibly on a different Node, it reattaches that same disk and sees exactly the bytes left behind. The disk follows the ordinal, never the Pod object or the Node, and the default retention policy keeps the claim.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Stable Storage', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-storage' },
      { label: 'StatefulSet Basics', href: 'https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/' },
    ],
  },
  {
    id: 'workloads-daemonset',
    title: 'DaemonSet Controller',
    category: 'workloads',
    subcategory: 'controllers',
    desc: 'How do you run one copy of a Pod on every eligible Node, and exactly one? A DaemonSet watches the Node set instead of a replica count, adding a Pod when an eligible Node joins and removing it when a Node leaves, so the fleet tracks the cluster rather than a fixed number. Its Pods also carry tolerations that let them land where ordinary workloads cannot. Scaling a DaemonSet means adding or removing Nodes.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'DaemonSet', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/' },
    ],
  },
  {
    id: 'workloads-job-parallelism',
    title: 'Job Parallelism and Completions',
    category: 'workloads',
    subcategory: 'controllers',
    desc: 'How does a Job run a batch of work to completion instead of serving forever? You give it completions, the number of successful runs you need, and parallelism, how many Pods may run at once, and it keeps launching Pods and retrying failures until that target is met. Once enough runs succeed it stops on its own and marks the batch complete. A failed Pod counts against backoffLimit, 6 by default, and reaching that limit fails the Job instead.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Parallel execution for Jobs', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/job/#parallel-jobs' },
    ],
  },
  {
    id: 'workloads-cronjob',
    title: 'CronJob Schedule and Concurrency',
    category: 'workloads',
    subcategory: 'controllers',
    desc: 'How do you run a Job on a repeating schedule instead of on demand? A CronJob holds a cron expression and, each time the clock matches, creates one Job from its template, which runs a Pod. It also decides what happens when a run is still going at the next tick, prunes finished Jobs, and starts a run missed while it was down, bounded both by startingDeadlineSeconds and by a ceiling of 100 missed ticks. A CronJob never runs a Pod itself, it only creates Jobs.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'CronJob', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/' },
      { label: 'Running Automated Tasks with a CronJob', href: 'https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/' },
    ],
  },
  {
    id: 'workloads-pod-phase-machine',
    title: 'Pod Lifecycle Phases',
    category: 'workloads',
    subcategory: 'pods-lifecycle',
    desc: 'What single field tells you where a Pod is in its life? The status.phase field moves through Pending while the Pod is placed and its images pulled, Running once every container exists and one has started, and then Succeeded or Failed when they all exit. It is deliberately coarse, so a container crash-looping inside a Running Pod never changes it. Phase is a summary of placement, not a statement about health.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Pod phase', href: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase' },
    ],
  },
  {
    id: 'workloads-pod-resize',
    title: 'In-place Pod Resize',
    category: 'workloads',
    subcategory: 'pods-lifecycle',
    desc: 'A running Pod is short on CPU, so does it have to be replaced to get more? Since 1.35 you can patch spec.containers[].resources through the resize subresource, and the Kubelet applies the new numbers to the container that is already running, in place or by restarting it, as resizePolicy says per resource. It answers PodResizePending when the Node cannot take the change, and the QoS class the Pod was created with never moves.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Resize Container Resources', href: 'https://kubernetes.io/docs/tasks/configure-pod-container/resize-container-resources/' },
      { label: 'Pod QoS Classes', href: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-qos/' },
      { label: 'Pod v1', href: 'https://kubernetes.io/docs/reference/kubernetes-api/core/pod-v1/' },
      { label: 'CRI Spec', href: 'https://github.com/kubernetes/cri-api/blob/master/pkg/apis/runtime/v1/api.proto' },
    ],
  },
  {
    id: 'workloads-restart-policy',
    title: 'Pod restartPolicy: Always, OnFailure, Never',
    category: 'workloads',
    subcategory: 'pods-lifecycle',
    desc: 'When a container in a Pod exits, what should happen next? The restartPolicy field is the Pod-level answer Kubernetes follows: Always brings the container back whatever the exit code, OnFailure retries only a non-zero exit, and Never leaves it alone. That choice separates a Pod that runs forever from one that retries and one that finishes. The Job controller relies on OnFailure and Never for exactly this, and the shared backoff only starts after the first restart.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Restart Policy', href: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy' },
    ],
  },
  {
    id: 'workloads-hooks',
    title: 'Lifecycle Hooks: postStart and preStop',
    category: 'workloads',
    subcategory: 'pods-lifecycle',
    desc: 'How does a container run code exactly when it starts and just before it stops? Lifecycle hooks give it two slots, postStart fired concurrently with the entrypoint and preStop run synchronously ahead of SIGTERM, both executed by the Kubelet rather than by your process. They are how a container announces itself and drains on the way out. The termination grace period bounds preStop, never postStart, and preStop shares it with the SIGTERM stop that follows.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Container Lifecycle Hooks', href: 'https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/' },
    ],
  },
  {
    id: 'workloads-probes',
    title: 'Startup, Liveness and Readiness Probes',
    category: 'workloads',
    subcategory: 'pods-lifecycle',
    desc: 'How does the Kubelet tell a slow boot from a hung container? Three probes answer that on their own periodSeconds: startupProbe gates the other two until the app is up, livenessProbe restarts the container after failureThreshold consecutive failures, and readinessProbe flips the Pod endpoint to ready=false in the EndpointSlice without removing it or restarting anything. A probe never restarts a Pod, only the container that failed it.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Configure Liveness, Readiness and Startup Probes', href: 'https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/' },
    ],
  },
  {
    id: 'workloads-container-states',
    title: 'Container Restarts and lastState',
    category: 'workloads',
    subcategory: 'pods-lifecycle',
    desc: 'A container crashed and restarted, so what killed it? The live state shows only the fresh Running instance, but Kubernetes keeps the previous termination beside it: lastState holds the exit code and reason, restartCount counts how often it has happened, and kubectl logs --previous reads the log stream of the instance that died. Together they are the whole post-mortem for a container you can no longer see, and only the last termination is kept.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Container States', href: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-states' },
    ],
  },
  {
    id: 'workloads-crashloopbackoff',
    title: 'CrashLoopBackOff and Restart Backoff',
    category: 'workloads',
    subcategory: 'pods-lifecycle',
    desc: 'Why does a broken container restart slower and slower? The Kubelet backs off exponentially, doubling the wait from 10s up to a 5 minute ceiling, so a crashing process cannot hot-loop and saturate the Node. During each wait the container reports Waiting with reason CrashLoopBackOff while the Pod phase stays Running, and only a clean run of 10 minutes resets the delay to the 10s base. CrashLoopBackOff is a symptom, never the cause.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Restart Policy', href: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy' },
    ],
  },
  {
    id: 'workloads-graceful-shutdown',
    title: 'Graceful Pod Shutdown',
    category: 'workloads',
    subcategory: 'pods-lifecycle',
    desc: 'When a Pod is deleted, why does it not die on the spot? The terminationGracePeriodSeconds budget, 30 by default, starts counting at the delete and is spent in two parts: the preStop hook, then the SIGTERM drain in which the app finishes in-flight work, closes its connections and exits on its own. SIGKILL is the last resort, used only if the container outlives that shared timer. Nothing in that path holds if the Node itself is already gone.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Termination of Pods', href: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination' },
    ],
  },
  {
    id: 'workloads-force-deletion',
    title: 'Force Deletion and Stuck Terminating Pods',
    category: 'workloads',
    subcategory: 'pods-lifecycle',
    desc: 'Why does a Pod sit in Terminating forever when its Node goes silent? The Kubelet never acknowledges the delete, so the API keeps the object and an identity-bound controller like StatefulSet refuses to create a replacement. Force deletion drops it from ETCD at once, but a merely partitioned Node may still be running the original container. That is why the flag exists but is never the first thing to reach for, and deleting the Node object is the safer route.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Force Delete StatefulSet Pods', href: 'https://kubernetes.io/docs/tasks/run-application/force-delete-stateful-set-pod/' },
      { label: 'Termination of Pods', href: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination' },
    ],
  },
];
