// The storage catalogue: every storage card and the subcategories they sort into.
// Adding a card means one entry here, one file beside it, one poster, one note.

// The SUBCATEGORIES list below is an ORDER, not a set: the sequence is an editorial argument
// about what a reader has to know first, never alphabetical and never a merge artefact.

export const SUBCATEGORIES = [
    { key: 'volume-foundations',   label: 'Volume Foundations' },
    { key: 'volumes-claims',        label: 'Volumes & Claims'   },
    { key: 'csi-mount-path',           label: 'CSI & Mount Path'   },
    { key: 'stateful-data', label: 'Stateful Data'      },
];

export const CARDS = [
  {
    id: 'storage-volume-model',
    title: 'Pod Volume Model',
    category: 'storage',
    subcategory: 'volume-foundations',
    desc: 'What is a Pod volume, and why does a file in it outlive the container that wrote it? A volume is declared once under spec.volumes and belongs to the Pod, and each container that wants it lists it in volumeMounts at a path of its own and optionally read-only, the usual way containers of one Pod share files. An init container can write a file and exit, the app can crash and restart, and an emptyDir like this one keeps the data until the Pod leaves its Node.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Volumes', href: 'https://kubernetes.io/docs/concepts/storage/volumes/' },
      { label: 'Why volumes are important', href: 'https://kubernetes.io/docs/concepts/storage/volumes/#why-volumes-are-important' },
    ],
  },
  {
    id: 'storage-volume-data-homes',
    title: 'Where Volume Data Lives',
    category: 'storage',
    subcategory: 'volume-foundations',
    desc: 'A Pod mounts five volumes, so where do their bytes live, and when does each one vanish? A write outside every volume lands in the container writable layer, emptyDir and hostPath sit on the Node storage, a Memory emptyDir sits in Node RAM, a ConfigMap is an API object that Kubelet copies in, and this claim points at network storage off the Node. Where the data lives decides whether it dies with the container, the Pod, the Node, or none of them.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Volumes', href: 'https://kubernetes.io/docs/concepts/storage/volumes/' },
      { label: 'Ephemeral Volumes', href: 'https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/' },
      { label: 'Persistent Volumes', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/' },
    ],
  },
  {
    id: 'storage-container-filesystem',
    title: 'Container Filesystem Layers',
    category: 'storage',
    subcategory: 'volume-foundations',
    desc: 'Why does a file written in a container vanish when the container is replaced, while a file under a volume stays? With the default overlayfs snapshotter the root filesystem is one overlay mount: a read takes the highest layer holding the path, and every change lands in the writable upperdir: a new file, a lower file copied up, or a whiteout hiding one. The image layers never change, the upperdir dies with the container, and a volume mounted at /data skips all of it.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Why volumes are important', href: 'https://kubernetes.io/docs/concepts/storage/volumes/#why-volumes-are-important' },
      { label: 'Images', href: 'https://kubernetes.io/docs/concepts/containers/images/' },
      { label: 'Container garbage collection', href: 'https://kubernetes.io/docs/concepts/architecture/garbage-collection/#container-image-garbage-collection' },
      { label: 'Overlay Filesystem', href: 'https://docs.kernel.org/filesystems/overlayfs.html' },
    ],
  },
  {
    id: 'storage-emptydir',
    title: 'emptyDir Lifecycle',
    category: 'storage',
    subcategory: 'volume-foundations',
    desc: 'What happens to an emptyDir when a container restarts, or when its Pod is replaced on another Node? The Kubelet creates it empty when the Pod is assigned to a Node, every container that mounts it shares it, and a restart keeps it, but once the Pod leaves that Node it is deleted, and a replacement Pod gets a new, empty one. With medium: Memory it is a tmpfs that counts against the memory limit of the container writing to it.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'emptyDir', href: 'https://kubernetes.io/docs/concepts/storage/volumes/#emptydir' },
      { label: 'Ephemeral Volumes', href: 'https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/' },
      { label: 'Memory-backed emptyDir', href: 'https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#memory-backed-emptydir' },
      { label: 'kubectl drain', href: 'https://kubernetes.io/docs/reference/kubectl/generated/kubectl_drain/' },
    ],
  },
  {
    id: 'storage-hostpath',
    title: 'hostPath Volumes',
    category: 'storage',
    subcategory: 'volume-foundations',
    desc: 'What does a hostPath volume hand a Pod, and why does it stay on one Node? The Kubelet checks the path against its type (Directory must exist, DirectoryOrCreate makes it), then the runtime bind-mounts it into the container, so writes land on the Node disk, escape the ephemeral-storage limit and outlive the Pod. A replacement on another Node finds a different directory or none, and since any path is allowed, Baseline and Restricted Pod Security forbid it.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'hostPath', href: 'https://kubernetes.io/docs/concepts/storage/volumes/#hostpath' },
      { label: 'Pod Security Standards', href: 'https://kubernetes.io/docs/concepts/security/pod-security-standards/' },
    ],
  },
  {
    id: 'storage-configmap-secret-mount',
    title: 'ConfigMap and Secret as Files',
    category: 'storage',
    subcategory: 'volume-foundations',
    desc: 'How does a ConfigMap or Secret volume change under a running app without showing a half-written file? Kubelet writes the keys the volume asks for as files in a hidden timestamped directory behind the ..data symlink. An update writes the new version beside it, renames a ..data_tmp link over ..data, atomic on Linux, and deletes the old one. It lands on the next Kubelet sync after the cache catches up, the app keeps running, and on Linux a Secret volume is tmpfs.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'ConfigMaps', href: 'https://kubernetes.io/docs/concepts/configuration/configmap/' },
      { label: 'Secrets', href: 'https://kubernetes.io/docs/concepts/configuration/secret/' },
      { label: 'configMap volumes', href: 'https://kubernetes.io/docs/concepts/storage/volumes/#configmap' },
      { label: 'secret volumes', href: 'https://kubernetes.io/docs/concepts/storage/volumes/#secret' },
      { label: 'Windows security', href: 'https://kubernetes.io/docs/concepts/security/windows-security/' },
    ],
  },
  {
    id: 'storage-downward-api-volume',
    title: 'Downward API Volume',
    category: 'storage',
    subcategory: 'volume-foundations',
    desc: 'How do Pod labels become a file that follows every relabel? A downwardAPI volume writes metadata.labels into a file, one key="value" line per label, and Kubelet rewrites it when a label changes, while an env var taken from one label key keeps the value it had when the container started. The whole labels or annotations map exists only as a file, and fields such as nodeName, podIP, hostIP and serviceAccountName only as env.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Downward API', href: 'https://kubernetes.io/docs/concepts/workloads/pods/downward-api/' },
      { label: 'Expose Pod information through files', href: 'https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/' },
    ],
  },
  {
    id: 'storage-projected-volume',
    title: 'Projected Volumes',
    category: 'storage',
    subcategory: 'volume-foundations',
    desc: 'How does one mounted directory hold a ConfigMap key, Pod metadata and a token that renews itself? A projected volume fills one mount from several sources, a ConfigMap, a Secret, downwardAPI, a serviceAccountToken, plus clusterTrustBundle and podCertificate, beta and off by default in 1.35. Kubelet replaces the audience-bound token at 80 percent of its lifetime or after 24 hours and the app re-reads it, while a legacy Secret token never expires.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Projected Volumes', href: 'https://kubernetes.io/docs/concepts/storage/projected-volumes/' },
      { label: 'Service Accounts', href: 'https://kubernetes.io/docs/concepts/security/service-accounts/' },
      { label: 'Token volume projection', href: 'https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#serviceaccount-token-volume-projection' },
    ],
  },
  {
    id: 'storage-image-volume',
    title: 'Image Volumes',
    category: 'storage',
    subcategory: 'volume-foundations',
    desc: 'How do you hand a Pod a large model or toolset from an OCI registry without baking it into the app image? An image volume names an OCI image or artifact by reference, and Kubelet resolves it at Pod startup by its pullPolicy, pulling it like a container image with the same pull credentials before any container starts. It is mounted read-only as one directory at the mountPath. A recreated Pod resolves it again, but IfNotPresent pulls it only if the Node lacks it.',
    k8sVersion: '1.36',
    tinted: true,
    sources: [
      { label: 'image volumes', href: 'https://kubernetes.io/docs/concepts/storage/volumes/#image' },
      { label: 'Use an Image Volume With a Pod', href: 'https://kubernetes.io/docs/tasks/configure-pod-container/image-volumes/' },
    ],
  },
  {
    id: 'storage-subpath',
    title: 'subPath Mounts',
    category: 'storage',
    subcategory: 'volume-foundations',
    desc: 'Why does a config file mounted with subPath miss an update? A subPath mount places one path from a volume, here one file beside the files an image ships, and Kubelet resolves it when the container starts. The ..data symlink flip that updates a ConfigMap, Secret, downward API or projected volume never reaches that mount, so a whole-directory mount in the same Pod reads v2 while the subPath file stays at v1 until its container restarts.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Using subPath', href: 'https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath' },
      { label: 'configMap volumes', href: 'https://kubernetes.io/docs/concepts/storage/volumes/#configmap' },
      { label: 'Projected Volumes', href: 'https://kubernetes.io/docs/concepts/storage/projected-volumes/' },
    ],
  },
  {
    id: 'storage-ephemeral-storage-eviction',
    title: 'Ephemeral Storage Limit Eviction',
    category: 'storage',
    subcategory: 'volume-foundations',
    desc: 'A Pod writes temp files, logs and scratch data to its Node, so why is it evicted while the Node disk is fine? The Kubelet periodically sums the writable layers, log files and disk emptyDir of each Pod against limits.ephemeral-storage: a container counts its own layer and logs, the Pod adds the emptyDir. Over the limit the whole Pod is evicted, not restarted, and stays Failed with reason Evicted while its controller, if any, makes a new one.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Local Ephemeral Storage', href: 'https://kubernetes.io/docs/concepts/storage/ephemeral-storage/' },
      { label: 'Node-pressure Eviction', href: 'https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/' },
    ],
  },
  {
    id: 'storage-recursive-readonly',
    title: 'Recursive Read-Only Mounts',
    category: 'storage',
    subcategory: 'volume-foundations',
    desc: 'A volume is mounted readOnly, so why can a container still write under it? On Linux readOnly makes only that one mount read-only, so a tmpfs mounted read-write below a hostPath directory stays writable. Setting recursiveReadOnly: Enabled makes the whole tree read-only but needs readOnly true, mountPropagation None or unset and kernel and runtime support, or the container does not start. Without that support IfPossible falls back to Disabled.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Read-only mounts', href: 'https://kubernetes.io/docs/concepts/storage/volumes/#read-only-mounts' },
      { label: 'Recursive read-only mounts', href: 'https://kubernetes.io/docs/concepts/storage/volumes/#recursive-read-only-mounts' },
    ],
  },
  {
    id: 'storage-pvc-binding',
    title: 'PVC to PV Binding',
    category: 'storage',
    subcategory: 'volumes-claims',
    desc: 'A PersistentVolumeClaim is a request, not storage, so who hands it a real volume? The binding controller scans the Available volumes, drops the ones too small, of the wrong class or short on access mode, and pairs the claim with one that satisfies all three by writing the link on both objects, the volume first. The pairing is exclusive, so with no dynamic provisioner behind the class a second claim like it stays Pending until an administrator adds another volume.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Persistent Volumes', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/' },
      { label: 'Binding', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/#binding' },
    ],
  },
  {
    id: 'storage-default-storageclass',
    title: 'Default StorageClass',
    category: 'storage',
    subcategory: 'volumes-claims',
    desc: 'A PVC does not name a StorageClass, so where does it get one, and why does storageClassName: "" behave differently from leaving the field out? Left out, the DefaultStorageClass admission plugin writes in the class annotated as default at creation, and if none exists yet the PV binding controller writes it into the still unbound claim once one appears. An empty string asks for no class, so both leave it alone and it binds only to a classless volume.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Default StorageClass', href: 'https://kubernetes.io/docs/concepts/storage/storage-classes/#default-storageclass' },
      { label: 'Retroactive default StorageClass assignment', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/#retroactive-default-storageclass-assignment' },
      { label: 'DefaultStorageClass admission', href: 'https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#defaultstorageclass' },
    ],
  },
  {
    id: 'storage-dynamic-provisioning',
    title: 'Dynamic Volume Provisioning',
    category: 'storage',
    subcategory: 'volumes-claims',
    desc: 'Binding only works if a matching volume already exists, so what happens when none does? The claim names a StorageClass, that class names a provisioner, and the provisioner watches for Pending claims pointing at it. It calls CreateVolume on the driver to carve a real disk out of the backend, then writes a PersistentVolume to represent it, already carrying that claimRef. The disk is built to order for that one claim.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Dynamic Provisioning', href: 'https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/' },
      { label: 'Storage Classes', href: 'https://kubernetes.io/docs/concepts/storage/storage-classes/' },
    ],
  },
  {
    id: 'storage-access-modes',
    title: 'Access Modes',
    category: 'storage',
    subcategory: 'volumes-claims',
    desc: 'ReadWriteOnce sounds like one Pod, so why can two Pods share the same volume? Because the mode is per Node, not per Pod: once a block disk is attached to a Node, any Pod scheduled there can mount it, while the attach controller refuses a Pod elsewhere with a Multi-Attach error. ReadWriteOncePod narrows it to one Pod. ReadWriteMany needs a backend that can deliver it, like NFS, and a single-attach block disk cannot.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Access Modes', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes' },
      { label: 'Persistent Volumes', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/' },
    ],
  },
  {
    id: 'storage-volume-mode',
    title: 'Filesystem vs Block',
    category: 'storage',
    subcategory: 'volumes-claims',
    desc: 'Two claims for identical disks, one field apart, so why does only one come back with a filesystem? The volumeMode field is Filesystem unless you say otherwise, so the CSI node service runs mkfs on a blank device, mounts it, and the container finds a directory. Set it to Block and the raw device is published instead, so fsGroup, subPath and file permissions stop applying. The field is immutable and must match on the claim and its volume.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Volume Mode', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/#volume-mode' },
      { label: 'Raw Block Volume Support', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/#raw-block-volume-support' },
    ],
  },
  {
    id: 'storage-topology-aware-provisioning',
    title: 'Immediate vs WaitForFirstConsumer',
    category: 'storage',
    subcategory: 'volumes-claims',
    desc: 'Why can a Pod sit in Pending in a multi-zone cluster with a healthy disk right there? With volumeBindingMode Immediate the volume is provisioned the instant the claim exists, in whatever zone the provisioner picks, and the Pod is stuck if no Node then both fits it and lies in that zone. WaitForFirstConsumer inverts the order so the Scheduler chooses the Node first. That failure is common in multi-zone clusters, and this is its one-line fix.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Volume Binding Mode', href: 'https://kubernetes.io/docs/concepts/storage/storage-classes/#volume-binding-mode' },
      { label: 'Allowed Topologies', href: 'https://kubernetes.io/docs/concepts/storage/storage-classes/#allowed-topologies' },
    ],
  },
  {
    id: 'storage-csi-capacity-tracking',
    title: 'CSI Storage Capacity',
    category: 'storage',
    subcategory: 'volumes-claims',
    desc: 'Why does a Pod get stuck Pending when the local storage pool on its chosen Node is full? Without capacity information the Scheduler picks that Node with no view of its free space, provisioning fails there, and the Node choice is reset so the Pod is placed blind again on the next pass. CSIStorageCapacity objects from a driver that opts in let the Scheduler see free space per Node and filter first, on classes that bind WaitForFirstConsumer.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Storage Capacity', href: 'https://kubernetes.io/docs/concepts/storage/storage-capacity/' },
      { label: 'CSIStorageCapacity API', href: 'https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/csi-storage-capacity-v1/' },
      { label: 'CSI capacity tracking', href: 'https://kubernetes-csi.github.io/docs/storage-capacity-tracking.html' },
    ],
  },
  {
    id: 'storage-volume-expansion',
    title: 'Online Volume Expansion',
    category: 'storage',
    subcategory: 'volumes-claims',
    desc: 'Bumping a PVC to a bigger size grows nothing on its own, so what makes a Pod see more space? The API accepts the edit only if allowVolumeExpansion is true on the StorageClass, then one or two phases run: the external-resizer grows the disk, and Kubelet grows the filesystem, a step a driver may skip on a raw block volume. Where that filesystem grows online the room appears with no restart. Shrinking is refused: no safe general way exists to shrink a live filesystem.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Expanding Persistent Volumes Claims', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/#expanding-persistent-volumes-claims' },
      { label: 'Resizing an in-use PersistentVolumeClaim', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/#resizing-an-in-use-persistentvolumeclaim' },
    ],
  },
  {
    id: 'storage-pvc-protection',
    title: 'PVC Protection Finalizers',
    category: 'storage',
    subcategory: 'volumes-claims',
    desc: 'You run kubectl delete pvc and the claim sits in Terminating, so what is holding it? The pvc-protection finalizer, added at creation: while a Pod using the claim still exists the deletionTimestamp is set but the delete never completes, because pulling storage from a running Pod would break it. Terminating is only a display: the phase stays Bound the whole time, and only the last consuming Pod leaving frees it. The fix is finding that Pod.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Storage Object in Use Protection', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/#storage-object-in-use-protection' },
      { label: 'Finalizers', href: 'https://kubernetes.io/docs/concepts/overview/working-with-objects/finalizers/' },
    ],
  },
  {
    id: 'storage-reclaim-policy',
    title: 'Reclaim Policy',
    category: 'storage',
    subcategory: 'volumes-claims',
    desc: 'You delete a PVC, so does the disk full of data go with it? One field on the PV decides, copied from the StorageClass when the volume is made, Delete unless the class says otherwise, and patchable on a live PV. Delete destroys the backing disk and then the PV object, while Retain touches nothing and leaves an orphan: a new claim of the same class gets a fresh empty disk, and even deleting the PV by hand leaves the old disk in the backend.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Reclaiming', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/#reclaiming' },
      { label: 'Retain', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/#retain' },
      { label: 'Change the Reclaim Policy of a PersistentVolume', href: 'https://kubernetes.io/docs/tasks/administer-cluster/change-pv-reclaim-policy/' },
    ],
  },
  {
    id: 'storage-pv-lifecycle-phases',
    title: 'PV Lifecycle Phases',
    category: 'storage',
    subcategory: 'volumes-claims',
    desc: 'What does the phase of a PersistentVolume track, and who moves it? The PV controller in kube-controller-manager writes it on events: a bound claim makes it Bound, a deleted claim makes it Released, as the stale claimRef stays. Under Delete a CSI volume leaves the row, Failed means reclamation failed, for instance when no plugin can delete it, and short of the deprecated Recycle the way back is clearing the claimRef by hand, old data included.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Lifecycle of a Volume and Claim', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/#lifecycle-of-a-volume-and-claim' },
      { label: 'Phase', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/#phase' },
      { label: 'Reclaiming', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/#reclaiming' },
    ],
  },
  {
    id: 'storage-pv-reservation',
    title: 'Reserving a PersistentVolume',
    category: 'storage',
    subcategory: 'volumes-claims',
    desc: 'How do you hand a retained disk full of data to a new claim, and make sure no other claim grabs it first? An administrator points the claimRef of the Released PV at the new claim by name and namespace, with no UID, so the PV turns Available for that claim alone and the binder skips it for every other claim. The claim names the PV in volumeName with storageClassName set to an empty string and the binder pairs them, while volumeName alone reserves nothing.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Reserving a PersistentVolume', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/#reserving-a-persistentvolume' },
      { label: 'Retain', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/#retain' },
      { label: 'Lifecycle of a Volume and Claim', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/#lifecycle-of-a-volume-and-claim' },
    ],
  },
  {
    id: 'storage-csi-architecture',
    title: 'CSI Architecture',
    category: 'storage',
    subcategory: 'csi-mount-path',
    desc: 'Kubernetes core runs no storage vendor driver of its own, so how does an EBS or Ceph disk get mounted? A CSI driver ships in two halves: the controller plugin runs as a Deployment or StatefulSet whose sidecars each watch one kind of object and turn it into gRPC calls, and the node plugin is a DaemonSet that registers with Kubelet. Only the node plugin mounts a filesystem volume for a Pod, and the runtime just binds that mount into the container.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'CSI Volumes', href: 'https://kubernetes.io/docs/concepts/storage/volumes/#csi' },
      { label: 'Sidecar Containers', href: 'https://kubernetes-csi.github.io/docs/sidecar-containers.html' },
      { label: 'Deploying a CSI driver', href: 'https://kubernetes-csi.github.io/docs/deploying.html' },
    ],
  },
  {
    id: 'storage-csidriver',
    title: 'CSIDriver Object',
    category: 'storage',
    subcategory: 'csi-mount-path',
    desc: 'Two CSI drivers serve one Pod, so why does one volume get a VolumeAttachment and an fsGroup change while the other gets Pod info in its mount call instead? Each driver here has a cluster scoped CSIDriver object named exactly after it, whose fields tell the attach-detach controller whether to attach and tell Kubelet whether to pass Pod info and apply fsGroup. A driver with no such object gets the defaults, and attach is required.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'CSIDriver API', href: 'https://kubernetes.io/docs/reference/kubernetes-api/storage/csi-driver-v1/' },
      { label: 'CSIDriver Object', href: 'https://kubernetes-csi.github.io/docs/csi-driver-object.html' },
      { label: 'CSI Skip Attach', href: 'https://kubernetes-csi.github.io/docs/skip-attach.html' },
      { label: 'CSI Pod Info on Mount', href: 'https://kubernetes-csi.github.io/docs/pod-info.html' },
      { label: 'CSI fsGroup Support', href: 'https://kubernetes-csi.github.io/docs/support-fsgroup.html' },
    ],
  },
  {
    id: 'storage-csi-attach-mount',
    title: 'Attach and Mount Chain',
    category: 'storage',
    subcategory: 'csi-mount-path',
    desc: 'A new claim is not a mounted disk, so what happens between the two? Up to four gRPC calls run in order: CreateVolume makes the disk, ControllerPublishVolume, where attach is required, attaches it to the Node, NodeStageVolume, if the driver stages, formats it if still blank and mounts it once at a global staging path, and NodePublishVolume mounts that into the Pod directory, usually by bind. When its last Pod goes, the other three undo in reverse and the disk stays.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'CSI Volumes', href: 'https://kubernetes.io/docs/concepts/storage/volumes/#csi' },
      { label: 'CSI Specification', href: 'https://github.com/container-storage-interface/spec/blob/master/spec.md' },
      { label: 'Persistent Volumes', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/' },
    ],
  },
  {
    id: 'storage-volumeattachment',
    title: 'VolumeAttachment',
    category: 'storage',
    subcategory: 'csi-mount-path',
    desc: 'What records that a disk is attached to a Node, and who writes it? Not Kubelet: for a CSI driver that requires attach, the attach-detach controller writes a VolumeAttachment, and the external-attacher calls ControllerPublishVolume and sets status.attached true. Only then does Kubelet get it mounted. Deleting the object detaches: the controller does so once the Pod is gone and Kubelet has unmounted, and it counts toward the Node attach limit until it is gone.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'VolumeAttachment API', href: 'https://kubernetes.io/docs/reference/kubernetes-api/storage/volume-attachment-v1/' },
      { label: 'CSI external-attacher', href: 'https://kubernetes-csi.github.io/docs/external-attacher.html' },
      { label: 'CSI Skip Attach', href: 'https://kubernetes-csi.github.io/docs/skip-attach.html' },
    ],
  },
  {
    id: 'storage-mount-path-chain',
    title: 'Mount Namespaces and Propagation',
    category: 'storage',
    subcategory: 'csi-mount-path',
    desc: 'How does a mount made inside the CSI node plugin container reach the host and then the app? Each container has its own mount namespace, and the plugin sets mountPropagation Bidirectional on its Kubelet directory mounts, so every mount it makes there is repeated in the host list, where a bind mount is the same files at a second path. The app container gets its own bind at /data, private by default, so later host mounts do not reach it.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Mount propagation', href: 'https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation' },
      { label: 'Deploying a CSI driver', href: 'https://kubernetes-csi.github.io/docs/deploying.html' },
      { label: 'Shared subtrees', href: 'https://docs.kernel.org/filesystems/sharedsubtree.html' },
      { label: 'Linux mount namespaces', href: 'https://man7.org/linux/man-pages/man7/mount_namespaces.7.html' },
    ],
  },
  {
    id: 'storage-csi-ephemeral-volume',
    title: 'CSI Ephemeral Volumes',
    category: 'storage',
    subcategory: 'csi-mount-path',
    desc: 'How do you mount a credential from an external store with no PV and no PVC? A CSI volume written inline in the Pod spec goes straight to the CSI node plugin: Kubelet calls NodePublishVolume, the driver creates the volume in that call and deletes it on NodeUnpublishVolume, with no StorageClass, no claim and no attach. Only a driver whose CSIDriver lists the Ephemeral mode may serve it, and since volumeAttributes come from the Pod author, an admin can drop that mode.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'CSI ephemeral volumes', href: 'https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#csi-ephemeral-volumes' },
      { label: 'CSI Ephemeral Local Volumes', href: 'https://kubernetes-csi.github.io/docs/ephemeral-local-volumes.html' },
      { label: 'Secrets Store CSI Driver concepts', href: 'https://secrets-store-csi-driver.sigs.k8s.io/concepts.html' },
    ],
  },
  {
    id: 'storage-fsgroup-ownership',
    title: 'fsGroup and Volume Ownership',
    category: 'storage',
    subcategory: 'csi-mount-path',
    desc: 'A freshly mounted volume is owned by root, so why can a non-root container not write to it? The securityContext.fsGroup field names a GID, and on a volume that supports it Kubelet chowns the whole tree to that group before the container starts, unless a CSI driver does it. That walk is cheap on a small volume but can add minutes on one with millions of files, which is what fsGroupChangePolicy OnRootMismatch skips. The default walks the whole tree every start.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Security Context', href: 'https://kubernetes.io/docs/tasks/configure-pod-container/security-context/' },
      { label: 'Volume Permission and Ownership Change Policy', href: 'https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods' },
    ],
  },
  {
    id: 'storage-volume-attach-limits',
    title: 'Node Volume Attach Limits',
    category: 'storage',
    subcategory: 'csi-mount-path',
    desc: 'Why does a Pod stay Pending on max volume count while every Node has spare CPU and memory? Because a Node has a second, invisible capacity: how many volumes one CSI driver may have attached at once. The node plugin reports it, Kubelet writes it into CSINode, and the Scheduler rejects any Node the Pod would push past it. A slot frees when the detach completes, not when the Pod dies, turning a rollout near the ceiling into a race.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'CSINode API', href: 'https://kubernetes.io/docs/reference/kubernetes-api/storage/csi-node-v1/' },
      { label: 'Node-specific Volume Limits', href: 'https://kubernetes.io/docs/concepts/storage/storage-limits/' },
    ],
  },
  {
    id: 'storage-multi-attach-error',
    title: 'Multi-Attach Error',
    category: 'storage',
    subcategory: 'csi-mount-path',
    desc: 'Why does a Pod hang in ContainerCreating with a Multi-Attach error for its volume? An RWO disk attaches to one Node at a time, and RollingUpdate stands the replacement up on a new Node while the old Pod still holds the attachment. Nothing is broken: the controller will not write a second VolumeAttachment and a one-replica rollout will not delete the old Pod, so each waits on the other. Recreate breaks it by deleting first.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Access Modes', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes' },
      { label: 'Deployment Strategy', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy' },
    ],
  },
  {
    id: 'storage-volume-detach-on-node-loss',
    title: 'Detach on Node Failure',
    category: 'storage',
    subcategory: 'csi-mount-path',
    desc: 'When a Node goes NotReady, why does its volume not move to a healthy Node right away? Nothing is contending for it, so the wait is on doubt rather than on a rival claim: the old Pod cannot be confirmed dead, and detaching a disk it might still be writing to risks corruption. Kubernetes rides out the eviction timeout and then the force-detach timeout, which is a safety property. Those two clocks are the outage, and the out-of-service taint skips them.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Non-graceful Node Shutdown', href: 'https://kubernetes.io/docs/concepts/cluster-administration/node-shutdown/#non-graceful-node-shutdown' },
      { label: 'Persistent Volumes', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/' },
    ],
  },
  {
    id: 'storage-volumeclaimtemplates',
    title: 'StatefulSet volumeClaimTemplates',
    category: 'storage',
    subcategory: 'stateful-data',
    desc: 'Why does every replica of a StatefulSet get its own disk, when Deployment replicas that name a claim all share that one? The volumeClaimTemplate stamps out one PersistentVolumeClaim per ordinal with a deterministic name like data-web-0 rather than a random one. Because that name comes from the Pod identity, a recreated Pod, even on another Node, mounts the same claim and data. Scaling down leaves the claims behind, as the default retention policy is Retain.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Volume Claim Templates', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#volume-claim-templates' },
      { label: 'Stable Storage', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-storage' },
      { label: 'PVC Retention Policy', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#persistentvolumeclaim-retention' },
      { label: 'Binding', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/#binding' },
    ],
  },
  {
    id: 'storage-pvc-retention-policy',
    title: 'StatefulSet PVC Retention',
    category: 'storage',
    subcategory: 'stateful-data',
    desc: 'When a StatefulSet scales down or is deleted, which of its claims survive? The persistentVolumeClaimRetentionPolicy answers with two independent fields, whenScaled and whenDeleted, each Retain, the default, or Delete, and Delete gives the claim an ownerReference, to the removed Pod or to the StatefulSet, so the garbage collector deletes it after its owner. Deleting a claim only releases its PV, whose own reclaimPolicy decides whether the disk goes too.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'PVC Retention Policy', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#persistentvolumeclaim-retention' },
      { label: 'Cascading Deletion', href: 'https://kubernetes.io/docs/concepts/architecture/garbage-collection/#cascading-deletion' },
      { label: 'Reclaiming', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/#reclaiming' },
      { label: 'Volume Binding Mode', href: 'https://kubernetes.io/docs/concepts/storage/storage-classes/#volume-binding-mode' },
    ],
  },
  {
    id: 'storage-generic-ephemeral-volume',
    title: 'Generic Ephemeral Volumes',
    category: 'storage',
    subcategory: 'stateful-data',
    desc: 'What if you want scratch space that behaves like emptyDir but can be large and on a real StorageClass? A generic ephemeral volume is an inline volumeClaimTemplate written on the Pod, and it gets a real PVC, real dynamic provisioning and a real CSI mount. Its lifetime is still the Pod: the PVC carries an ownerReference and is collected when the Pod goes, taking the disk with it unless the class says Retain. It bridges scratch and the real machinery.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Generic Ephemeral Volumes', href: 'https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#generic-ephemeral-volumes' },
      { label: 'Ephemeral Volumes', href: 'https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/' },
    ],
  },
  {
    id: 'storage-volume-snapshot',
    title: 'Volume Snapshots',
    category: 'storage',
    subcategory: 'stateful-data',
    desc: 'How can a snapshot be ready in seconds, and why is it not always a backup? A VolumeSnapshot binds to a cluster-scoped VolumeSnapshotContent the way a PVC binds a PV, and on a copy-on-write backend the snapshot is a frozen map of the volume blocks, so only a block written later is kept twice and a restore gets a new, crash-consistent volume holding the older state. Here the volume, snapshot and restore share one Ceph RBD pool, and losing it loses all three.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Volume Snapshots', href: 'https://kubernetes.io/docs/concepts/storage/volume-snapshots/' },
      { label: 'VolumeSnapshotClasses', href: 'https://kubernetes.io/docs/concepts/storage/volume-snapshot-classes/' },
      { label: 'Snapshot Controller', href: 'https://kubernetes-csi.github.io/docs/snapshot-controller.html' },
      { label: 'CSI external-snapshotter', href: 'https://kubernetes-csi.github.io/docs/external-snapshotter.html' },
    ],
  },
  {
    id: 'storage-pvc-clone',
    title: 'Cloning a PVC',
    category: 'storage',
    subcategory: 'stateful-data',
    desc: 'What has to match before Kubernetes will clone a volume? A clone is an ordinary PVC whose dataSource names an existing claim, made only when the two fit: the same namespace and volumeMode, a size at least the source, and a source that is Bound and not in use, while the class may differ if its driver is the same. The storage system duplicates the volume server-side with no VolumeSnapshot in between, and afterwards the clone shares nothing with its source.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'CSI Volume Cloning', href: 'https://kubernetes.io/docs/concepts/storage/volume-pvc-datasource/' },
      { label: 'Provisioning', href: 'https://kubernetes.io/docs/concepts/storage/volume-pvc-datasource/#provisioning' },
    ],
  },
];
