// The storage catalogue: every storage card and the subcategories they sort into.
// Adding a card means one entry here, one file beside it, one poster, one note.

// The SUBCATEGORIES list below is an ORDER, not a set: the sequence is an editorial argument
// about what a reader has to know first, never alphabetical and never a merge artefact.

export const SUBCATEGORIES = [
    { key: 'volume-foundations',   label: 'Volume Foundations' },
    { key: 'volumes-claims',        label: 'Volumes & Claims'   },
    { key: 'csi-mount-path',           label: 'CSI & Mount Path'   },
    { key: 'stateful-data', label: 'Stateful Data'      },
];

export const CARDS = [
  {
    id: 'storage-volume-model',
    title: 'Pod Volume Model',
    category: 'storage',
    subcategory: 'volume-foundations',
    desc: 'What does it mean for a Pod to have a volume, and who does it belong to? It is declared once at the Pod level under spec.volumes and mounted into each container at volumeMounts, possibly at a different path. Because it belongs to the Pod, not to any container, two containers that mount it share every write and data outlives a crash. Delete the Pod and an ephemeral volume goes too, which is the gap persistent storage closes.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Volumes', href: 'https://kubernetes.io/docs/concepts/storage/volumes/' },
      { label: 'Why volumes are important', href: 'https://kubernetes.io/docs/concepts/storage/volumes/#why-volumes-are-important' },
    ],
  },
  {
    id: 'storage-container-filesystem',
    title: 'Container Filesystem Layers',
    category: 'storage',
    subcategory: 'volume-foundations',
    desc: 'Why does a file written inside a container vanish on restart, but a file on a volume does not? A container root filesystem is a stack of read-only image layers with one thin writable layer on top, merged by overlayfs, and that writable layer is thrown away when the container is removed. A mounted volume is a hole punched straight through the overlay to real storage. Editing a file from an image copies it up first, and the copy dies with the writable layer.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Why volumes are important', href: 'https://kubernetes.io/docs/concepts/storage/volumes/#why-volumes-are-important' },
      { label: 'Images', href: 'https://kubernetes.io/docs/concepts/containers/images/' },
    ],
  },
  {
    id: 'storage-emptydir',
    title: 'emptyDir Lifecycle',
    category: 'storage',
    subcategory: 'volume-foundations',
    desc: 'Where does an emptyDir live, and exactly when does it disappear? It is created empty the moment the Pod is assigned to a Node, sits on that Node disk, and is shared by every container in the Pod. It survives a container restarting but is deleted forever when the Pod leaves the Node. Set medium to Memory and it becomes tmpfs sized to the sizeLimit, so a write past it fails, while on disk that same limit gets the Pod evicted instead.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'emptyDir', href: 'https://kubernetes.io/docs/concepts/storage/volumes/#emptydir' },
      { label: 'Ephemeral Volumes', href: 'https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/' },
    ],
  },
  {
    id: 'storage-hostpath',
    title: 'hostPath Volumes',
    category: 'storage',
    subcategory: 'volume-foundations',
    desc: 'Why does a hostPath look like persistent storage and quietly is not? It mounts a path on the Node itself, so the data stays behind on that one Node when the Pod is gone, and type Directory demands that the path already exist while only DirectoryOrCreate makes one. Pointed at the runtime socket it hands over the whole Node, which is why the Baseline and Restricted Pod Security Standards forbid it outright. It is a Node-agent tool, never an application one.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'hostPath', href: 'https://kubernetes.io/docs/concepts/storage/volumes/#hostpath' },
      { label: 'Pod Security Standards', href: 'https://kubernetes.io/docs/concepts/security/pod-security-standards/' },
    ],
  },
  {
    id: 'storage-configmap-secret-mount',
    title: 'ConfigMap and Secret as Files',
    category: 'storage',
    subcategory: 'volume-foundations',
    desc: 'How does a ConfigMap become files, and why does an update never show a half-written config? Each key becomes a file, and Kubelet writes them into a timestamped directory then flips one ..data symlink, so every update is atomic. Changes arrive on the sync period, up to about a minute, and nothing restarts the app. A subPath mount opts out and never updates, and a Secret defaults to tmpfs so it never touches the disk.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'ConfigMaps', href: 'https://kubernetes.io/docs/concepts/configuration/configmap/' },
      { label: 'Secrets', href: 'https://kubernetes.io/docs/concepts/configuration/secret/' },
    ],
  },
  {
    id: 'storage-projected-volume',
    title: 'Projected Volumes',
    category: 'storage',
    subcategory: 'volume-foundations',
    desc: 'What if one directory needs a ConfigMap, a Secret, Pod metadata and an API token at once? A projected volume assembles all of them into a single mount, and the serviceAccountToken source is the one that matters. Unlike the old Secret-based token that never expired, a projected token is short-lived and audience-bound, and Kubelet rotates it in place before it expires. The app just keeps reading one valid file.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Projected Volumes', href: 'https://kubernetes.io/docs/concepts/storage/projected-volumes/' },
      { label: 'Service Accounts', href: 'https://kubernetes.io/docs/concepts/security/service-accounts/' },
    ],
  },
  {
    id: 'storage-ephemeral-storage-eviction',
    title: 'Ephemeral Storage Limits',
    category: 'storage',
    subcategory: 'volume-foundations',
    desc: 'A container fills the Node disk with logs, so which Pod gets evicted and why? Two separate paths exist: limits.ephemeral-storage evicts that one Pod the instant its writable layer, disk-backed emptyDir and logs exceed it, however healthy the Node is. Node-pressure eviction instead has Kubelet report DiskPressure on the Node, then takes the Pods over their request first, ranked by Priority and by how far over each sits. It can take a Pod inside its own limit.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Local Ephemeral Storage', href: 'https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#local-ephemeral-storage' },
      { label: 'Node-pressure Eviction', href: 'https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/' },
    ],
  },
  {
    id: 'storage-ephemeral-vs-persistent',
    title: 'Ephemeral vs Persistent',
    category: 'storage',
    subcategory: 'volume-foundations',
    desc: 'Two volumes in one Pod, both written to, so why does only one survive a reschedule? An emptyDir is tied to the Node, so a Pod that is deleted and lands elsewhere comes back completely empty. A PersistentVolumeClaim is tied to nothing but the claim, so it reattaches the very same disk with the data intact. Same Pod spec, two outcomes: scratch goes in an emptyDir, anything you keep goes behind a PVC, which is an object with a life of its own.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Persistent Volumes', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/' },
      { label: 'Ephemeral Volumes', href: 'https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/' },
    ],
  },
  {
    id: 'storage-pvc-binding',
    title: 'PVC to PV Binding',
    category: 'storage',
    subcategory: 'volumes-claims',
    desc: 'A PersistentVolumeClaim is a request, not storage, so who turns it into a real disk? The binding controller scans the volumes that are Available, throws out the ones too small, of the wrong class or short on access mode, and pairs the claim with one that satisfies all three by writing the link on both objects at once. That pairing is exclusive and permanent, so a second claim for the same volume waits until a volume it can have appears.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Persistent Volumes', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/' },
      { label: 'Binding', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/#binding' },
    ],
  },
  {
    id: 'storage-dynamic-provisioning',
    title: 'StorageClass Provisioning',
    category: 'storage',
    subcategory: 'volumes-claims',
    desc: 'Binding only works if a matching volume already exists, so what happens when none does? The claim names a StorageClass, that class names a provisioner, and the provisioner watches for Pending claims pointing at it. It calls CreateVolume on the driver to carve a real disk out of the backend, then writes a PersistentVolume to represent it, already carrying that claimRef. The disk is built to order for that one claim.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Dynamic Provisioning', href: 'https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/' },
      { label: 'Storage Classes', href: 'https://kubernetes.io/docs/concepts/storage/storage-classes/' },
    ],
  },
  {
    id: 'storage-access-modes',
    title: 'Access Modes',
    category: 'storage',
    subcategory: 'volumes-claims',
    desc: 'ReadWriteOnce sounds like one Pod, so why can two Pods share the same volume? Because the mode is per Node, not per Pod: once a block disk is attached to a Node, any Pod scheduled there can mount it, while a Pod elsewhere gets a Multi-Attach error. ReadWriteMany needs a shared filesystem like NFS rather than a raw disk. Mostly the mode is a request the driver honours, and ReadWriteOncePod is the one Kubernetes enforces itself.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Access Modes', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes' },
      { label: 'Persistent Volumes', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/' },
    ],
  },
  {
    id: 'storage-volume-mode',
    title: 'Filesystem vs Block',
    category: 'storage',
    subcategory: 'volumes-claims',
    desc: 'Two claims for identical disks, one field apart, so why does only one come back with a filesystem? The volumeMode field is Filesystem unless you say otherwise, so the CSI node service runs mkfs on a blank device, mounts it, and the container finds a directory. Set it to Block and the raw device is published instead, so fsGroup, subPath and file permissions stop applying. The field is immutable and must match on both.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Volume Mode', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/#volume-mode' },
      { label: 'Raw Block Volume Support', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/#raw-block-volume-support' },
    ],
  },
  {
    id: 'storage-volume-expansion',
    title: 'Online Volume Expansion',
    category: 'storage',
    subcategory: 'volumes-claims',
    desc: 'Bumping a PVC to a bigger size grows nothing on its own, so what makes a Pod see more space? The API accepts the edit only if allowVolumeExpansion is true on the StorageClass, then runs two phases: the external-resizer grows the disk, and Kubelet grows the filesystem, a phase a raw block volume skips entirely. Where that filesystem grows online the room appears with no restart. Shrinking is refused, there being no safe way to shrink a live filesystem.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Expanding Persistent Volumes Claims', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/#expanding-persistent-volumes-claims' },
      { label: 'Resizing an in-use PersistentVolumeClaim', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/#resizing-an-in-use-persistentvolumeclaim' },
    ],
  },
  {
    id: 'storage-pvc-protection',
    title: 'PVC Protection Finalizers',
    category: 'storage',
    subcategory: 'volumes-claims',
    desc: 'You run kubectl delete pvc and the claim sits in Terminating, so what is holding it? The pvc-protection finalizer, added at creation: while a Pod still mounts the claim the deletionTimestamp is set but the delete never completes, because pulling storage from a running Pod would break it. Only kubectl prints Terminating, the phase stays Bound the whole time, and only the last consuming Pod leaving frees it. The fix is finding that Pod.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Storage Object in Use Protection', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/#storage-object-in-use-protection' },
      { label: 'Finalizers', href: 'https://kubernetes.io/docs/concepts/overview/working-with-objects/finalizers/' },
    ],
  },
  {
    id: 'storage-reclaim-policy',
    title: 'Reclaim Policy',
    category: 'storage',
    subcategory: 'volumes-claims',
    desc: 'You delete a PVC, so does the disk full of data go with it? One field on the PV decides, inherited from the StorageClass, which defaults to Delete for anything dynamically provisioned. Under Delete the controller calls DeleteVolume, wipes the backing disk and removes the PV object, so the data is gone for good. Under Retain nothing is touched, but the volume parks in Released with a stale claimRef that only an administrator can clear by hand.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Reclaiming', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/#reclaiming' },
      { label: 'Retain', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/#retain' },
    ],
  },
  {
    id: 'storage-pv-lifecycle-phases',
    title: 'PV Phase Machine',
    category: 'storage',
    subcategory: 'volumes-claims',
    desc: 'What does the phase of a PersistentVolume track, and what moves it from one to the next? A fresh volume is Available, binding a claim flips it to Bound, and deleting that claim sends it to Released rather than back, because the claimRef stays behind and goes stale. From there the reclaim policy decides the ending, and only one edge leads back, cleared by hand. A failed Delete parks it in Failed, where automatic cleanup gives up and a person takes over.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Lifecycle of a Volume and Claim', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/#lifecycle-of-a-volume-and-claim' },
      { label: 'Phase', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/#phase' },
    ],
  },
  {
    id: 'storage-csi-architecture',
    title: 'CSI Architecture',
    category: 'storage',
    subcategory: 'csi-mount-path',
    desc: 'Kubernetes core has no code for any storage vendor, so how does an EBS or Ceph disk get mounted? A CSI driver ships in two halves: the controller plugin runs as a Deployment or StatefulSet whose sidecars each watch one kind of object and turn it into one gRPC call, and the node plugin is a DaemonSet that registers with Kubelet. Only the node plugin ever mounts the volume on the Node. The sidecars bridge those objects to a vendor that core never knew.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'CSI Volumes', href: 'https://kubernetes.io/docs/concepts/storage/volumes/#csi' },
      { label: 'Sidecar Containers', href: 'https://kubernetes-csi.github.io/docs/sidecar-containers.html' },
      { label: 'Storage Concepts', href: 'https://kubernetes.io/docs/concepts/storage/' },
    ],
  },
  {
    id: 'storage-csi-attach-mount',
    title: 'Attach and Mount Chain',
    category: 'storage',
    subcategory: 'csi-mount-path',
    desc: 'A new claim is not a mounted disk, so what happens between the two? Four gRPC calls run in order: CreateVolume makes the disk exist, ControllerPublishVolume attaches it to the Node, NodeStageVolume formats it only if it is still blank and mounts it once at a global staging path, and NodePublishVolume bind-mounts that into the Pod. Stage runs once per Node, publish once per Pod, which is how Pods on one Node share a single disk.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'CSI Volumes', href: 'https://kubernetes.io/docs/concepts/storage/volumes/#csi' },
      { label: 'CSI Specification', href: 'https://github.com/container-storage-interface/spec/blob/master/spec.md' },
      { label: 'Persistent Volumes', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/' },
    ],
  },
  {
    id: 'storage-volumeattachment',
    title: 'VolumeAttachment',
    category: 'storage',
    subcategory: 'csi-mount-path',
    desc: 'What is the cluster record that a disk is attached to a Node, and who writes it? Not the Pod and not Kubelet: the attach-detach controller decides a volume must be attached and writes a VolumeAttachment object. The external-attacher watches those, calls ControllerPublishVolume, and sets status.attached true, and only then does Kubelet mount. Deleting that object, not the Pod, is what triggers the detach, which is why a slot stays taken until it is gone.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'VolumeAttachment API', href: 'https://kubernetes.io/docs/reference/kubernetes-api/storage/volume-attachment-v1/' },
      { label: 'Persistent Volumes', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/' },
    ],
  },
  {
    id: 'storage-mount-path-chain',
    title: 'Where the Bytes Land',
    category: 'storage',
    subcategory: 'csi-mount-path',
    desc: 'A container writes to /data, but where do the bytes actually go on the Node? The path is a short chain of mounts: the raw device is mounted once at a global staging path, that staged filesystem is bind-mounted into each Pod private directory, and the runtime maps that to /data. Two Pods on one Node get two bind mounts onto one staged device, never a second attach. A write passes through both mounts onto the one disk.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'CSI Volumes', href: 'https://kubernetes.io/docs/concepts/storage/volumes/#csi' },
      { label: 'CSI Specification', href: 'https://github.com/container-storage-interface/spec/blob/master/spec.md' },
      { label: 'Persistent Volumes', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/' },
    ],
  },
  {
    id: 'storage-fsgroup-ownership',
    title: 'fsGroup and Volume Ownership',
    category: 'storage',
    subcategory: 'csi-mount-path',
    desc: 'A freshly mounted volume is owned by root, so why can a non-root container not write to it? The securityContext.fsGroup field names a GID, and Kubelet chowns the whole volume tree to that group before the container starts. That walk is cheap on a small volume but adds minutes on one with millions of files, which is what fsGroupChangePolicy OnRootMismatch exists to skip. The default walks the whole tree every start.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Security Context', href: 'https://kubernetes.io/docs/tasks/configure-pod-container/security-context/' },
      { label: 'Volume Permission and Ownership Change Policy', href: 'https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods' },
    ],
  },
  {
    id: 'storage-volume-attach-limits',
    title: 'Node Volume Attach Limits',
    category: 'storage',
    subcategory: 'csi-mount-path',
    desc: 'Why does a Pod stay Pending on max volume count while every Node has spare CPU and memory? Because a Node has a second, invisible capacity: how many volumes one CSI driver may have attached at once. The node plugin reports it, Kubelet writes it into CSINode, and the scheduler rejects any Node at its ceiling. A slot frees when the detach completes, not when the Pod dies, turning a rollout near the ceiling into a race.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'CSINode API', href: 'https://kubernetes.io/docs/reference/kubernetes-api/storage/csi-node-v1/' },
      { label: 'Node-specific Volume Limits', href: 'https://kubernetes.io/docs/concepts/storage/storage-limits/' },
    ],
  },
  {
    id: 'storage-multi-attach-error',
    title: 'Multi-Attach Error',
    category: 'storage',
    subcategory: 'csi-mount-path',
    desc: 'Why does a Pod hang in ContainerCreating with a Multi-Attach error for its volume? An RWO disk attaches to one Node at a time, and RollingUpdate stands the replacement up on a new Node while the old Pod still holds the attachment. Nothing is broken: the controller will not write a second VolumeAttachment and the rollout will not delete the old Pod, so each waits on the other. Recreate breaks it by deleting first.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Access Modes', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes' },
      { label: 'Deployment Strategy', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy' },
    ],
  },
  {
    id: 'storage-volume-detach-on-node-loss',
    title: 'Detach on Node Failure',
    category: 'storage',
    subcategory: 'csi-mount-path',
    desc: 'When a Node goes NotReady, why does its volume not move to a healthy Node right away? Nothing is contending for it, so the wait is on doubt rather than on a rival claim: the old Pod cannot be confirmed dead, and detaching a disk it might still be writing to risks corruption. Kubernetes rides out the eviction timeout and then the force-detach timeout, which is a safety property. Those two clocks are the outage, and the out-of-service taint skips them.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Non-graceful Node Shutdown', href: 'https://kubernetes.io/docs/concepts/cluster-administration/node-shutdown/#non-graceful-node-shutdown' },
      { label: 'Persistent Volumes', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/' },
    ],
  },
  {
    id: 'storage-volumeclaimtemplates',
    title: 'StatefulSet volumeClaimTemplates',
    category: 'storage',
    subcategory: 'stateful-data',
    desc: 'Why does every replica of a StatefulSet get its own disk while a Deployment shares one? The volumeClaimTemplate stamps out one PersistentVolumeClaim per ordinal with a deterministic name like data-web-0 rather than a random one. Because that name comes from the Pod identity, a Pod recreated even on another Node rebinds the same claim and the same data. Scaling down leaves them behind, since Retain is the default.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Volume Claim Templates', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#volume-claim-templates' },
      { label: 'Stable Storage', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-storage' },
    ],
  },
  {
    id: 'storage-pvc-retention-policy',
    title: 'StatefulSet PVC Retention',
    category: 'storage',
    subcategory: 'stateful-data',
    desc: 'When a StatefulSet shrinks or is deleted, what happens to the disks it leaves behind? The persistentVolumeClaimRetentionPolicy answers with two independent knobs, whenScaled for a replica scaled away and whenDeleted for the whole set, each Retain or Delete. Retain on both is the historical default, safe but silently leaking a disk on every scale-down nobody cleans up. Delete reclaims it, at the cost of the data, and the policy lives on the set rather than the claim.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'PVC Retention Policy', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#persistentvolumeclaim-retention' },
    ],
  },
  {
    id: 'storage-topology-aware-provisioning',
    title: 'WaitForFirstConsumer',
    category: 'storage',
    subcategory: 'stateful-data',
    desc: 'Why can a Pod hang forever in a multi-zone cluster with a healthy disk sitting right there? With volumeBindingMode Immediate the volume is provisioned the instant the claim exists, in whatever zone the provisioner picks, and the Pod is stuck if no Node then both fits it and lies in that zone. WaitForFirstConsumer inverts the order so the scheduler chooses the Node first. That failure is the commonest multi-zone bug, and this is its one-line fix.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Volume Binding Mode', href: 'https://kubernetes.io/docs/concepts/storage/storage-classes/#volume-binding-mode' },
      { label: 'Allowed Topologies', href: 'https://kubernetes.io/docs/concepts/storage/storage-classes/#allowed-topologies' },
    ],
  },
  {
    id: 'storage-csi-capacity-tracking',
    title: 'CSI Storage Capacity',
    category: 'storage',
    subcategory: 'stateful-data',
    desc: 'Why does a Pod get stuck Pending when the local storage pool on its chosen Node is full? Without capacity information the scheduler picks that Node on cpu and memory alone, provisioning fails there, and the Node choice is reset so the Pod is placed blind again on the next pass. CSIStorageCapacity objects from a driver that opts in let the scheduler see free space per Node and filter first, on classes that bind WaitForFirstConsumer.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Storage Capacity', href: 'https://kubernetes.io/docs/concepts/storage/storage-capacity/' },
      { label: 'CSIStorageCapacity API', href: 'https://kubernetes.io/docs/concepts/storage/storage-capacity/#api' },
    ],
  },
  {
    id: 'storage-volume-snapshot',
    title: 'Volume Snapshots',
    category: 'storage',
    subcategory: 'stateful-data',
    desc: 'How do you capture a point-in-time copy of a live volume, and why is that copy not a backup? A VolumeSnapshot is the namespaced request and a VolumeSnapshotClass names the driver, and the controller creates a cluster-scoped VolumeSnapshotContent that binds exactly as a PV binds to a PVC. All three are CRDs rather than core API, installed with the snapshot controller. The copy sits in the same storage system as the original, so both die together.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Volume Snapshots', href: 'https://kubernetes.io/docs/concepts/storage/volume-snapshots/' },
      { label: 'VolumeSnapshotClasses', href: 'https://kubernetes.io/docs/concepts/storage/volume-snapshot-classes/' },
      { label: 'Snapshot Controller', href: 'https://kubernetes-csi.github.io/docs/snapshot-controller.html' },
      { label: 'CSI external-snapshotter', href: 'https://kubernetes-csi.github.io/docs/external-snapshotter.html' },
    ],
  },
  {
    id: 'storage-pvc-clone',
    title: 'Cloning a PVC',
    category: 'storage',
    subcategory: 'stateful-data',
    desc: 'Need an independent copy of a volume right now, without setting up a snapshot first? A clone is a new PVC whose dataSource points straight at an existing one, and the storage system makes an exact duplicate server-side with no snapshot object in between. The two claims must share a namespace and volumeMode, the new one must ask for at least the size of the source, and the source must be bound and not in use. The result has no shared lineage.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'CSI Volume Cloning', href: 'https://kubernetes.io/docs/concepts/storage/volume-pvc-datasource/' },
      { label: 'Provisioning', href: 'https://kubernetes.io/docs/concepts/storage/volume-pvc-datasource/#provisioning' },
    ],
  },
  {
    id: 'storage-generic-ephemeral-volume',
    title: 'Generic Ephemeral Volumes',
    category: 'storage',
    subcategory: 'stateful-data',
    desc: 'What if you want scratch space that behaves like emptyDir but can be large and on a real StorageClass? A generic ephemeral volume is an inline volumeClaimTemplate written on the Pod, and it gets a real PVC, real dynamic provisioning and a real CSI mount. Its lifetime is still the Pod: the PVC carries an ownerReference and is collected when the Pod goes, taking the disk with it unless the class says Retain. It bridges scratch and the real machinery.',
    k8sVersion: '1.35',
    tinted: true,
    sources: [
      { label: 'Generic Ephemeral Volumes', href: 'https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#generic-ephemeral-volumes' },
      { label: 'Ephemeral Volumes', href: 'https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/' },
    ],
  },
];
