const ICON_NETWORK   = `<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="6" cy="6" r="2.5"/><circle cx="18" cy="6" r="2.5"/><circle cx="6" cy="18" r="2.5"/><circle cx="18" cy="18" r="2.5"/><line x1="8.5" y1="6" x2="15.5" y2="6"/><line x1="6" y1="8.5" x2="6" y2="15.5"/><line x1="8.5" y1="18" x2="15.5" y2="18"/><line x1="18" y1="8.5" x2="18" y2="15.5"/></svg>`;
const ICON_WORKLOADS = `<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polygon points="12 3 21 8 12 13 3 8 12 3"/><polyline points="3 13 12 18 21 13"/></svg>`;
const ICON_STORAGE   = `<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><ellipse cx="12" cy="5" rx="8" ry="2.5"/><path d="M4 5v6c0 1.4 3.6 2.5 8 2.5s8-1.1 8-2.5V5"/><path d="M4 11v8c0 1.4 3.6 2.5 8 2.5s8-1.1 8-2.5v-8"/></svg>`;
const ICON_CONTROL   = `<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="4" y="4" width="16" height="16" rx="2"/><rect x="9" y="9" width="6" height="6"/><line x1="9" y1="2" x2="9" y2="4"/><line x1="15" y1="2" x2="15" y2="4"/><line x1="9" y1="20" x2="9" y2="22"/><line x1="15" y1="20" x2="15" y2="22"/><line x1="20" y1="9" x2="22" y2="9"/><line x1="20" y1="15" x2="22" y2="15"/><line x1="2" y1="9" x2="4" y2="9"/><line x1="2" y1="15" x2="4" y2="15"/></svg>`;
const ICON_SCALING   = `<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polyline points="3 17 9 11 13 15 21 7"/><polyline points="14 7 21 7 21 14"/></svg>`;
const ICON_SECURITY  = `<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 2 4 6v6c0 5 3.4 8.7 8 10 4.6-1.3 8-5 8-10V6l-8-4z"/></svg>`;

export const CATEGORIES = [
  { key: 'all',       label: 'All' },
  { key: 'control',   label: 'Cluster',       sub: 'Cluster internals',   icon: ICON_CONTROL },
  { key: 'workloads', label: 'Workloads',     sub: 'Pods and controllers', icon: ICON_WORKLOADS },
  { key: 'network',   label: 'Networking',    sub: 'Traffic flow',        icon: ICON_NETWORK },
  { key: 'storage',   label: 'Storage',       sub: 'Volume flow',         icon: ICON_STORAGE },
  { key: 'scaling',   label: 'Scaling',       sub: 'Autoscale flow',      icon: ICON_SCALING },
  { key: 'security',  label: 'Security',      sub: 'Policy flow',         icon: ICON_SECURITY },
];

export const CATEGORY_ICONS = {
  network:   ICON_NETWORK,
  workloads: ICON_WORKLOADS,
  storage:   ICON_STORAGE,
  control:   ICON_CONTROL,
  scaling:   ICON_SCALING,
  security:  ICON_SECURITY,
};

export const CATEGORY_SUB = {
  network:   'Traffic flow',
  workloads: 'Pods and controllers',
  storage:   'Volume flow',
  control:   'Cluster internals',
  scaling:   'Autoscale flow',
  security:  'Policy flow',
};

export const SCHEMES = [
  {
    id: 'network-pod-to-pod-same-node',
    title: 'Pod-to-Pod (same node)',
    category: 'network',
    desc: 'How a packet travels from Pod A to Pod B on the same node via the CNI bridge and veth pairs.',
    k8sVersion: '1.32',
    module: './schemes/network-pod-to-pod-same-node.js',
    sources: [
      { label: 'K8s docs: Networking', href: 'https://kubernetes.io/docs/concepts/cluster-administration/networking/' },
    ],
  },
  {
    id: 'service-cluster-ip',
    title: 'Service: ClusterIP routing',
    category: 'network',
    desc: 'Selector matches Pods to Endpoints, kube-proxy installs DNAT rules so traffic to ClusterIP lands on a backing Pod.',
    k8sVersion: '1.32',
    module: './schemes/service-cluster-ip.js',
    sources: [
      { label: 'K8s docs: Service', href: 'https://kubernetes.io/docs/concepts/services-networking/service/' },
    ],
  },
  {
    id: 'workloads-rolling-update',
    title: 'Deployment Rolling Update',
    category: 'workloads',
    subcategory: 'controllers',
    desc: 'How do you move every Pod to a new version without taking the app offline? A Deployment rolls the change out gradually, bringing up Pods on the new version a few at a time and retiring the old ones only once the replacements are healthy, so the Service always keeps enough backends serving traffic. If the new version misbehaves, the same machinery rolls it back just as smoothly.',
    k8sVersion: '1.32',
    module: './schemes/workloads-rolling-update.js',
    tinted: true,
    sources: [
      { label: 'K8s docs: Deployments', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/deployment/' },
    ],
  },
  {
    id: 'workloads-deployment-rollback',
    title: 'Deployment Rollback and Revision History',
    category: 'workloads',
    subcategory: 'controllers',
    desc: 'A rollout went bad, how do you get back to the version that worked? A Deployment keeps its old ReplicaSets around as numbered revisions, so a rollback is just scaling the previous one back up while the broken one is scaled to zero. The same revision history is how a stuck rollout is detected and undone in a single command.',
    k8sVersion: '1.32',
    module: './schemes/workloads-deployment-rollback.js',
    tinted: true,
    sources: [
      { label: 'K8s docs: Rolling Back a Deployment', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#rolling-back-a-deployment' },
    ],
  },
  {
    id: 'volume-pvc-binding',
    title: 'PVC → PV binding',
    category: 'storage',
    desc: 'A PersistentVolumeClaim asks for storage, provisioner creates a PV, the binding controller pairs them, and kubelet mounts.',
    k8sVersion: '1.32',
    module: './schemes/volume-pvc-binding.js',
    sources: [
      { label: 'K8s docs: Persistent Volumes', href: 'https://kubernetes.io/docs/concepts/storage/persistent-volumes/' },
    ],
  },
  {
    id: 'control-plane-architecture',
    title: 'Control Plane Architecture',
    category: 'control',
    subcategory: 'control-plane',
    desc: 'Where each control-plane component lives and how they connect. ApiServer is the sole gateway, ETCD the only durable store, controllers, scheduler and kubelet all talk through ApiServer.',
    k8sVersion: '1.32',
    module: './schemes/control-plane-architecture.js',
    sources: [
      { label: 'K8s docs: Components', href: 'https://kubernetes.io/docs/concepts/overview/components/' },
      { label: 'K8s docs: Architecture', href: 'https://kubernetes.io/docs/concepts/architecture/' },
    ],
  },
  {
    id: 'control-etcd-raft',
    title: 'ETCD Raft Consensus',
    category: 'control',
    subcategory: 'control-plane',
    desc: 'Leader takes writes, replicates via AppendEntries RPC, commits when quorum acks (2 of 3), then broadcasts commitIndex so Followers apply.',
    k8sVersion: '1.32',
    module: './schemes/control-etcd-raft.js',
    sources: [
      { label: 'Raft algorithm', href: 'https://raft.github.io/' },
      { label: 'Raft paper', href: 'https://raft.github.io/raft.pdf' },
    ],
  },
  {
    id: 'control-leader-election',
    title: 'Leader Election via Lease',
    category: 'control',
    subcategory: 'control-plane',
    desc: 'Replicas race to PUT a Lease with CAS, winner renews via renewTime to hold leadership, on crash the Lease expires and a standby CAS-acquires it. leaseTransitions ticks on every handover.',
    k8sVersion: '1.32',
    module: './schemes/control-leader-election.js',
    sources: [
      { label: 'K8s docs: Leases', href: 'https://kubernetes.io/docs/concepts/architecture/leases/' },
      { label: 'K8s API: Lease v1', href: 'https://kubernetes.io/docs/reference/kubernetes-api/cluster-resources/lease-v1/' },
    ],
  },
  {
    id: 'control-scheduler-decision',
    title: 'Scheduler Decision Cycle',
    category: 'control',
    subcategory: 'control-plane',
    desc: 'Queue, filter (drop failing predicates), score (rank survivors 0 to 100), bind (POST .../pods/{name}/binding). Filter and score run as plugins on the Scheduling Framework.',
    k8sVersion: '1.32',
    module: './schemes/control-scheduler-decision.js',
    sources: [
      { label: 'K8s docs: kube-scheduler', href: 'https://kubernetes.io/docs/concepts/scheduling-eviction/kube-scheduler/' },
      { label: 'K8s docs: Scheduling Framework', href: 'https://kubernetes.io/docs/concepts/scheduling-eviction/scheduling-framework/' },
    ],
  },
  {
    id: 'control-admission-webhooks',
    title: 'Admission Chain',
    category: 'control',
    subcategory: 'control-plane',
    desc: 'Six stages before the etcd write: authn, authz, mutating webhooks, schema, validating webhooks, persist. Webhook stages let policy tools (Kyverno, OPA Gatekeeper, sidecar injectors) plug in via Configuration objects.',
    k8sVersion: '1.32',
    module: './schemes/control-admission-webhooks.js',
    sources: [
      { label: 'K8s docs: Admission Controllers', href: 'https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/' },
    ],
  },
  {
    id: 'control-api-structure',
    title: 'List-Watch and Informers',
    category: 'control',
    subcategory: 'control-plane',
    desc: 'Groups, versions, resources. Clients list-then-watch, informers turn the stream into a local cache that controllers reconcile against.',
    k8sVersion: '1.32',
    module: './schemes/control-api-structure.js',
    sources: [
      { label: 'K8s docs: API concepts', href: 'https://kubernetes.io/docs/reference/using-api/api-concepts/' },
      { label: 'K8s docs: Kubernetes API', href: 'https://kubernetes.io/docs/concepts/overview/kubernetes-api/' },
    ],
  },
  {
    id: 'control-plane-apply-flow',
    title: 'Kubectl Apply Flow',
    category: 'control',
    subcategory: 'control-plane',
    desc: 'A single kubectl apply: client → ApiServer → ETCD → ControllerManager → Scheduler → Kubelet.',
    k8sVersion: '1.32',
    module: './schemes/control-plane-apply-flow.js',
    sources: [
      { label: 'K8s docs: Architecture', href: 'https://kubernetes.io/docs/concepts/architecture/' },
    ],
  },
  {
    id: 'control-plane-delete-flow',
    title: 'Kubectl Delete Flow',
    category: 'control',
    subcategory: 'control-plane',
    desc: 'ApiServer marks deletionTimestamp in ETCD, GarbageCollector cascades through ownerReferences, finalizers gate the actual purge.',
    k8sVersion: '1.32',
    module: './schemes/control-plane-delete-flow.js',
    sources: [
      { label: 'K8s docs: Garbage Collection', href: 'https://kubernetes.io/docs/concepts/architecture/garbage-collection/' },
      { label: 'K8s docs: Owners and Dependents', href: 'https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/' },
      { label: 'K8s docs: Finalizers', href: 'https://kubernetes.io/docs/concepts/overview/working-with-objects/finalizers/' },
    ],
  },
  {
    id: 'lifecycle-node-drain',
    title: 'Node Drain',
    category: 'control',
    subcategory: 'worker-nodes',
    desc: 'PATCH spec.unschedulable=true cordons the node, then the policy/v1 Eviction API is called per Pod with PodDisruptionBudget gating each request. A blocked eviction returns 429 and kubectl retries until currentHealthy recovers. DaemonSet, mirror and emptyDir Pods need their own flags.',
    k8sVersion: '1.32',
    module: './schemes/lifecycle-node-drain.js',
    sources: [
      { label: 'K8s docs: Safely Drain a Node', href: 'https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/' },
      { label: 'K8s docs: Eviction API', href: 'https://kubernetes.io/docs/concepts/scheduling-eviction/api-eviction/' },
      { label: 'K8s docs: PodDisruptionBudget', href: 'https://kubernetes.io/docs/concepts/workloads/pods/disruptions/' },
    ],
  },
  {
    id: 'control-kubelet-sync-loop',
    title: 'Kubelet Reconcile Loop',
    category: 'control',
    subcategory: 'worker-nodes',
    desc: 'Watch ApiServer, PLEG observes containers via ListContainers, SyncPod compares desired vs observed, CRI Create/Start calls, status PATCHed back. Loop runs continuously, driven by API events and periodic relist.',
    k8sVersion: '1.32',
    module: './schemes/control-kubelet-sync-loop.js',
    sources: [
      { label: 'K8s docs: Kubelet', href: 'https://kubernetes.io/docs/concepts/overview/components/#kubelet' },
      { label: 'K8s blog: Kubelet PLEG', href: 'https://developers.redhat.com/blog/2019/11/13/pod-lifecycle-event-generator-understanding-the-pleg-is-not-healthy-issue-in-kubernetes' },
    ],
  },
  {
    id: 'control-node-pressure-eviction',
    title: 'Node-pressure Eviction',
    category: 'control',
    subcategory: 'worker-nodes',
    desc: 'cAdvisor reports usage, eviction manager compares against --eviction-hard thresholds, MemoryPressure or DiskPressure is set, Pods ranked by QoS class (BestEffort first), kubelet terminates victims until pressure clears. Different from taint-based eviction on node failure (Node Failure card).',
    k8sVersion: '1.32',
    module: './schemes/control-node-pressure-eviction.js',
    sources: [
      { label: 'K8s docs: Node-pressure Eviction', href: 'https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/' },
      { label: 'K8s docs: Pod QoS Classes', href: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-qos/' },
    ],
  },
  {
    id: 'control-graceful-node-shutdown',
    title: 'Graceful Node Shutdown',
    category: 'control',
    subcategory: 'worker-nodes',
    desc: 'Kubelet holds a systemd inhibitor lock. On PrepareForShutdown (D-Bus) it rejects new Pods, SIGTERMs non-critical Pods within shutdownGracePeriod minus shutdownGracePeriodCriticalPods, then critical Pods within shutdownGracePeriodCriticalPods, releases the lock. Local cleanup, no API-driven drain.',
    k8sVersion: '1.32',
    module: './schemes/control-graceful-node-shutdown.js',
    sources: [
      { label: 'K8s docs: Graceful node shutdown', href: 'https://kubernetes.io/docs/concepts/cluster-administration/node-shutdown/' },
      { label: 'KEP-2000: Graceful Node Shutdown', href: 'https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2000-graceful-node-shutdown' },
    ],
  },
  {
    id: 'control-node-failure',
    title: 'Node Failure and Eviction',
    category: 'control',
    subcategory: 'worker-nodes',
    desc: 'Kubelet renews the Lease every 10s and PATCHes Node.status every 5 min, until heartbeats stop. Lease stale, Ready=Unknown after --node-monitor-grace-period, NoExecute taint applied, toleration expires, Pod evicted and rescheduled. Default MTTR ≈ 40s + 300s.',
    k8sVersion: '1.32',
    module: './schemes/control-node-failure.js',
    sources: [
      { label: 'K8s docs: Node status', href: 'https://kubernetes.io/docs/concepts/architecture/nodes/#node-status' },
      { label: 'K8s docs: Node taints', href: 'https://kubernetes.io/docs/reference/labels-annotations-taints/#node-kubernetes-io-unreachable' },
      { label: 'K8s docs: Taint-based Evictions', href: 'https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-based-evictions' },
    ],
  },
  {
    id: 'control-pod-sandbox-cri',
    title: 'Pod Sandbox via CRI',
    category: 'control',
    subcategory: 'worker-nodes',
    desc: 'RunPodSandbox creates a pause container with shared namespaces, CNI plugin attaches the network, PullImage fetches each image, CreateContainer plus StartContainer launch the workload containers in the sandbox.',
    k8sVersion: '1.32',
    module: './schemes/control-pod-sandbox-cri.js',
    sources: [
      { label: 'CRI spec', href: 'https://github.com/kubernetes/cri-api/blob/master/pkg/apis/runtime/v1/api.proto' },
      { label: 'K8s docs: Container Runtimes', href: 'https://kubernetes.io/docs/setup/production-environment/container-runtimes/' },
    ],
  },
  {
    id: 'control-oom-kill',
    title: 'Container OOMKill',
    category: 'control',
    subcategory: 'worker-nodes',
    desc: 'Container hits memory.max in its cgroup, the kernel cgroup OOM killer picks a process by oom_score_adj (set from QoS class), SIGKILL exits 137. Kubelet PATCHes lastState.terminated.reason=OOMKilled and restartPolicy decides next. Different from node-pressure eviction, where the kubelet proactively evicts by QoS. Here the kernel does the killing and the kubelet only witnesses.',
    k8sVersion: '1.32',
    module: './schemes/control-oom-kill.js',
    sources: [
      { label: 'K8s docs: Resource Management', href: 'https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/' },
      { label: 'K8s docs: Pod QoS Classes', href: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-qos/' },
    ],
  },
  {
    id: 'network-dns-coredns',
    title: 'DNS via CoreDNS',
    category: 'network',
    desc: 'Pod resolv.conf points at kube-dns, and the query lands on a CoreDNS pod where the plugin chain (cache, kubernetes) returns the Service ClusterIP.',
    k8sVersion: '1.32',
    module: './schemes/network-dns-coredns.js',
    sources: [
      { label: 'K8s docs: DNS for Services and Pods', href: 'https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/' },
    ],
  },
  {
    id: 'network-ingress-routing',
    title: 'Ingress controller routing',
    category: 'network',
    desc: 'External LB to Ingress controller pod, Host/path match against Ingress rules, then proxy to the backend Service and Pod.',
    k8sVersion: '1.32',
    module: './schemes/network-ingress-routing.js',
    sources: [
      { label: 'K8s docs: Ingress', href: 'https://kubernetes.io/docs/concepts/services-networking/ingress/' },
    ],
  },
  {
    id: 'network-kube-proxy-iptables',
    title: 'kube-proxy iptables chains',
    category: 'network',
    desc: 'Packet to a ClusterIP traverses KUBE-SERVICES → KUBE-SVC-XXX (random pick by probability) → KUBE-SEP-YYY (DNAT) before egress.',
    k8sVersion: '1.32',
    module: './schemes/network-kube-proxy-iptables.js',
    sources: [
      { label: 'K8s docs: kube-proxy', href: 'https://kubernetes.io/docs/reference/networking/virtual-ips/' },
    ],
  },
  {
    id: 'scaling-hpa-cycle',
    title: 'HPA scale-up cycle',
    category: 'scaling',
    desc: 'metrics-server feeds HPA controller, which computes desired replicas with a stabilization window and PATCHes the Deployment scale subresource.',
    k8sVersion: '1.32',
    module: './schemes/scaling-hpa-cycle.js',
    sources: [
      { label: 'K8s docs: Horizontal Pod Autoscaling', href: 'https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/' },
    ],
  },
  {
    id: 'workloads-replicaset',
    title: 'ReplicaSet Reconcile and Ownership',
    category: 'workloads',
    subcategory: 'controllers',
    desc: 'How does Kubernetes keep exactly the right number of identical Pods alive? A ReplicaSet runs a control loop that constantly compares how many Pods it should have against how many it can see, creating or deleting Pods until the two match. It owns those Pods through ownerReferences, adopts any stray Pod whose labels match its selector, and lets go of one whose labels change.',
    k8sVersion: '1.32',
    module: './schemes/workloads-replicaset.js',
    tinted: true,
    sources: [
      { label: 'K8s docs: ReplicaSet', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/' },
      { label: 'K8s docs: Owners and Dependents', href: 'https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/' },
    ],
  },
  {
    id: 'workloads-statefulset-ordered-startup',
    title: 'StatefulSet Ordered Rollout',
    category: 'workloads',
    subcategory: 'controllers',
    desc: 'Some workloads care about the order their Pods come up in. A StatefulSet starts its Pods one at a time in a fixed sequence, waiting for each to become ready before creating the next, and gives every Pod a stable name and its own storage that follow it across restarts. When it scales down, it tears the Pods down in reverse, newest first.',
    k8sVersion: '1.32',
    module: './schemes/workloads-statefulset-ordered-startup.js',
    tinted: true,
    sources: [
      { label: 'K8s docs: StatefulSets', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/' },
    ],
  },
  {
    id: 'security-rbac-authorization',
    title: 'RBAC authorization',
    category: 'security',
    desc: 'Request → SubjectAccessReview walks RoleBindings + ClusterRoleBindings, the first matching rule decides, and the decision is audit-logged.',
    k8sVersion: '1.32',
    module: './schemes/security-rbac-authorization.js',
    sources: [
      { label: 'K8s docs: RBAC Authorization', href: 'https://kubernetes.io/docs/reference/access-authn-authz/rbac/' },
    ],
  },
  {
    id: 'security-networkpolicy-enforcement',
    title: 'NetworkPolicy enforcement',
    category: 'security',
    desc: 'CNI plugin compiles ingress/egress policies into per-Pod iptables or eBPF rules. Allowed sources pass, and everything else falls into default-deny.',
    k8sVersion: '1.32',
    module: './schemes/security-networkpolicy-enforcement.js',
    sources: [
      { label: 'K8s docs: Network Policies', href: 'https://kubernetes.io/docs/concepts/services-networking/network-policies/' },
    ],
  },
  {
    id: 'storage-csi-attach-mount',
    title: 'CSI attach and mount',
    category: 'storage',
    desc: 'external-attacher (ControllerPublish) gets the cloud disk to the node, then csi-node-driver does NodeStage and NodePublish to bind-mount into the Pod namespace.',
    k8sVersion: '1.32',
    module: './schemes/storage-csi-attach-mount.js',
    sources: [
      { label: 'CSI spec', href: 'https://github.com/container-storage-interface/spec/blob/master/spec.md' },
    ],
  },
  {
    id: 'workloads-init-containers-and-sidecars',
    title: 'Init Containers and Native Sidecars',
    category: 'workloads',
    subcategory: 'pods-bootstrap',
    desc: 'Init containers run strictly sequentially, each must exit 0 before the next starts. A native sidecar (initContainer with restartPolicy=Always, GA in 1.29) runs for the full Pod lifetime and gates main until it reports Started, termination reverses the order.',
    k8sVersion: '1.32',
    module: './schemes/workloads-init-containers-and-sidecars.js',
    tinted: true,
    sources: [
      { label: 'K8s docs: Sidecar Containers', href: 'https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/' },
    ],
  },
  {
    id: 'workloads-pod-image-pull',
    title: 'Image Pull and Registry Auth',
    category: 'workloads',
    subcategory: 'pods-bootstrap',
    desc: 'imagePullPolicy resolves (Always for :latest, IfNotPresent otherwise, Never for preloaded). imagePullSecrets gate the registry call, missing layers are pulled by sha256 digest into the local store, overlay rootfs is stacked. Failures surface as ErrImagePull or ImagePullBackOff on exponential backoff.',
    k8sVersion: '1.32',
    module: './schemes/workloads-pod-image-pull.js',
    tinted: true,
    sources: [
      { label: 'K8s docs: Images', href: 'https://kubernetes.io/docs/concepts/containers/images/' },
      { label: 'K8s docs: ImagePullSecrets', href: 'https://kubernetes.io/docs/concepts/configuration/secret/#using-imagepullsecrets' },
      { label: 'OCI Distribution Spec', href: 'https://github.com/opencontainers/distribution-spec' },
    ],
  },
  {
    id: 'workloads-pod-qos-classes',
    title: 'Pod QoS Classes',
    category: 'workloads',
    subcategory: 'pods-bootstrap',
    desc: 'BestEffort, Burstable or Guaranteed, derived at admission from requests vs limits. Drives kubelet cgroup limits, oom_score_adj and node-pressure eviction order. Status field, immutable for the Pod life.',
    k8sVersion: '1.32',
    module: './schemes/workloads-pod-qos-classes.js',
    tinted: true,
    sources: [
      { label: 'K8s docs: Pod QoS Classes', href: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-qos/' },
      { label: 'K8s docs: Resource Management', href: 'https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/' },
      { label: 'K8s docs: Node-pressure Eviction', href: 'https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/' },
    ],
  },
  {
    id: 'workloads-pod-priority-preemption',
    title: 'Pod Priority and Preemption',
    category: 'workloads',
    subcategory: 'pods-bootstrap',
    desc: 'priorityClassName resolves to a numeric value. On NoFit the scheduler preempts the smallest lower-priority victim set via standard DELETE (no PDB check, unlike eviction), then binds once capacity returns.',
    k8sVersion: '1.32',
    module: './schemes/workloads-pod-priority-preemption.js',
    tinted: true,
    sources: [
      { label: 'K8s docs: Priority and Preemption', href: 'https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/' },
      { label: 'K8s docs: PriorityClass', href: 'https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.32/#priorityclass-v1-scheduling-k8s-io' },
    ],
  },
  {
    id: 'scaling-cluster-autoscaler',
    title: 'Cluster Autoscaler adds a node',
    category: 'scaling',
    desc: 'Pending pod (Unschedulable) is the trigger. CA simulates the fit, calls cloud API to scale up the node group, kubelet on the new node registers, scheduler binds.',
    k8sVersion: '1.32',
    module: './schemes/scaling-cluster-autoscaler.js',
    sources: [
      { label: 'Cluster Autoscaler FAQ', href: 'https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md' },
    ],
  },
  {
    id: 'network-pod-to-pod-cross-node',
    title: 'Pod-to-Pod across nodes',
    category: 'network',
    desc: 'cni0 has no FDB entry for the remote Pod, so the CNI plugin wraps the frame in VXLAN/UDP. Node-2\'s kernel decapsulates and delivers via local cni0.',
    k8sVersion: '1.32',
    module: './schemes/network-pod-to-pod-cross-node.js',
    sources: [
      { label: 'K8s docs: Cluster Networking', href: 'https://kubernetes.io/docs/concepts/cluster-administration/networking/' },
    ],
  },
  {
    id: 'network-externaltrafficpolicy',
    title: 'ExternalTrafficPolicy: Cluster vs Local',
    category: 'network',
    desc: 'Cluster mode forwards via SNAT (extra hop, src IP lost). Local mode preserves src IP but drops if no local backend pod is on the node hit by the LB.',
    k8sVersion: '1.32',
    module: './schemes/network-externaltrafficpolicy.js',
    sources: [
      { label: 'K8s docs: ExternalTrafficPolicy', href: 'https://kubernetes.io/docs/reference/networking/virtual-ips/#external-traffic-policy' },
    ],
  },
  {
    id: 'storage-volume-snapshot',
    title: 'VolumeSnapshot lifecycle',
    category: 'storage',
    desc: 'VolumeSnapshot CR triggers external-snapshotter, which calls driver CreateSnapshot. VolumeSnapshotContent binds, readyToUse flips true, and new PVCs can dataSource it.',
    k8sVersion: '1.32',
    module: './schemes/storage-volume-snapshot.js',
    sources: [
      { label: 'K8s docs: Volume Snapshots', href: 'https://kubernetes.io/docs/concepts/storage/volume-snapshots/' },
    ],
  },
  {
    id: 'workloads-pvc-stickiness',
    title: 'StatefulSet PVC Stickiness',
    category: 'workloads',
    subcategory: 'controllers',
    desc: 'When a StatefulSet Pod moves to another node, does its data move with it? Yes. Each Pod owns a volume tied to its identity, and that volume outlives the Pod, so when a replacement with the same identity starts up, possibly on a different node, it reattaches the very same disk and sees exactly the data the previous Pod left behind.',
    k8sVersion: '1.32',
    module: './schemes/workloads-pvc-stickiness.js',
    tinted: true,
    sources: [
      { label: 'K8s docs: StatefulSet basics', href: 'https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/' },
    ],
  },
  {
    id: 'workloads-daemonset',
    title: 'DaemonSet Controller',
    category: 'workloads',
    subcategory: 'controllers',
    desc: 'How do you run a copy of the same Pod on every node, and exactly one? A DaemonSet watches the set of nodes and keeps one Pod on each that matches, adding a Pod when a node joins and removing it when a node leaves, so the Pod count tracks the cluster instead of a fixed number of replicas.',
    k8sVersion: '1.32',
    module: './schemes/workloads-daemonset.js',
    tinted: true,
    sources: [
      { label: 'K8s docs: DaemonSet', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/' },
    ],
  },
  {
    id: 'workloads-job-parallelism',
    title: 'Job Parallelism and Completions',
    category: 'workloads',
    subcategory: 'controllers',
    desc: 'A Job runs a batch of work to completion instead of serving forever. You tell it how many successful runs you need in total and how many Pods may run at the same time, and it keeps launching Pods and retrying the ones that fail until that target is reached. Once enough runs have succeeded it stops on its own and marks the batch complete.',
    k8sVersion: '1.32',
    module: './schemes/workloads-job-parallelism.js',
    tinted: true,
    sources: [
      { label: 'K8s docs: Jobs', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/job/' },
    ],
  },
  {
    id: 'workloads-cronjob',
    title: 'CronJob Schedule and Concurrency',
    category: 'workloads',
    subcategory: 'controllers',
    desc: 'How do you run a Job on a repeating schedule instead of on demand? A CronJob holds a cron expression and, each time the clock matches, creates one Job from its template, which in turn runs a Pod. It also decides what to do when a run is still going at the next tick, prunes old finished Jobs so history does not pile up, and skips runs that were missed while the controller was down.',
    k8sVersion: '1.32',
    module: './schemes/workloads-cronjob.js',
    tinted: true,
    sources: [
      { label: 'K8s docs: CronJob', href: 'https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/' },
      { label: 'K8s docs: Running Automated Tasks with a CronJob', href: 'https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/' },
    ],
  },
  {
    id: 'storage-emptydir-vs-pv',
    title: 'emptyDir vs PV on reschedule',
    category: 'storage',
    desc: 'emptyDir tied to the Pod and its host tmpfs: gone on reschedule. PV outlives the Pod and reattaches on the new node, preserving data.',
    k8sVersion: '1.32',
    module: './schemes/storage-emptydir-vs-pv.js',
    sources: [
      { label: 'K8s docs: Volumes', href: 'https://kubernetes.io/docs/concepts/storage/volumes/' },
    ],
  },
  {
    id: 'scaling-vpa-recommend-vs-auto',
    title: 'VPA recommend vs auto',
    category: 'scaling',
    desc: 'recommender writes status.recommended from observed usage. In Auto mode the updater evicts pods, and the admission webhook injects new requests on the replacement.',
    k8sVersion: '1.32',
    module: './schemes/scaling-vpa-recommend-vs-auto.js',
    sources: [
      { label: 'VPA design', href: 'https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler' },
    ],
  },
  {
    id: 'scaling-pdb-during-eviction',
    title: 'PDB gates eviction',
    category: 'scaling',
    desc: 'Eviction API checks PodDisruptionBudget. If granting would breach minAvailable, the request returns 429 and drain has to wait for replacements to become Ready.',
    k8sVersion: '1.32',
    module: './schemes/scaling-pdb-during-eviction.js',
    sources: [
      { label: 'K8s docs: PodDisruptionBudget', href: 'https://kubernetes.io/docs/concepts/workloads/pods/disruptions/' },
    ],
  },
  {
    id: 'security-tls-bootstrap',
    title: 'Kubelet TLS bootstrap',
    category: 'security',
    desc: 'Kubelet uses a bootstrap token to POST a CSR. The csr-approver auto-approves, then csr-signer signs with the cluster CA. Kubelet stores the cert and rotates it before expiry.',
    k8sVersion: '1.32',
    module: './schemes/security-tls-bootstrap.js',
    sources: [
      { label: 'K8s docs: TLS Bootstrapping', href: 'https://kubernetes.io/docs/reference/access-authn-authz/kubelet-tls-bootstrapping/' },
    ],
  },
  {
    id: 'security-serviceaccount-token-projection',
    title: 'ServiceAccount token projection',
    category: 'security',
    desc: 'kubelet calls TokenRequest API per Pod for an audience-bound, expiring JWT. Token is written via atomic symlink swap into the Pod\'s projected volume and rotated before expiry.',
    k8sVersion: '1.32',
    module: './schemes/security-serviceaccount-token-projection.js',
    sources: [
      { label: 'K8s docs: Service Account Tokens', href: 'https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/' },
    ],
  },
  {
    id: 'workloads-pod-phase-machine',
    title: 'Pod Lifecycle Phases',
    category: 'workloads',
    subcategory: 'pods-lifecycle',
    desc: 'A Pod\'s life unfolds in a few clear stages: it starts up on a node, runs while its containers are doing work, and eventually finishes, cleanly if everything succeeded or with a failure. The phase field is the single high-level line that tells you which stage the Pod is in right now.',
    k8sVersion: '1.32',
    module: './schemes/workloads-pod-phase-machine.js',
    tinted: true,
    sources: [
      { label: 'K8s docs: Pod Lifecycle', href: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/' },
    ],
  },
  {
    id: 'workloads-restart-policy',
    title: 'Pod restartPolicy: Always, OnFailure, Never',
    category: 'workloads',
    subcategory: 'pods-lifecycle',
    desc: 'When a container in a Pod exits, what should happen next? restartPolicy is the Pod-level answer Kubernetes follows: always bring the container back, only retry when it failed, or leave it alone. The choice shapes whether the Pod runs forever, retries until success, or finishes after one go.',
    k8sVersion: '1.32',
    module: './schemes/workloads-restart-policy.js',
    tinted: true,
    sources: [
      { label: 'K8s docs: Restart policy', href: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy' },
    ],
  },
  {
    id: 'workloads-hooks',
    title: 'Lifecycle Hooks: postStart and preStop',
    category: 'workloads',
    subcategory: 'pods-lifecycle',
    desc: 'Sometimes a container needs to do something right when it starts, or right before it stops. Lifecycle hooks (postStart and preStop) are the two slots Kubernetes exposes for that code, run by the kubelet so your container can announce itself, drain connections, or wrap up cleanly around its main work.',
    k8sVersion: '1.32',
    module: './schemes/workloads-hooks.js',
    tinted: true,
    sources: [
      { label: 'K8s docs: Container Lifecycle Hooks', href: 'https://kubernetes.io/docs/concepts/containers/container-workloads-hooks/' },
    ],
  },
  {
    id: 'workloads-probes',
    title: 'Startup, Liveness and Readiness Probes',
    category: 'workloads',
    subcategory: 'pods-lifecycle',
    desc: 'Three kubelet handlers (httpGet, tcpSocket, grpc, exec) on periodSeconds intervals. startupProbe gates the other two during a slow boot, livenessProbe restarts the container after failureThreshold consecutive failures, readinessProbe toggles the Pod IP in the Service EndpointSlice without a restart.',
    k8sVersion: '1.32',
    module: './schemes/workloads-probes.js',
    tinted: true,
    sources: [
      { label: 'K8s docs: Configure Liveness, Readiness and Startup Probes', href: 'https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/' },
    ],
  },
  {
    id: 'workloads-container-states',
    title: 'Container Restarts and lastState',
    category: 'workloads',
    subcategory: 'pods-lifecycle',
    desc: 'A container crashed and restarted, what killed it? The live state shows the fresh Running instance and hides the failure, but Kubernetes preserves the previous termination next to it: lastState holds the exit code and reason, restartCount counts the restarts, and kubectl logs --previous reads the prior log stream.',
    k8sVersion: '1.32',
    module: './schemes/workloads-container-states.js',
    tinted: true,
    sources: [
      { label: 'K8s docs: Container states', href: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-states' },
    ],
  },
  {
    id: 'workloads-crashloopbackoff',
    title: 'CrashLoopBackOff and Restart Backoff',
    category: 'workloads',
    subcategory: 'pods-lifecycle',
    desc: 'A container that keeps crashing gets restarted with a growing delay between attempts, doubling from 10s up to a 5 minute ceiling so a broken process cannot saturate the node by hot-looping. The container shows up as Waiting with reason CrashLoopBackOff during each wait, the Pod phase stays Running, and the timer only resets after a sustained healthy run.',
    k8sVersion: '1.32',
    module: './schemes/workloads-crashloopbackoff.js',
    tinted: true,
    sources: [
      { label: 'K8s docs: Restart policy', href: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy' },
    ],
  },
  {
    id: 'workloads-graceful-shutdown',
    title: 'Graceful Pod Shutdown',
    category: 'workloads',
    subcategory: 'pods-lifecycle',
    desc: 'When a Pod is deleted, Kubernetes does not kill it on the spot. The kubelet runs the preStop hook, sends SIGTERM to the container, then waits out the terminationGracePeriodSeconds budget so the app can drain in-flight work, close connections and exit cleanly. SIGKILL is the last resort, used only if the container is still alive when the timer runs out.',
    k8sVersion: '1.32',
    module: './schemes/workloads-graceful-shutdown.js',
    tinted: true,
    sources: [
      { label: 'K8s docs: Termination of Pods', href: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination' },
    ],
  },
  {
    id: 'workloads-force-deletion',
    title: 'Force Deletion and Stuck Terminating Pods',
    category: 'workloads',
    subcategory: 'pods-lifecycle',
    desc: 'A Pod can get stuck in Terminating when the node hosting it goes silent. The kubelet never acknowledges the delete, so the API keeps the object around and an identity-bound controller like StatefulSet refuses to schedule a replacement. Force deletion drops the object from etcd at once, but if the node was only partitioned the original container may still run and clash with the recreated replica.',
    k8sVersion: '1.32',
    module: './schemes/workloads-force-deletion.js',
    tinted: true,
    sources: [
      { label: 'K8s docs: Force Delete StatefulSet Pods', href: 'https://kubernetes.io/docs/tasks/run-application/force-delete-stateful-set-pod/' },
      { label: 'K8s docs: Pod Lifecycle', href: 'https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination' },
    ],
  },
];

export const CATEGORY_LABEL = Object.fromEntries(CATEGORIES.map(c => [c.key, c.label]));

export const SUBCATEGORIES = {
  control: [
    { key: 'control-plane', label: 'Control Plane' },
    { key: 'worker-nodes',  label: 'Worker Nodes'  },
  ],
  workloads: [
    { key: 'pods-bootstrap', label: 'Pods Bootstrap' },
    { key: 'pods-lifecycle', label: 'Pods Lifecycle' },
    { key: 'controllers',   label: 'Controllers'    },
  ],
};
