// Static pages for crawlers and sharing, since both apps route by `#`: one per scheme card under
// scheme/card/, one per command section under cli/section/, an index of each, and sitemap.xml, built
// from the modules the apps load. `--check` writes nothing and exits 1 while anything is stale.
import { readFile, writeFile, mkdir, readdir, rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const from = (p) => import(pathToFileURL(join(ROOT, p)).href);
const CHECK = process.argv.includes('--check');

const { SCHEMES, CATEGORIES, CATEGORY_LABEL, SUBCATEGORIES } = await from('scheme/js/data.js');
const { renderPoster } = await from('scheme/js/lib/poster.js');
const { SECTIONS, COPY_ICON, CHECK_ICON } = await from('cli/js/data.js');
const { hl, sortCmds } = await from('cli/js/lib/commands.js');

const SITE = 'https://kube.how';
const MARK = '<!-- generated by tools/pages/build.mjs: edit the generator, not this file -->';
const CARD_DIR = 'scheme/card';
const SECTION_DIR = 'cli/section';
const cardPath = (id) => `/${CARD_DIR}/${id}/`;
const sectionPath = (id) => `/${SECTION_DIR}/${id}/`;

// A <title> Google shows whole: the most telling form that fits in 60 characters.
const fitTitle = (...forms) => forms.find(f => f.length <= 60) || forms[forms.length - 1];

const esc = (s) => String(s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
const jsonLd = (o) => JSON.stringify(o).replace(/</g, '\\u003c');

// A meta description: the first whole sentences that fit in 160 characters. A sentence ends at . ! or ?
// before a space and a capital, so `resolv.conf` or `127.0.0.1` never split. Under 100 characters it
// is too thin, and the text is cut at a word near 160 instead.
function summary(text, max = 160) {
  const parts = [];
  let from = 0;
  for (const m of text.matchAll(/[.!?](?=\s+[A-Z0-9"'(`]|\s*$)/g)) {
    parts.push(text.slice(from, m.index + 1).trim());
    from = m.index + 1;
  }
  if (text.slice(from).trim()) parts.push(text.slice(from).trim());
  let out = '';
  for (const p of parts) {
    const next = out ? `${out} ${p}` : p;
    if (next.length > max) break;
    out = next;
  }
  if (out.length >= 100) return out;
  return text.length <= max ? text : text.slice(0, max - 3).replace(/\s+\S*$/, '') + '...';
}

// ── Shared chrome, read out of the live pages so the static ones match them ──────────────────────
const schemeIndex = await readFile(join(ROOT, 'scheme/index.html'), 'utf8');
const cliIndex = await readFile(join(ROOT, 'cli/index.html'), 'utf8');
const pick = (html, re, what) => {
  const m = html.match(re);
  if (!m) throw new Error(`build.mjs: could not find ${what} in a live page, the template moved`);
  return m[0];
};
const FONTS = pick(schemeIndex, /  <link rel="preconnect" href="https:\/\/fonts\.googleapis\.com">[\s\S]*?<\/noscript>/, 'the font links');
const BEACON = pick(schemeIndex, /<script defer src="https:\/\/static\.cloudflareinsights\.com[^\n]*<\/script>/, 'the analytics beacon');
// The static pages have no shortcuts sheet, so the sidebar keyboard button goes.
const sidebar = (html) => pick(html, /  <aside class="sidebar"[\s\S]*?<\/aside>\s*<button class="side-expand"[\s\S]*?<\/button>/, 'the sidebar')
  .replace(/\s*<button class="side-btn side-keys"[\s\S]*?<\/button>/, '');
const logo = (html) => pick(html, /      <a class="logo" href="\/"[\s\S]*?\n      <\/a>/, 'the logo');

function page({ app, title, description, canonical, ogImage, ld, body, css }) {
  const index = app === 'scheme' ? schemeIndex : cliIndex;
  const icon = app === 'scheme' ? '/scheme/favicon.svg' : '/favicon.svg';
  const back = app === 'scheme'
    ? '<a class="action-btn" href="/scheme/">All schemes</a>'
    : '<a class="action-btn" href="/cli/">All commands</a>';
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="color-scheme" content="dark">
  <meta name="theme-color" content="#110f1f">
  <style>:root{color-scheme:dark}html,body{background:#110f1f;color:#ece9ff}</style>
  ${MARK}
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${esc(title)}</title>
  <meta name="description" content="${esc(description)}">
  <link rel="canonical" href="${canonical}">
  <meta property="og:type" content="article">
  <meta property="og:site_name" content="kube.how">
  <meta property="og:url" content="${canonical}">
  <meta property="og:title" content="${esc(title)}">
  <meta property="og:description" content="${esc(description)}">
  <meta property="og:image" content="${ogImage}">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="${esc(title)}">
  <meta name="twitter:description" content="${esc(description)}">
  <meta name="twitter:image" content="${ogImage}">
  <link rel="icon" type="image/svg+xml" href="${icon}">

${FONTS}

  <link rel="stylesheet" href="/${app}/css/styles.css">
  <link rel="stylesheet" href="/${app}/css/${css}">

  <script type="application/ld+json">${jsonLd(ld)}</script>
</head>
<body class="static-page">
${sidebar(index)}

  <header class="header">
    <div class="header-inner">
${logo(index)}
      <div class="header-actions">${back}</div>
    </div>
  </header>

${body}

  <footer class="footer">
    <p class="disclaimer">Not affiliated with the CNCF or the Kubernetes project.</p>
    <p>&copy; <span id="year"></span> <a href="/">kube.how</a></p>
  </footer>

  <script type="module">
    import { setupSidebar } from '/${app}/js/lib/sidebar.js';
    setupSidebar();
    document.getElementById('year').textContent = new Date().getFullYear();${app === 'cli' ? COPY_SCRIPT : ''}
  </script>

  ${BEACON}
</body>
</html>
`;
}

const breadcrumbLd = (items) => ({
  '@type': 'BreadcrumbList',
  itemListElement: items.map(([name, url], i) => ({ '@type': 'ListItem', position: i + 1, name, item: url })),
});

// ── Scheme card pages ────────────────────────────────────────────────────────────────────────────
// Grid order, the same walk app.js buildUnits() does: category, then subcategory, then catalog order.
const schemeOrder = [];
for (const c of CATEGORIES.filter(c => c.key !== 'all')) {
  const inCat = SCHEMES.filter(s => s.category === c.key);
  const subs = SUBCATEGORIES[c.key] || [];
  for (const sc of subs) schemeOrder.push(...inCat.filter(s => s.subcategory === sc.key));
  schemeOrder.push(...inCat.filter(s => !subs.some(sc => sc.key === s.subcategory)));
}

async function schemePage(s, i) {
  const mod = await from(`scheme/js/schemes/${s.category}/${s.id}.js`);
  // Step 0 is the poster rest frame and carries no narration: the narrated steps are 1..N, which
  // is also the index `#scheme=<id>&step=<n>` opens.
  const steps = (mod.STEPS_SPEC || []).map((st, idx) => ({ idx, text: st && st.narration })).filter(st => st.text);
  const sub = (SUBCATEGORIES[s.category] || []).find(sc => sc.key === s.subcategory);
  const cat = CATEGORY_LABEL[s.category] || s.category;
  const url = `${SITE}${cardPath(s.id)}`;
  const play = `/scheme/#scheme=${s.id}`;
  const prev = schemeOrder[i - 1], next = schemeOrder[i + 1];
  const related = schemeOrder.filter(o => o.category === s.category && o.subcategory === s.subcategory && o.id !== s.id);
  const sources = s.sources || [];
  const title = fitTitle(`${s.title}: Kubernetes animated diagram`, `${s.title} | Kubernetes diagram`, `${s.title} | Kubernetes`, s.title);
  const description = summary(s.desc);
  const body = `  <main class="page" id="main">
    <nav class="crumbs" aria-label="Breadcrumb">
      <ol>
        <li><a href="/scheme/">Schemes</a></li>
        <li><a href="/scheme/#at=${s.category}">${esc(cat)}</a></li>
        ${sub ? `<li><a href="/scheme/#at=${sub.key}">${esc(sub.label)}</a></li>` : ''}
      </ol>
    </nav>
    <article class="page-article" data-cat="${s.category}">
      <header class="page-head">
        <div class="page-tags"><span class="page-cat">${esc(cat)}</span><span class="page-version">k8s ${esc(s.k8sVersion)}</span></div>
        <h1>${esc(s.title)}</h1>
        <p class="page-lede">${esc(s.desc)}</p>
        <p class="page-cta">
          <a class="page-play" href="${play}"><span aria-hidden="true">&#9654;</span> Play the animation</a>
          <span class="page-play-note">${steps.length} steps, animated, best on a wide screen</span>
        </p>
      </header>
      <figure class="page-poster">${renderPoster(s)}</figure>
      <section class="page-steps" aria-labelledby="steps-h">
        <h2 id="steps-h">How it works, step by step</h2>
        <ol>
${steps.map(st => `          <li id="step-${st.idx}">
            <p>${esc(st.text)}</p>
            <a class="page-step-play" href="${play}&amp;step=${st.idx}">Play from this step</a>
          </li>`).join('\n')}
        </ol>
      </section>
${sources.length ? `      <section class="page-sources" aria-labelledby="sources-h">
        <h2 id="sources-h">Sources</h2>
        <ul>${sources.map(src => `<li><a href="${esc(src.href)}" target="_blank" rel="noopener">${esc(src.label)}</a></li>`).join('')}</ul>
      </section>
` : ''}      <nav class="page-pager" aria-label="Previous and next scheme">
        ${prev ? `<a rel="prev" href="${cardPath(prev.id)}"><small>Previous</small>${esc(prev.title)}</a>` : '<span></span>'}
        ${next ? `<a rel="next" href="${cardPath(next.id)}"><small>Next</small>${esc(next.title)}</a>` : '<span></span>'}
      </nav>
${related.length ? `      <section class="page-related" aria-labelledby="related-h">
        <h2 id="related-h">More in ${esc(sub ? sub.label : cat)}</h2>
        <ul>${related.map(o => `<li><a href="${cardPath(o.id)}">${esc(o.title)}</a></li>`).join('')}</ul>
      </section>
` : ''}    </article>
  </main>`;
  const ld = [
    {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      headline: s.title,
      description: s.desc,
      url,
      image: `${SITE}/images/og-scheme.png`,
      inLanguage: 'en',
      about: { '@type': 'Thing', name: 'Kubernetes' },
      proficiencyLevel: 'Intermediate',
      isPartOf: { '@type': 'WebSite', name: 'kube.how', url: `${SITE}/` },
    },
    { '@context': 'https://schema.org', ...breadcrumbLd([['kube.how', `${SITE}/`], ['Schemes', `${SITE}/scheme/`], ['All schemes', `${SITE}/${CARD_DIR}/`], [s.title, url]]) },
  ];
  return page({ app: 'scheme', title, description, canonical: url, ogImage: `${SITE}/images/og-scheme.png`, ld, body, css: 'page.css' });
}

// ── Command section pages ────────────────────────────────────────────────────────────────────────
// The /cli/ category of a section, by its `sub` label. app.js keeps the same map as CATEGORIES.
const CLI_CAT = {
  Installation: ['installation', 'kubernetes'],
  Cluster: ['cluster', 'kubernetes'],
  Workloads: ['workloads', 'kubernetes'],
  Helm: ['helm', 'tools'],
  Kustomize: ['kustomize', 'tools'],
  K9s: ['k9s', 'tools'],
  'Debug K8s': ['troubleshooting-kubernetes', 'troubleshooting'],
  'Debug Tools': ['troubleshooting-tools', 'troubleshooting'],
};
// The words a search for these commands would use: `kubectl Pods`, `Helm Releases`, `Kubeadm`.
function cliHeading(sec) {
  switch (sec.sub) {
    case 'Installation': return `${sec.title} commands`;
    case 'Cluster':
    case 'Workloads': return `kubectl ${sec.title} commands`;
    // "K9s UI Shortcuts" is a list of keys, not of commands.
    case 'Helm': case 'Kustomize': case 'K9s': return /shortcuts/i.test(sec.title) ? `${sec.sub} ${sec.title}` : `${sec.sub} ${sec.title} commands`;
    case 'Debug K8s': return `Debug Kubernetes ${sec.title}: troubleshooting commands`;
    case 'Debug Tools': return `Debug ${sec.title}: troubleshooting commands`;
    default: return `${sec.title} commands`;
  }
}

const COPY_SCRIPT = `
    // Copy on a click anywhere on a command, as on /cli/.
    const COPY = ${JSON.stringify(COPY_ICON)}, CHECK = ${JSON.stringify(CHECK_ICON)};
    // The section index (/cli/section/) has no commands, so the handler is attached only where they are.
    document.querySelector('.page-cli')?.addEventListener('click', (e) => {
      const item = e.target.closest('.cmd-item');
      if (!item) return;
      const btn = item.querySelector('.copy-btn');
      const done = () => {
        btn.innerHTML = CHECK; btn.classList.add('copied');
        setTimeout(() => { btn.innerHTML = COPY; btn.classList.remove('copied'); }, 1500);
      };
      if (navigator.clipboard && window.isSecureContext) navigator.clipboard.writeText(item.dataset.raw).then(done, () => {});
    });`;

function cliPage(sec, i) {
  const [catKey, group] = CLI_CAT[sec.sub] || [];
  if (!catKey) throw new Error(`build.mjs: section ${sec.id} has an unknown sub label "${sec.sub}", add it to CLI_CAT`);
  const url = `${SITE}${sectionPath(sec.id)}`;
  const total = sec.groups.reduce((n, g) => n + g.cmds.length, 0);
  const heading = cliHeading(sec);
  const groupNames = sec.groups.map(g => g.title).join(', ');
  const prev = SECTIONS[i - 1], next = SECTIONS[i + 1];
  const related = SECTIONS.filter(o => o.sub === sec.sub && o.id !== sec.id);
  const title = fitTitle(`${heading} cheat sheet`, heading);
  const description = summary(`${total} copy-ready ${heading}: ${groupNames}.${sec.version ? ` Checked against ${sec.version}.` : ''} Each with a one-line explanation.`);
  const cards = sec.groups.map((g, gi) => `
        <div class="card" data-card="${gi}">
          <h2 class="card-title">${esc(g.title)}</h2>
          ${g.desc ? `<div class="card-desc">${esc(g.desc)}</div>` : ''}
          <div class="cmd-list">${sortCmds(g.cmds).map(c => `
            <div class="cmd-item" data-raw="${esc(c.cmd)}">
              <code class="cmd-code">${hl(c.cmd)}</code>
              <div class="cmd-desc">${esc(c.desc)}</div>
              <button class="copy-btn" type="button" title="Copy command" aria-label="Copy command">${COPY_ICON}</button>
            </div>`).join('')}
          </div>
        </div>`).join('');
  const body = `  <main class="main page-cli" id="main">
    <nav class="crumbs" aria-label="Breadcrumb">
      <ol>
        <li><a href="/cli/">Commands</a></li>
        <li><a href="/cli/#${catKey}">${esc(sec.sub)}</a></li>
        <li><a href="/cli/#${sec.id}">${esc(sec.title)}</a></li>
      </ol>
    </nav>
    <section class="section" data-section="${sec.id}" data-cat="${catKey}" data-group="${group}">
      <div class="section-header">
        <div class="section-icon">${sec.icon}</div>
        <h1 class="section-title">${esc(heading)}</h1>
        <span class="section-meta">
          ${sec.version ? `<span class="section-version">${esc(sec.version)}</span>` : ''}
          <span class="section-count">${total} ${total === 1 ? 'command' : 'commands'}</span>
        </span>
      </div>
      <p class="page-lede">${total} commands in ${sec.groups.length} groups: ${esc(groupNames)}. Click any command to copy it.${sec.docs ? ` Official documentation: <a href="${esc(sec.docs)}" target="_blank" rel="noopener">${esc(new URL(sec.docs).host)}</a>.` : ''}</p>
      <p class="page-cta"><a class="page-open" href="/cli/#${sec.id}">Open in the interactive cheat sheet</a> <span class="page-play-note">search, stars and every other section</span></p>
      <div class="cards-grid">${cards}
      </div>
    </section>
    <nav class="page-pager" aria-label="Previous and next section">
      ${prev ? `<a rel="prev" href="${sectionPath(prev.id)}"><small>Previous</small>${esc(cliHeading(prev))}</a>` : '<span></span>'}
      ${next ? `<a rel="next" href="${sectionPath(next.id)}"><small>Next</small>${esc(cliHeading(next))}</a>` : '<span></span>'}
    </nav>
${related.length ? `    <section class="page-related" aria-labelledby="related-h">
      <h2 id="related-h">More ${esc(sec.sub)} sections</h2>
      <ul>${related.map(o => `<li><a href="${sectionPath(o.id)}">${esc(o.title)}</a></li>`).join('')}</ul>
    </section>
` : ''}  </main>`;
  const ld = [
    {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      headline: heading,
      description,
      url,
      image: `${SITE}/images/og-image.png`,
      inLanguage: 'en',
      about: { '@type': 'Thing', name: 'Kubernetes' },
      isPartOf: { '@type': 'WebSite', name: 'kube.how', url: `${SITE}/` },
    },
    { '@context': 'https://schema.org', ...breadcrumbLd([['kube.how', `${SITE}/`], ['Commands', `${SITE}/cli/`], ['All sections', `${SITE}/${SECTION_DIR}/`], [heading, url]]) },
  ];
  return page({ app: 'cli', title, description, canonical: url, ogImage: `${SITE}/images/og-image.png`, ld, body, css: 'page.css' });
}

// ── The two index pages ──────────────────────────────────────────────────────────────────────────
// /scheme/card/ and /cli/section/: every card, every section, grouped as the apps group them. A
// trimmed URL lands on a real page instead of a 404, and a crawler reaches every page in one hop.
function schemeIndexPage() {
  const groups = [];
  for (const c of CATEGORIES.filter(c => c.key !== 'all')) {
    const inCat = schemeOrder.filter(s => s.category === c.key);
    const subs = (SUBCATEGORIES[c.key] || []).map(sc => [sc.label, inCat.filter(s => s.subcategory === sc.key)]).filter(g => g[1].length);
    groups.push([CATEGORY_LABEL[c.key] || c.key, c.key, subs]);
  }
  const title = 'All Kubernetes schemes: animated architecture diagrams';
  const description = `All ${SCHEMES.length} animated Kubernetes architecture diagrams on kube.how, grouped by Cluster, Workloads, Networking and Storage, each explained step by step.`;
  const url = `${SITE}/${CARD_DIR}/`;
  const body = `  <main class="page" id="main">
    <nav class="crumbs" aria-label="Breadcrumb"><ol><li><a href="/scheme/">Schemes</a></li></ol></nav>
    <article class="page-article page-index">
      <header class="page-head">
        <h1>All Kubernetes schemes</h1>
        <p class="page-lede">${SCHEMES.length} animated diagrams of how Kubernetes works inside, each explained step by step. Pick one to read it, or <a href="/scheme/">browse them as a grid</a>.</p>
      </header>
${groups.map(([label, key, subs]) => `      <section class="page-index-group" data-cat="${key}" aria-labelledby="g-${key}">
        <h2 id="g-${key}">${esc(label)}</h2>
${subs.map(([sl, list]) => `        <h3>${esc(sl)}</h3>
        <ul>${list.map(s => `<li><a href="${cardPath(s.id)}">${esc(s.title)}</a></li>`).join('')}</ul>`).join('\n')}
      </section>`).join('\n')}
    </article>
  </main>`;
  const ld = [
    { '@context': 'https://schema.org', '@type': 'CollectionPage', name: title, description, url, isPartOf: { '@type': 'WebSite', name: 'kube.how', url: `${SITE}/` } },
    { '@context': 'https://schema.org', ...breadcrumbLd([['kube.how', `${SITE}/`], ['Schemes', `${SITE}/scheme/`], ['All schemes', url]]) },
  ];
  return page({ app: 'scheme', title, description, canonical: url, ogImage: `${SITE}/images/og-scheme.png`, ld, body, css: 'page.css' });
}

function sectionIndexPage() {
  const subs = [...new Set(SECTIONS.map(s => s.sub))];
  const total = SECTIONS.reduce((n, s) => n + s.groups.reduce((m, g) => m + g.cmds.length, 0), 0);
  const title = 'All Kubernetes command sections: kubectl, Helm, Kustomize, K9s';
  const description = `Every section of the kube.how Kubernetes cheat sheet: ${total} copy-ready commands for kubectl, Helm, Kustomize, K9s and troubleshooting, in ${SECTIONS.length} sections.`;
  const url = `${SITE}/${SECTION_DIR}/`;
  const body = `  <main class="page page-sections" id="main">
    <nav class="crumbs" aria-label="Breadcrumb"><ol><li><a href="/cli/">Commands</a></li></ol></nav>
    <article class="page-article page-index">
      <header class="page-head">
        <h1>All command sections</h1>
        <p class="page-lede">${total} copy-ready commands in ${SECTIONS.length} sections. Pick one to see its commands, or <a href="/cli/">search them all at once</a>.</p>
      </header>
${subs.map(sub => `      <section class="page-index-group" aria-labelledby="g-${(CLI_CAT[sub] || [sub])[0]}">
        <h2 id="g-${(CLI_CAT[sub] || [sub])[0]}">${esc(sub)}</h2>
        <ul>${SECTIONS.filter(s => s.sub === sub).map(s => `<li><a href="${sectionPath(s.id)}">${esc(cliHeading(s))}</a></li>`).join('')}</ul>
      </section>`).join('\n')}
    </article>
  </main>`;
  const ld = [
    { '@context': 'https://schema.org', '@type': 'CollectionPage', name: title, description, url, isPartOf: { '@type': 'WebSite', name: 'kube.how', url: `${SITE}/` } },
    { '@context': 'https://schema.org', ...breadcrumbLd([['kube.how', `${SITE}/`], ['Commands', `${SITE}/cli/`], ['All sections', url]]) },
  ];
  return page({ app: 'cli', title: fitTitle(title, 'All Kubernetes command sections'), description: summary(description), canonical: url, ogImage: `${SITE}/images/og-image.png`, ld, body, css: 'page.css' });
}

// ── Sitemap ──────────────────────────────────────────────────────────────────────────────────────
// No <lastmod>: it would have to come from git, and a date that changes on every commit would make
// --check fail right after any commit. Google reads lastmod only when it is consistently right.
function sitemap() {
  const urls = [
    [`${SITE}/`, '1.0'], [`${SITE}/cli/`, '0.9'], [`${SITE}/scheme/`, '0.9'],
    [`${SITE}/${CARD_DIR}/`, '0.8'], [`${SITE}/${SECTION_DIR}/`, '0.8'],
    ...schemeOrder.map(s => [`${SITE}${cardPath(s.id)}`, '0.7']),
    ...SECTIONS.map(s => [`${SITE}${sectionPath(s.id)}`, '0.7']),
  ];
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- generated by tools/pages/build.mjs: edit the generator, not this file -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map(([loc, pr]) => `  <url>
    <loc>${loc}</loc>
    <changefreq>weekly</changefreq>
    <priority>${pr}</priority>
  </url>`).join('\n')}
</urlset>
`;
}

// ── Write or check ───────────────────────────────────────────────────────────────────────────────
for (const id of [...SCHEMES.map(s => s.id), ...SECTIONS.map(s => s.id)]) {
  if (!/^[a-z0-9-]+$/.test(id)) throw new Error(`build.mjs: "${id}" cannot be a page directory`);
}

const want = new Map();
for (const [i, s] of schemeOrder.entries()) want.set(`${CARD_DIR}/${s.id}/index.html`, await schemePage(s, i));
want.set(`${CARD_DIR}/index.html`, schemeIndexPage());
for (const [i, s] of SECTIONS.entries()) want.set(`${SECTION_DIR}/${s.id}/index.html`, cliPage(s, i));
want.set(`${SECTION_DIR}/index.html`, sectionIndexPage());
want.set('sitemap.xml', sitemap());

// A stale generated page: a directory whose index.html carries MARK and is not in `want`, including
// one straight under scheme/ or cli/ (the old location). Nothing without MARK is ever touched.
const stale = [];
for (const app of ['scheme', 'cli', CARD_DIR, SECTION_DIR]) {
  if (!existsSync(join(ROOT, app))) continue;
  for (const d of await readdir(join(ROOT, app), { withFileTypes: true })) {
    if (!d.isDirectory()) continue;
    const rel = `${app}/${d.name}/index.html`;
    if (want.has(rel) || !existsSync(join(ROOT, rel))) continue;
    if ((await readFile(join(ROOT, rel), 'utf8')).includes(MARK)) stale.push(`${app}/${d.name}`);
  }
}

const changed = [];
for (const [rel, html] of want) {
  const file = join(ROOT, rel);
  const cur = existsSync(file) ? await readFile(file, 'utf8') : null;
  if (cur === html) continue;
  changed.push(rel);
  if (!CHECK) {
    await mkdir(dirname(file), { recursive: true });
    await writeFile(file, html);
  }
}
if (!CHECK) for (const dir of stale) await rm(join(ROOT, dir), { recursive: true });

if (CHECK) {
  if (changed.length || stale.length) {
    console.error(`pages are out of date: ${changed.length} to write, ${stale.length} to delete. Run: node tools/pages/build.mjs`);
    for (const f of [...changed, ...stale].slice(0, 20)) console.error(`  ${f}`);
    process.exit(1);
  }
  console.log(`pages up to date: ${want.size - 1} pages + sitemap.xml`);
} else {
  console.log(`wrote ${changed.length} file(s), deleted ${stale.length} stale page(s); ${want.size - 1} pages + sitemap.xml in total`);
}
